--[[--------------------------------------------------
003_Horde_40to50.lua
Authors: mrmr
Version: 1.04.2
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 40 to Lvl 50
    1.04.1
        -- First Release
            Horde's Guide
            from level 40 to lever 50
    1.04.2
    	-- no changes in here for this revision
	1.1.0
		-- Автор перевода и актуализации: Eynschteyn
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Horde_40to50 = {
-----------40-41 Badlands
	--[401] = {
	[4041] = {
		title = "40-41 Badlands",
		--n = "40-41 Badlands",
		--pID = 311, nID = 402,
		--itemCount = 29,
		items = {
			[1] = { str = "1. 40-41 Badlands" },
			[2] = { str = "2. Цель — не уходить из зоны, пока не получите 41 уровень, так что гриндите мобов по пути куда бы вы ни шли Как только войдёте в Badlands, бегите на юго-запад в точку 42.52", x = 42, y = 52, zone = "Badlands" },
			[3] = { str = "3. Сдайте задание #TURNIN\"Martek the Exiled\"# (в точке 42.52) и возьмите #ACCEPT\"Indurium\"# и #ACCEPT\"Barbecued Buzzard Wings\"#", x = 42, y = 52, zone = "Badlands" },
			[4] = { str = "4. Спуститесь чуть южнее и выполните задание #DOQUEST\"Indurium\"# в точке 51.67", x = 51, y = 67, zone = "Badlands" },
			[5] = { str = "5. Вернитесь назад и сдайте задание #TURNIN\"Indurium\"# и возьмите #ACCEPT\"News for Fizzle\"#" },
			[6] = { str = "6. Затем идите на северо-запад и возьмите задание #ACCEPT\"Study of the Elements: Rock\"# (в точке 25.44). #VIDEONOTE:# Если у вас есть предметы #NPCFrost Oil#, #NPCGyrochronatom#, #NPCHealing Potion#, #NPCLesser Invisibility Potion# и #NPCPatterned Bronze Bracers# — возьмите и выполните там все задания.", x = 25, y = 44, zone = "Badlands" },
			[7] = { str = "7. Прогриндите свой путь на запад до Kargath (точка 4.46)", x = 4, y = 46, zone = "Badlands" },
			[8] = { str = "8. Откройте полетчика в Kargath." },
			[9] = { str = "9. НЕ делайте Kargath вашим домом. (домом должен оставаться Booty Bay)" },
			[10] = { str = "10. Возьмите задания: #ACCEPT\"Coyote Thieves\"#, #ACCEPT\"Report to Helgrum\"#, #ACCEPT\"Broken Alliances\"# и #ACCEPT\"Badlands Reagent Run\"#" },
			[11] = { str = "11. Затем выполните:" },
			[12] = { str = "12. #DOQUEST\"Barbecued Buzzard Wings\"# " },
			[13] = { str = "13. #DOQUEST\"Coyote Thieves\"# " },
			[14] = { str = "14. #DOQUEST\"Broken Alliances\"# (Следующую часть этого задания ПРОПУСТИТЕ)" },
			[15] = { str = "15. #DOQUEST\"Badlands Reagent Run\"# " },
			[16] = { str = "16. #DOQUEST\"Study of the Elements: Rock\"# (#NPClesser rock elementals#), сдайте задание сразу после выполнения" },
			[17] = { str = "17. #DOQUEST\"Study of the Elements: Rock\"# (#NPCrock elementals#), сдайте задание сразу после выполнения" },
			[18] = { str = "18. #DOQUEST\"Study of the Elements: Rock\"# (#NPCgreater rock elementals#)" },
			[19] = { str = "19. Затем убедитесь, что все задания в Badlands (кроме #ACCEPT\"Report to Helgrum\"#) выполнены и сданы." },
			[20] = { str = "20. Сейчас у вас должен быть примерно 41 уровень, если нет — гриндите мобов до него." },
			[21] = { str = "21. Жмите Hearth в BB и проверьте, есть ли в вашем журнале задание #DOQUEST\"Dream Dust in the Swamp\"#. Если нет — возьмите его у Krazek в точке 27.77", x = 27, y = 77, zone = "Stranglethorn Vale" },
			[22] = { str = "22. Летите в Grom'gol." },
			[23] = { str = "23. Сдайте все главы/задания #NPCThe Green Hills of Stranglethorn Chapters/Quests# в Nesingwary's Expedition (точка 35.10), если у вас есть все страницы; если нет — позже будет ещё возможность сдать это задание. Недостающие страницы можно поискать на аукционе (AH).", x = 35, y = 10, zone = "Badlands" },
			[24] = { str = "24. Затем бегите до Swamp of Sorrows, по пути зайдите взять задание: #ACCEPT\"Nothing But the Truth\"# (в Duskwood в точке 87.35)", x = 87, y = 35, zone = "Duskwood" },
			[25] = { str = "25. Затем сдайте задание #TURNIN\"Nothing But the Truth\"# (НПС стоит рядом с ним)" },
			[26] = { str = "26. Снова возьмите #ACCEPT\"Nothing But the Truth\"#" },
			[27] = { str = "27. Затем бегите в Swamp of Sorrows..." },
			--[28] = { str = "." },
			--[29] = { str = "." },
		}
	},

-----------41-42 Swamp of Sorrows
	--[402] = {
	[4142] = {
		title = "41-42 Swamp of Sorrows",
		--n = "41-42 Swamp of Sorrows",
		--pID = 401, nID = 403,
		--itemCount = 27,
		items = {
			[1] = { str = "1. 41-42 Swamp of Sorrows" },
			[2] = { str = "2. Начните с задания: #DOQUEST\"Dream Dust in the Swamp\"# (точка 14.59). Для его выполнения может понадобиться несколько вылазок в эту зону..", x = 14, y = 59, zone = "Swamp of Sorrows" },
			[3] = { str = "3. #DOQUEST\"Nothing But the Truth\"# — убейте Mire Lord ради Mire Lord Fungus (в точке 6.32)", x = 6, y = 32, zone = "Swamp of Sorrows" },
			[4] = { str = "4. Найдите и убейте #NPCCudgel# (в точке 47.39), с него падает Noboru's Cudgel, который начинает задание #ACCEPT\"Noboru the Cudgel\"#" },
			[5] = { str = "5. Сдайте задание #TURNIN\"Noboru the Cudgel\"# (точка 25.31) и возьмите #ACCEPT\"Draenethyst Crystals\"#", x = 25, y = 31, zone = "Swamp of Sorrows" },
			[6] = { str = "6. Прогриндите путь до Stonard (точка 45.54)", x = 45, y = 54, zone = "Swamp of Sorrows" },
			[7] = { str = "7. Сделайте Stonard вашим домом." },
			[8] = { str = "8. Возьмите задания #ACCEPT\"Lack of Surplus\"# и #ACCEPT\"#NPCFresh Meat\"#" },
			[9] = { str = "9. Откройте полетчика." },
			[10] = { str = "10. Сдайте задание #TURNIN\"Report to Helgrum\"# и возьмите #ACCEPT\"Pool of Tears\"# (элитное)" },
			[11] = { str = "11. Выполните следующие задания:" },
			[12] = { str = "12. #DOQUEST\"Pool of Tears\"# (артефакты лежат в воде вокруг храма Atal'Hakkar)" },
			[13] = { str = "13. #DOQUEST\"Lack of Surplus\"#, затем сдайте его (в точке 81.80) и возьмите #ACCEPT\"Lack of Surplus\"# часть 2, выполните её", x = 81, y = 80, zone = "Swamp of Sorrows" },
			[14] = { str = "14. Выполните #DOQUEST\"Fresh Meat\"# и #DOQUEST\"Nothing But the Truth\"# (сердца #NPCShadow Panthers#)" },
			[15] = { str = "15. #DOQUEST\"Draenethyst Crystals\"#, затем сдайте его в точке 25.31", x = 25, y = 31, zone = "Swamp of Sorrows" },
			[16] = { str = "16. #DOQUEST\"Ongeku\"# " },
			[17] = { str = "17. Сдайте #TURNIN\"Lack of Surplus\"# часть 2 и возьмите #ACCEPT\"Threat From the Sea\"#" },
			[18] = { str = "18. Сдайте #TURNIN\"Threat From the Sea\"#, затем снова возьмите #ACCEPT\"Threat From the Sea\"#" },
			[19] = { str = "19. Выполните #DOQUEST\"Threat From the Sea\"# вместе с #DOQUEST\"Fresh Meat\"#" },
			[20] = { str = "20. Сдайте #TURNIN\"Threat From the Sea\"# и возьмите #ACCEPT\"Continued Threat\"#" },
			[21] = { str = "21. Выполните #DOQUEST\"Continued Threat\"#, затем сдайте его." },
			[22] = { str = "22. Жмите Hearth в Stonard." },
			[23] = { str = "23. Сдайте #TURNIN\"Fresh Meat\"# и #TURNIN\"Pool of Tears\"# и возьмите #ACCEPT\"The Atal'ai Exile\"#" },
			[24] = { str = "24. Сейчас должен быть примерно 42 уровень, если нет — гриндите до него. #HUNTERВыучите новые способности охотника у тренера.#" },
			[25] = { str = "25. Летите в Grom'gol..." },
			--[26] = { str = "." },
			--[27] = { str = "." },
		}
	},

-----------42-43 Stranglethorn Vale
	--[403] = {
	[4243] = {
		title = "42-43 Stranglethorn Vale",
		--n = "42-43 Stranglethorn Vale",
		--pID = 402, nID = 404,
		--itemCount = 23,
		items = {
			[1] = { str = "1. 42-43 Stranglethorn Vale" },
			[2] = { str = "2. Возьмите #ACCEPT\"Mok'thardin's Enchantment\"# часть 4 и #ACCEPT\"Split Bone Necklace\"#" },
			[3] = { str = "3. Летите в Booty Bay" },
			[4] = { str = "4. Возьмите ВСЕ задания в BB: #ACCEPT\"The Bloodsail Buccaneers\"#, #ACCEPT\"Up to Snuff\"#, #ACCEPT\"Zanzil's Secret\"#, #ACCEPT\"Akiris by the Bundle\"#, #ACCEPT\"Voodoo Dues\"#, #ACCEPT\"Stoley's Debt\"#, #ACCEPT\"Stranglethorn Fever\"# и #ACCEPT\"Keep An Eye Out\"#" },
			[5] = { str = "5. Сдайте задание #TURNIN\"Dream Dust in the Swamp\"#" },
			[6] = { str = "6. Сделайте BB вашим домом." },
			[7] = { str = "7. Затем выполняйте в следующем порядке:" },
			[8] = { str = "8. #DOQUEST\"The Bloodsail Buccaneers\"# вместе с #DOQUEST\"Up to Snuff\"# и #DOQUEST\"Keep An Eye Out\"# (делаются на побережье около 31.80, ещё мобов можно найти в 27.70). Также выполните #DOQUEST\"Stranglethorn Fever\"# (для него понадобится один клык гориллы, а знахарь сидит в пещере в точке 34.60)", x = 31, y = 80, zone = "Stranglethorn Vale" },
			[9] = { str = "9. #DOQUEST\"Mok'thardin's Enchantment\"# часть 4 вместе с #DOQUEST\"Akiris by the Bundle\"# (точка 25.63)", x = 25, y = 63, zone = "Stranglethorn Vale" },
			[10] = { str = "10. #DOQUEST\"Zanzil's Secret\"# вместе с #DOQUEST\"Voodoo Dues\"# (точки 34.52 и 39.58)", x = 34, y = 52, zone = "Stranglethorn Vale" },
			[11] = { str = "11. #DOQUEST\"Skullsplitter Tusks\"# вместе с #DOQUEST\"Split Bone Necklace\"#" },
			[12] = { str = "12. Гриндите троллей Skullsplitter, пока до 43 уровня не останется минимум 2-3 полоски опыта." },
			[13] = { str = "13. Жмите Hearth в Booty Bay" },
			[14] = { str = "14. Сдайте ВСЕ задания и обязательно возьмите #ACCEPT\"Tran'Rek\"# и #ACCEPT\"Rumors for Kravel\"# у Krazek, а также #ACCEPT\"Whiskey Slim's Lost Grog\"# у Whiskey Slim" },
			[15] = { str = "15. Летите в Grom'gol" },
			[16] = { str = "16. Сдайте #TURNIN\"Mok'thardin's Enchantment\"# часть 4 и #TURNIN\"Split Bone Necklace\"#" },
			[17] = { str = "17. Возьмите задание #ACCEPT\"Grim Message\"#" },
			[18] = { str = "18. Садитесь на дирижабль до Orgrimmar" },
			[19] = { str = "19. По прилёту идите к Belgrom Rockmaul в точке 75.34 и возьмите задание #ACCEPT\"A Threath in Ferelas\"#", x = 75, y = 34, zone = "Orgrimmar" },
			[20] = { str = "20. Летите в Thunder Bluff" },
			[21] = { str = "21. Сдайте задания #TURNIN\"The Black Shield\"# и #TURNIN\"Frostmaw\"# и возьмите #ACCEPT\"Deadmire\"# (подсказка: гриву Frostmaw я обычно долго храню в банке)" },
			[22] = { str = "22. Летите в Desolace, если вы ещё не прошли 4-5 полосок 43 уровня, или в Dustwallow Marsh, если прошли." },
			--[22] = { str = "." },
			--[23] = { str = "." },
		}
	},

-----------43-43 Desolace
	--[404] = {
	[4342] = {
		title = "43-43 Desolace",
		--n = "43-43 Desolace",
		--pID = 403, nID = 405,
		--itemCount = 16,
		items = {
			[1] = { str = "1. 43-43 Desolace" },
			[2] = { str = "2. ОПЦИОНАЛЬНО: весь этот раздел можно пропустить, если вы уже прошли 4-5 полосок 43 уровня и больше; ничего страшного не будет, если пропустить раздел и пойти сразу в Dustwallow Marsh." },
			[3] = { str = "3. Сделайте Shadowprey Village вашим домом." },
			[4] = { str = "4. Возьмите задание #ACCEPT\"Portals of the Legion\"#" },
			[5] = { str = "5. Сдайте задание #TURNIN\"Ongeku\"# в точке 36.79 и ПРОПУСТИТЕ #NPC\"Khan Jehn\"#", x = 36, y = 79, zone = "Desolace" },
			[6] = { str = "6. Пока вы в Desolace, высматривайте элитного великана для задания #NPC\"Nothing But the Truth\"#..." },
			[7] = { str = "7. ...если не найдёте великана и не добудёте \"#NPCDeepstrider Tumor#\", задание придётся бросить; я не трачу время на поиски deepstrider-великана по всей зоне." },
			[8] = { str = "8. затем идите в Mannoroc Coven в точке 50.76 и сделайте:", x = 50, y = 76, zone = "Desolace" },
			[9] = { str = "9. #DOQUEST\"Portals of the Legion\"#" },
			[10] = { str = "10. #DOQUEST\"The Corrupter\"# (элитное) (убейте #NPCLord Azrethoc# и #NPCJugkar Grim'rod#)" },
			[11] = { str = "11. Сдайте #TURNIN\"The Corrupter\"# (элитное) в точке 53.54", x = 53, y = 54, zone = "Desolace" },
			[12] = { str = "12. затем жмите Hearth в Shadowprey Village" },
			[13] = { str = "13. Сдайте задание #TURNIN\"Portals of the Legion\"#" },
			[14] = { str = "14. Летите в TB (Thunder Bluff), затем в Dustwallow Marsh..." },
			--[15] = { str = "." },
			--[16] = { str = "." },
		}
	},

-----------43-43 Dustwallow Marsh
	--[405] = {
	[4343] = {
		title = "43-43 Dustwallow Marsh",
		--n = "43-43 Dustwallow Marsh",
		--pID = 404, nID = 406,
		--itemCount = 14,
		items = {
			[1] = { str = "1. 43-43 Dustwallow Marsh" },
			[2] = { str = "2. Возьмите задание #ACCEPT\"Identifying the Brood\"#" },
			[3] = { str = "3. Спуститесь в точку 40.36, возьмите задание #DOQUEST\"Questioning Reethe\"# и выполните его.", x = 40, y = 36, zone = "Dustwallow Marsh" },
			[4] = { str = "4. Спуститесь и выполните:" },
			[5] = { str = "5. #DOQUEST\"Deadmire\"# " },
			[6] = { str = "6. #DOQUEST\"Marg Speaks\"# — убивайте мобов около точки 58.63", x = 58, y = 63, zone = "Dustwallow Marsh" },
			[7] = { str = "7. #DOQUEST\"Identifying the Brood\"# " },
			[8] = { str = "8. Затем прогриндите путь обратно до Brackenwall Village" },
			[9] = { str = "9. Сдайте #TURNIN\"Questioning Reethe\"# и #TURNIN\"Identifying the Brood\"# и возьмите #ACCEPT\"The Brood of Onyxia\"#" },
			[10] = { str = "10. Бегайте туда-сюда, пока не выполните #DOQUEST\"The Brood of Onyxia\"#, но финальную часть пока не делайте (она делается позже, на #NPClevel 48#, так что пока задание можно бросить)." },
			[11] = { str = "11. Сдайте #TURNIN\"Marg Speaks\"# и возьмите #ACCEPT\"Report to Zor\"#" },
			[12] = { str = "12. Летите в Tanaris..." },
			--[13] = { str = "." },
			--[14] = { str = "." },
		}
	},

-----------43-44 Tanaris
	--[406] = {
	[4344] = {
		title = "43-44 Tanaris",
		--n = "43-44 Tanaris",
		--pID = 405, nID = 407,
		--itemCount = 36,
		items = {
			[1] = { str = "1. 43-44 Tanaris" },
			[2] = { str = "2. Идите в Gadgetzan..." },
			[3] = { str = "3. Возьмите задания: #ACCEPT\"WANTED: Caliph Scorpidsting\"# и #ACCEPT\"WANTED: Andre Firebeard\"# (розыскной плакат)" },
			[4] = { str = "4. Сдайте задание #TURNIN\"Tran'Rek\"#" },
			[5] = { str = "5. Возьмите задания: #ACCEPT\"Gadgetzan Water Survey\"#, #ACCEPT\"Wastewander Justice\"# и #ACCEPT\"Water Pouch Bounty\"#" },
			[6] = { str = "6. Сделайте Gadgetzan вашим домом." },
			[7] = { str = "7. Идите в Shimmering Flats (в Thousand Needles, точка 78.77) и сдайте #TURNIN\"Rumors for Kravel\"#, #TURNIN\"News for Fizzle\"# и #TURNIN\"Razzeric's Tweaking\"# и возьмите #ACCEPT\"Safety First\"#", x = 53, y = 76, zone = "Tanaris" },
			[8] = { str = "8. Возьмите задание #ACCEPT\"Keeping Pace\"#" },
			[9] = { str = "9. Сдайте #TURNIN\"Keeping Pace\"# у Zamek, затем заберите Rizzle's Plans в точке 77.77 и возьмите задание #ACCEPT\"Rizzle's Schematics\"#" },
			[10] = { str = "10. Возьмите задание #ACCEPT\"Back to Booty Bay\"# (у Kravel Koalbeard)" },
			[11] = { str = "11. Сдайте задание #TURNIN\"Rizzle's Schematics\"# у Pozzik." },
			[12] = { str = "12. Жмите Hearth обратно в Gadgetzan." },
			[13] = { str = "13. Сдайте #TURNIN\"Safety First\"# и я ПРОПУСКАЮ следующую часть этого задания." },
			[14] = { str = "14. Затем прогриндите путь на восток до Steamwheedle Port (точка 67.23)", x = 67, y = 23, zone = "Tanaris" },
			[15] = { str = "15. Возьмите задания: #ACCEPT\"Pirate Hats Ahoy!\"#, #ACCEPT\"Screecher Spirits\"# и #ACCEPT\"Southsea Shakedown\"#" },
			[16] = { str = "16. Сдайте #TURNIN\"Stoley's Debt\"# и возьмите #ACCEPT\"Stoley's Shipment\"#" },
			[17] = { str = "17. Затем выполните эти задания:" },
			[18] = { str = "18. #DOQUEST\"Wastewander Justice\"# вместе с #DOQUEST\"Water Pouch Bounty\"# (в точке 64.29)", x = 64, y = 29, zone = "Tanaris" },
			[19] = { str = "19. Затем выполните всё следующее (шаги 19-23) в Lost Rigger Cove (точка 72.47):", x = 72, y = 47, zone = "Tanaris" },
			[20] = { str = "20. #DOQUEST\"Southsea Shakedown\"# " },
			[21] = { str = "21. #DOQUEST\"Pirate Hats Ahoy!\"# " },
			[22] = { str = "22. #DOQUEST\"Stoley's Shipment\"# " },
			[23] = { str = "23. #DOQUEST\"Ship Schedules\"# (найдите его в одном из #NPCPirate's footlocker# в Lost Rigger Cove. Если предмет не находится — просто пропустите)" },
			[24] = { str = "24. #DOQUEST\"WANTED: Andre Firebeard\"#" },
			[25] = { str = "25. Когда всё готово, жмите Hearth в Gadgetzan." },
			[26] = { str = "26. Сдайте #TURNIN\"Water Pouch Bounty\"# и #TURNIN\"Wastewander Justice\"# и возьмите #ACCEPT\"More Wastewander Justice\"#" },
			[27] = { str = "27. Выполните #DOQUEST\"Gadgetzan Water Survey\"# (по пути гриндите мобов, координаты 38.29), затем вернитесь и сдайте его.", x = 38, y = 29, zone = "Tanaris" },
			[28] = { str = "28. Идите в Steamwheedle Port." },
			[29] = { str = "29. Сдайте там ВСЕ задания и возьмите #ACCEPT\"Deliver to MacKinley\"#" },
			[30] = { str = "30. Затем выполните: #DOQUEST\"More Wastewander Justice\"# вместе с #DOQUEST\"WANTED: Caliph Scorpidsting\"# (точка 59.37)", x = 59, y = 37, zone = "Tanaris" },
			[31] = { str = "31. Затем жмите Hearth в Gadgetzan. Обязательно сохраните (положите в банк) все Wastewander Water Pouches, какие у вас есть, — они понадобятся для позднего задания." },
			[32] = { str = "32. Сдайте #TURNIN\"More Wastewander Justice\"# и #TURNIN\"WANTED: Caliph Scorpidsting\"#" },
			[33] = { str = "33. Летите в Freewind Post." },
			[34] = { str = "34. Бегите на запад в Feralas..." },
			--[35] = { str = "." },
			--[36] = { str = "." },
		}
	},

-----------44-46 Feralas
	--[407] = {
	[4446] = {
		title = "44-46 Feralas",
		--n = "44-46 Feralas",
		--pID = 406, nID = 408,
		--itemCount = 51,
		items = {
			[1] = { str = "1. 44-46 Feralas" },
			[2] = { str = "2. Бегите в Camp Mojache (точка 75.44)", x = 75, y = 44, zone = "Feralas" },
			[3] = { str = "3. Возьмите там ВСЕ задания: #ACCEPT\"A New Cloak's Sheen\"#, #ACCEPT\"The Ogres of Feralas\"#, #ACCEPT\"Gordunni Cobalt\"#, #ACCEPT\"War on the Woodpaw\"#, #ACCEPT\"The Mark of Quality\"#, #ACCEPT\"A Strange Request\"#" },
			[4] = { str = "4. Откройте полетчика." },
			[5] = { str = "5. Сделайте Camp Mojache вашим домом." },
			[6] = { str = "6. Затем выполняйте в следующем порядке:" },
			[7] = { str = "7. #DOQUEST\"War on the Woodpaw\"# — делайте чуть севернее Camp Mojache (точка 71.37)", x = 71, y = 37, zone = "Feralas" },
			[8] = { str = "8. #DOQUEST\"The Ogres of Feralas\"# вместе с #DOQUEST\"Gordunni Cobalt\"# (точка 75.31)", x = 75, y = 31, zone = "Feralas" },
			[9] = { str = "9. Обязательно кликните по одному из свитков, лежащих на земле, — он начинает задание #ACCEPT\"The Gordunni Scroll\"#" },
			[10] = { str = "10. Затем выполните: #DOQUEST\"A New Cloak's Sheen\"# (точка 67.48)", x = 67, y = 48, zone = "Feralas" },
			[11] = { str = "11. Вернитесь в Camp Mojache, сдайте ВСЕ эти задания и возьмите все новые." },
			[12] = { str = "12. Выполните #DOQUEST\"Alpha Strike\"# (в точке 72.56), затем сдайте его и возьмите #ACCEPT\"Woodpaw Investigation\"#", x = 72, y = 56, zone = "Feralas" },
			[13] = { str = "13. Выполните #DOQUEST\"Woodpaw Investigation\"# (в точке 71.55) и сдайте его, возьмите #ACCEPT\"The Battle Plans\"#", x = 71, y = 55, zone = "Feralas" },
			[14] = { str = "14. Затем выполните #DOQUEST\"A Grim Discovery\"# (точка 66.46)", x = 66, y = 46, zone = "Feralas" },
			[15] = { str = "15. Жмите Hearth обратно в Camp Mojache, сдайте #TURNIN\"The Battle Plans\"# и #TURNIN\"A Grim Discovery\"# и возьмите ВСЕ новые задания." },
			[16] = { str = "16. ВАЖНО: если выпадет предмет 'OOX-22/FE Distress Beacon', возьмите задание #ACCEPT\"Find OOX-22/FE!\"#. Сдайте #TURNIN\"Find OOX-22/FE!\"# (в точке 53.55). Затем выполните:", x = 53, y = 55, zone = "Feralas" },
			[17] = { str = "17. #DOQUEST\"Stinglasher\"# вместе с #DOQUEST\"Zukk'ash Infestation\"# (точка 74.62)", x = 74, y = 62, zone = "Feralas" },
			[18] = { str = "18. #DOQUEST\"Screecher Spirits\"# (точка 55.56)", x = 55, y = 56, zone = "Feralas" },
			[19] = { str = "19. #DOQUEST\"The Ogres of Feralas\"# часть 2 (точка 59.68)", x = 59, y = 68, zone = "Feralas" },
			[20] = { str = "20. #VIDEONOTE:# Пока вы в этой зоне, обязательно подберите #NPCHippogryph Egg# на юго-западе (около 55.76) — позже он сдаётся в Tanaris для позднего #NPCquest#.", x = 53, y = 76, zone = "Feralas" },
			[21] = { str = "21. #DOQUEST\"Dark Ceremony\"# (точка 59.68)", x = 59, y = 68, zone = "Feralas" },
			[22] = { str = "22. #DOQUEST\"The Mark of Quality\"# (точка 53.55)", x = 53, y = 55, zone = "Feralas" },
			[23] = { str = "23. Бегите обратно в Camp Mojache, сдайте эти задания и возьмите все новые задания только у этих квестгиверов." },
			[24] = { str = "24. Затем сделайте следующее (если у вас есть 90+ золота — идите покупать маунта! К этому моменту он уже должен быть вам по карману...):" },
			[25] = { str = "25. Летите в Orgrimmar..." },
			[26] = { str = "26. Обязательно достаньте 120 Silk Cloth и 120 Mageweave из банка или почтового ящика. Для тех, кто не умеет считать: это по 6 стаков по 20 штук и Silk, и Mageweave." },
			[27] = { str = "27. Затем сдайте: #TURNIN\"Zukk'ash Report\"# (точка 56.46)", x = 56, y = 46, zone = "Orgrimmar" },
			[28] = { str = "28. Выполните #DOQUEST\"A Donation of Silk\"# и #DOQUEST\"A Donation of Mageweave\"# (в точке 63.51)", x = 63, y = 51, zone = "Orgrimmar" },
			[29] = { str = "29. Возьмите задание #ACCEPT\"Ripple Recovery\"# (у Dran Droffers) (точка 59.36)", x = 59, y = 36, zone = "Orgrimmar" },
			[30] = { str = "30. Затем сдайте #TURNIN\"Ripple Recovery\"# (НПС стоит рядом с Dran) и снова возьмите #ACCEPT\"Ripple Recovery\"#." },
			[31] = { str = "31. Сдайте #TURNIN\"Parts of the Swarm\"# и #TURNIN\"A Grim Discovery\"# у #NPCBelgrom Rockmaul# и возьмите #ACCEPT\"Betrayed\"# (точка 75.34). Заодно выучите новые способности, пока вы в Orgrimmar.", x = 75, y = 34, zone = "Orgrimmar" },
			[32] = { str = "32. Сдайте #TURNIN\"A Strange Request\"# и возьмите #ACCEPT\"Retrun to Witch Doctor Uzer'i\"# (Cleft of Shadow, точка 49.50)", x = 49, y = 50, zone = "Orgrimmar" },
			[33] = { str = "33. Сдайте #ACCEPT\"Report to Zor\"# и возьмите/выполните #DOQUEST\"Service to the Horde\"# (Valley of Wisdom, точка 38.38)", x = 38, y = 38, zone = "Orgrimmar" },
			[34] = { str = "34. Сдайте #TURNIN\"The Gordunni Orb\"# (Valley of Spirits, точка 39.86)", x = 39, y = 86, zone = "Orgrimmar" },
			[35] = { str = "35. Сдайте #TURNIN\"A Donation of Silk\"# и #TURNIN\"A Donation of Mageweave\"# (для фракции троллей, в точке 37.87)", x = 37, y = 87, zone = "Orgrimmar" },
			[36] = { str = "36. Теперь, прежде чем хиртиться обратно в Feralas, слетайте в Durotar и купите маунта!" },
			[37] = { str = "37. Сдайте #TURNIN\"Retrun to Witch Doctor Uzer'i\"# и возьмите #ACCEPT\"Natural Materials\"# и #ACCEPT\"Testing the Vessel\"#" },
			[38] = { str = "38. затем выполните #DOQUEST\"Natural Materials\"#" },
			[39] = { str = "39. гриндите гиппогрифов, пока задание не выполнится." },
			[40] = { str = "40. Если выпадет предмет \"#NPCOOX-22/FE Distress Beacon#\", возьмите задание #ACCEPT\"Find OOX-22/FE!\"#" },
			[41] = { str = "41. Сдайте #TURNIN\"Find OOX-22/FE!\"# (в точке 51.57)", x = 51, y = 57, zone = Ferelas },
			[42] = { str = "42. если у вас ещё нет 46 уровня, гриндите его на гиппогрифах.." },
			[43] = { str = "43. жмите Hearth обратно в Camp Mojache." },
			[44] = { str = "44. Сдайте #TURNIN\"Natural Materials\"# и возьмите #ACCEPT\"The Sunken Temple\"#" },
			[45] = { str = "45. Летите в Thunder Bluff" },
			[46] = { str = "46. Сдайте задание #TURNIN\"Deadmire\"#" },
			[47] = { str = "47. Выучите новые способности." },
			[48] = { str = "48. Летите в Crossroads, затем в Splintertree Post (Ashenvale)" },
			[49] = { str = "49. Затем идите на восток в Azshara..." },
			--[50] = { str = "." },
			--[51] = { str = "." },
		}
	},

-----------46-46 Azshara
	--[408] = {
	[4646] = {
		title = "46-46 Azshara",
		--n = "46-46 Azshara",
		--pID = 407, nID = 409,
		--itemCount = 16,
		items = {
			[1] = { str = "1. 46-46 Azshara" },
			[2] = { str = "2. Идите возьмите задания #DOQUEST\"Spiritual Unrest\"# и #DOQUEST\"A Land Filled with Hatred\"# (в точке 10.78)", x = 10, y = 78, zone = "Azshara" },
			[3] = { str = "3. Затем выполните их (в точках 17.66 и 20.62) и сдайте.", x = 17, y = 66, zone = "Azshara" },
			[4] = { str = "4. Затем идите в Valormok (точка 21.52)", x = 21, y = 52, zone = "Azshara" },
			[5] = { str = "5. Сдайте #TURNIN\"Betrayed\"# (следующую часть этого задания пока пропустите)" },
			[6] = { str = "6. Откройте там полетчика и летите в Orgrimmar." },
			[7] = { str = "7. Затем отправляйтесь в Undercity." },
			[8] = { str = "8. Идите в Magic Quarter и возьмите задание #ACCEPT\"Lines of Communication\"#" },
			[9] = { str = "9. Идите в Apothecarium Quarter и возьмите задания: #ACCEPT\"Seeping Corruption\"# и #ACCEPT\"Errand for Apothecary Zinge\"#" },
			[10] = { str = "10. Затем сдайте #ACCEPT\"Errand for Apothecary Zinge\"# (в соседней комнате)" },
			[11] = { str = "11. Вернитесь обратно и снова сдайте #TURNIN\"Errand for Apothecary Zinge\"# и возьмите #ACCEPT\"Into the Field\"#" },
			[12] = { str = "12. 'Field Testing Kit' и 'Box of Empty Vials' пока можно положить в банк." },
			[13] = { str = "13. Летите в Tarren Mill и сделайте его вашим домом." },
			[14] = { str = "14. Отправляйтесь в Hinterlands. Проход находится около точки 83.33", x = 83, y = 33, zone = "Hillsbard Foothills" },
			--[15] = { str = "." },
		}
	},

-----------46-47 Hinterlands
	--[409] = {
	[4647] = {
		title = "46-47 Hinterlands",
		--n = "46-47 Hinterlands",
		--pID = 408, nID = 410,
		--itemCount = 38,
		items = {
			[1] = { str = "1. 46-47 Hinterlands" },
			[2] = { str = "2. Сдайте #TURNIN\"Ripple Recovery\"# (в точке 27.49) и возьмите #ACCEPT\"A Sticky Situation\"#", x = 27, y = 49, zone = "Hinterlands" },
			[3] = { str = "3. Доезжайте до Revantusk Village (точка 77.80)", x = 77, y = 80, zone = "Hinterlands" },
			[4] = { str = "4. Возьмите задания: #ACCEPT\"Vilebranch Hooligans\"#, #ACCEPT\"Cannibalistic Cousins\"#, #ACCEPT\"Message to the Wildhammer\"#, #ACCEPT\"Stalking the Stalkers\"#, #ACCEPT\"Hunt the Savages\"# и #ACCEPT\"Avenging the Fallen\"#" },
			[5] = { str = "5. затем выполните следующее:" },
			[6] = { str = "6. #DOQUEST\"Whiskey Slim's Lost Grog\"# " },
			[7] = { str = "7. #DOQUEST\"Vilebranch Hooligans\"# " },
			[8] = { str = "8. #DOQUEST\"Cannibalistic Cousins\"# " },
			[9] = { str = "9. #DOQUEST\"A Sticky Situation\"# (сдайте позже), затем возьмите #ACCEPT\"Ripple Delivery\"#" },
			[10] = { str = "10. #DOQUEST\"Stalking the Stalkers\"# " },
			[11] = { str = "11. #DOQUEST\"Hunt the Savages\"# " },
			[12] = { str = "12. #DOQUEST\"Testing the Vessel\"# " },
			[13] = { str = "13. #DOQUEST\"Avenging the Fallen\"# " },
			[14] = { str = "14. #DOQUEST\"Lines of Communication\"# " },
			[15] = { str = "15. #DOQUEST\"Message to the Wildhammer\"# " },
			[16] = { str = "16. #DOQUEST\"Rin'ji is Trapped!\"# (эскорт-задание, начинается в точке 31.48)", x = 31, y = 48, zone = "Hinterlands" },
			[17] = { str = "17. #DOQUEST\"Grim Message\"# — пока делаете это задание, возьмите #ACCEPT\"Venom Bottles\"# (одна из маленьких бутылок на столе)" },
			[18] = { str = "18. Да-да, тот самый старый добрый гринд в Hinterlands.. развлекайтесь LOL." },
			[19] = { str = "19. Если выпадет предмет \"#NPCOOX-09/HL Distress Beacon#\", возьмите задание #ACCEPT\"Find OOX-09/HL!\"#" },
			[20] = { str = "20. Сдайте #TURNIN\"Find OOX-09/HL!\"# (в точке 49.38)", x = 49, y = 38, zone = "Hinterlands" },
			[21] = { str = "21. Сдайте #TURNIN\"Rin'ji is Trapped!\"# (в точке 86.59) и возьмите #ACCEPT\"Rin'ji's Secret\"#", x = 86, y = 59, zone = "Hinterlands" },
			[22] = { str = "22. Идите в Revantusk Village." },
			[23] = { str = "23. Сдайте ВСЕ задания." },
			[24] = { str = "24. Затем откройте полетчика и летите в TM (Tarren Mill)." },
			[25] = { str = "25. Сдайте #TURNIN\"Venom Bottles\"# и возьмите #ACCEPT\"Undamaged Venom Sac\"#" },
			[26] = { str = "26. Затем достаю весь mageweave из почтового ящика и лечу в Hammerfall..." },
			[27] = { str = "27. Затем идите к Doctor Gregory Victor прокачивать первую помощь..." },
			[28] = { str = "28. ...обычно я прокачиваю первую помощь до 290, чтобы делать Heavy Runecloth Bandage." },
			[29] = { str = "29. Затем летите обратно в TM." },
			[30] = { str = "30. затем езжайте обратно в Hinterlands (не летите)" },
			[31] = { str = "31. Выполните #DOQUEST\"Undamaged Venom Sac\"# и #DOQUEST\"The Atal'ai Exile\"# и возьмите #ACCEPT\"Return to Fel'Zerul\"#" },
			[32] = { str = "32. Затем жмите Hearth в Tarren Mill." },
			[33] = { str = "33. Сдайте #TURNIN\"Undamaged Venom Sac\"# и я ПРОПУСКАЮ #NPC\"Consult Master Gadrin\"#. Берите это задание, только если вы орк/тролль и вам ещё нужен маунт, — оно сдаётся в том же месте." },
			[34] = { str = "34. Летите в Undercity." },
			[35] = { str = "35. Идите в Magic Quarter и сдайте #TURNIN\"A Donation of Mageweave\"# (для этого задания нужно 60 mageweave cloth)" },
			[36] = { str = "36. затем сдайте: #TURNIN\"Lines of Communication\"# и #TURNIN\"Rin'ji's Secret\"#, затем выполните #TURNIN\"Oran's Gratitude\"#" },
			[37] = { str = "37. Садитесь на дирижабль до Grom'gol..." },
			--[38] = { str = "." },
			--[39] = { str = "." },
		}
	},

-----------47-47 Stranglethorn Vale
	--[410] = {
	[4747] = {
		title = "47-47 Stranglethorn Vale",
		--n = "47-47 Stranglethorn Vale",
		--pID = 409, nID = 411,
		--itemCount = 20,
		items = {
			[1] = { str = "1. 47-47 Stranglethorn Vale" },
			[2] = { str = "2. Выполните #DOQUEST\"Raptor Mastery\"# (убивайте #NPCTethis#) (точка 28.44) и сдайте его", x = 28, y = 44, zone = "Stranglethorn Vale" },
			[3] = { str = "3. Возьмите #ACCEPT\"Big Game Hunter\"# (элитное), выполните его и сдайте." },
			[4] = { str = "4. Идите в Grom'gol и сдайте #TURNIN\"Grim Message\"# (если делали раздел Hinterlands)." },
			[5] = { str = "5. Летите в BB." },
			[6] = { str = "6. Возьмите #ACCEPT\"The Bloodsail Buccaneers\"# часть 5 и #ACCEPT\"Whiskey Slim's Lost Grog\"#" },
			[7] = { str = "7. Сделайте BB вашим домом." },
			[8] = { str = "8. Возьмите #ACCEPT\"The Captain's Chest\"# (элитное) и выполните его (в точке 36.65). ПРИМЕЧАНИЕ: это задание тяжело солоить; соло оно проходимо, но лучше найти группу, чтобы убить Gorlash. Лично я пропускаю его, когда гоню до 60.", x = 36, y = 65, zone = "Stranglethorn Vale" },
			[9] = { str = "9. Сдайте #TURNIN\"Back to Booty Bay\"# и #TURNIN\"Deliver to MacKinley\"#" },
			[10] = { str = "10. Убедитесь, что задание #DOQUEST\"The Captain's Chest\"# взято, затем выполните его (в точке 36.65). Если вашему классу тяжело — найдите группу или просто пропустите его.", x = 36, y = 65, zone = "Stranglethorn Vale" },
			[11] = { str = "11. Ищите маленькую бутылку на берегу к востоку от BB, пока не выпадет предмет #NPCCarefully Folded Note# — он начинает задание #ACCEPT\"Message in a Bottle\"#" },
			[12] = { str = "12. Сдайте #TURNIN\"Message in a Bottle\"# (в точке 38.80)", x = 38, y = 80, zone = "Stranglethorn Vale" },
			[13] = { str = "13. Затем выполните #DOQUEST\"The Bloodsail Buccaneers\"# часть 5 (убейте трёх пиратов на трёх кораблях) и пока делаете это, найдите #ACCEPT\"Cortello's Riddle\"# (обычно это маленький свиток внизу среднего корабля)" },
			[14] = { str = "14. Затем жмите Hearth обратно в BB; если камень ещё на кулдауне — умрите специально." },
			[15] = { str = "15. Сдайте #TURNIN\"The Captain's Chest\"# и #TURNIN\"The Bloodsail Buccaneers\"# часть 5" },
			[16] = { str = "16. Летите в Kargath (Badlands).." },
			[17] = { str = "17. Достаю стак Silk Cloth из почтового ящика для задания #ACCEPT\"Caught\"#, затем..." },
			[18] = { str = "18. Идите в Searing Gorge..." },
			--[19] = { str = "." },
			--[20] = { str = "." },
		}
	},

-----------47-48 Searing Gorge
	--[411] = {
	[4748] = {
		title = "47-48 Searing Gorge",
		--n = "47-48 Searing Gorge",
		--pID = 410, nID = 412,
		--itemCount = 26,
		items = {
			[1] = { str = "1. 47-48 Searing Gorge" },
			[2] = { str = "2. Первым делом я иду на юго-восток и выполняю #DOQUEST\"Caught!\"# (парень в уборной, 65.62), затем сдаю его. ... беру #ACCEPT\"Ledger from Tanaris\"# ... щёлкаю по уборной, чтобы получить #NPCGoodsteel Ledger#", x = 65, y = 62, zone = "Searing Gorge" },
			[3] = { str = "3. Затем я начинаю убивать Glassweb Spiders для задания #DOQUEST\"Ledger from Tanaris\"#." },
			[4] = { str = "4. Затем иду на северо-запад, говорю с #NPCKalaran Windblade# (в точке 39.38) по пути к Thorium Point (35.25). Сначала выполняю его задание «выслушай меня» #DOQUEST\"Divine Retribution\"#. Чтобы получить #ACCEPT\"The Flawless Flame\"#. Оказавшись в Thorium Point, соберите ВСЕ задания там и откройте полетчика.", x = 35, y = 25, zone = "Searing Gorge" },
			[5] = { str = "5. Затем выполните следующее (шаги 5-13 в любом порядке):" },
			[6] = { str = "6. #DOQUEST\"Fiery Menace!\"# " },
			[7] = { str = "7. #DOQUEST\"Curse These Fat Fingers\"# " },
			[8] = { str = "8. #DOQUEST\"STOLEN: Smithing Tuyere and Lookout's Spyglass\"# " },
			[9] = { str = "9. #DOQUEST\"The Flawless Flame\"# сдайте, затем возьмите и выполните #DOQUEST\"Forging the Shaft\"# " },
			[10] = { str = "10. #DOQUEST\"JOB OPPORTUNITY: Culling the Competition\"# " },
			[11] = { str = "11. #DOQUEST\"WANTED: Overseer Maltorius\"# (элитное) (выполняйте это задание только в группе, даже 60 уровень с трудом проходит его соло)." },
			[12] = { str = "12. #DOQUEST\"What the Flux?\"# (планы для задания #DOQUEST\"What the Flux?\"# лежат прямо за Overseer Maltorius)" },
			[13] = { str = "13. #DOQUEST\"Incendosaurs? Whateverosaur is More Like It\"# " },
			[14] = { str = "14. #DOQUEST\"The Key to Freedom\"# начинается с выпавшего предмета #NPCGrimsite Outhouse Key#, сдайте в уборной (юго-восток, 65.62)", x = 65, y = 62, zone = "Searing Gorge" },
			[15] = { str = "15. Сдайте #TURNIN\"Forging the Shaft\"# ... возьмите #ACCEPT\"The Flame's Casing\"# " },
			[16] = { str = "16. Выполните #DOQUEST\"The Flame's Casing\"# (около 24.36). Просто убивайте мобов там, пока не выпадет предмет.", x = 24, y = 36, zone = "Searing Gorge" },
			[17] = { str = "17. Затем сдайте #TURNIN\"The Flame's Casing\"# ... возьмите и выполните #DOQUEST\"The Torch of Retribution\"#, затем сдайте его ... возьмите и выполните #DOQUEST\"The Torch of Retribution\"# часть 2 (просто подберите факел с земли)." },
			[18] = { str = "18. Возьмите #ACCEPT\"Squire Maltrake\"#, затем сдайте его ... возьмите #ACCEPT\"Set Them Ablaze!\"# " },
			[19] = { str = "19. Выполните #DOQUEST\"Set Them Ablaze!\"# (север=33.54, юг=44.61, восток=50.54, запад=35.60). Как только это будет сделано, возвращайтесь и сдайте его.", x = 33, y = 54, zone = "Searing Gorge" },
			[20] = { str = "20. Щёлкните по маленькому сундуку на земле (в точке 38.38) и возьмите #ACCEPT\"Trinkets...\"#, затем щёлкните по сундуку снова, чтобы сдать его.", x = 38, y = 38, zone = "Searing Gorge" },
			[21] = { str = "21. Обязательно сохраните #NPCBlack Dragonflight Molt# в инвентаре, он понадобится для позднего #NPCquest#." },
			[22] = { str = "22. Как только всё это будет сделано, сдайте все задания Searing Gorge. Убедитесь, что у вас есть все 20 solid crystal leg shafts." },
			[23] = { str = "23. Направляйтесь на юг в Burning Steppes (вам придётся идти через Black Rock Mountains).." },
			[24] = { str = "24. Я открываю некоторые области, затем беру там полетчика (в точке 65.25) и лечу напрямую в Stonard (Swamp of Sorrows)...", x = 65, y = 25, zone = "Searing Gorge" },
			--[25] = { str = "." },
			--[26] = { str = "." },
		}
	},

-----------48-48 Swamp of Sorrows
	--[412] = {
	[4848] = {
		title = "48-48 Swamp of Sorrows",
		--n = "48-48 Swamp of Sorrows",
		--pID = 411, nID = 413,
		--itemCount = 29,
		items = {
			[1] = { str = "1. 48-48 Swamp of Sorrows" },
			[2] = { str = "2. НЕ делайте Stonard вашим домом. (домом всё ещё должен оставаться Booty Bay)" },
			[3] = { str = "3. Идите к #NPCFallen Hero of the Horde# (34.66) ... говорите с ним, пока не получите это задание: #ACCEPT\"The Disgraced One\"# ", x = 34, y = 66, zone = "Searing Gorge" },
			[4] = { str = "4. Затем выполните #DOQUEST\"Cortello's Riddle\"# (22.48 под мостом)", x = 22, y = 48, zone = "Searing Gorge" },
			[5] = { str = "5 Возьмите #ACCEPT\"Cortello's Riddle\"# часть 2" },
			[6] = { str = "6. Идите обратно в Stonard." },
			[7] = { str = "7. Сдайте #TURNIN\"The Disgraced One\"# (и #TURNIN\"Return to Fel'Zerul\"#, если делали Hinterlands)... возьмите #ACCEPT\"The Missing Orders\"# " },
			[8] = { str = "8. #HUNTER Получите новые заклинания/способности охотника#" },
			[9] = { str = "9. Сдайте #TURNIN\"The Missing Orders\"# (в таверне) ... возьмите #ACCEPT\"The Swamp Talker\"# " },
			[10] = { str = "10. Выполните #DOQUEST\"The Swamp Talker\"# (в пещере в точке 65.78)", x = 65, y = 78, zone = "Searing Gorge" },
			[11] = { str = "11. Затем направляйтесь на северо-восток и.." },
			[12] = { str = "12. Идите убивать моба #NPCJarquia# (около 94.50 или 92.65), с него падает #NPCGoodsteel's Balanced Flameberge#... для задания #DOQUEST\"Ledger from Tanaris\"# ", x = 94, y = 50, zone = "Searing Gorge" },
			[13] = { str = "13. Затем умрите специально, чтобы оказаться в Stonard." },
			[14] = { str = "14. Идите к #NPCFallen Hero of the Horde# (34.66) и сдайте #TURNIN\"The Swamp Talker\"# ", x = 34, y = 66, zone = "Searing Gorge" },
			[15] = { str = "15. Возьмите и выполните #DOQUEST\"A Tale of Sorrow\"# (просто поговорите с ним)" },
			[16] = { str = "16. Жмите Hearth в Booty Bay." },
			[17] = { str = "17. Садитесь на корабль до Ratchet." },
			[18] = { str = "18. Летите в Brackenwall Village (Dustwallow Marsh). Оказавшись там, возьмите #ACCEPT\"The Brood of Onyxia\"# " },
			[19] = { str = "19. Затем направляйтесь на юг и заберите #NPCOverdue Package# для задания #DOQUEST\"Ledger from Tanaris\"# (в точке 54.55)", x = 54, y = 55, zone = "Dustwallow Marsh" },
			[20] = { str = "20. Спуститесь немного и выполните #DOQUEST\"The Brood of Onyxia\"# (яйца можно найти в точках 53.72 и 48.75)", x = 53, y = 72, zone = "Dustwallow Marsh" },
			[21] = { str = "21. Затем направляйтесь на запад к пещере Bloodfen Burrow (32.67) и выполните #DOQUEST\"Cortello's Riddle\"# ... возьмите следующую часть." , x = 32, y = 67, zone = "Dustwallow Marsh" },
			[22] = { str = "22. Затем умрите специально, чтобы оказаться обратно в Brackenwall Village." },
			[23] = { str = "23. Сдайте #TURNIN\"The Brood of Onyxia\"# ... возьмите #ACCEPT\"Challenge Overlord Mok'Morokk\"# (??? TBC Quest)" },
			[24] = { str = "24. Выполните #DOQUEST\"Challenge Overlord Mok'Morokk\"#, затем сдайте его. (??? TBC Quest)" },
			[25] = { str = "25. Затем летите в Tanaris.." },
			[26] = { str = "26. Сдайте #TURNIN\"Ledger from Tanaris\"# и #TURNIN\"Into the Field\"# ... возьмите и выполните #DOQUEST\"Slake that Thirst\"#" },
			[27] = { str = "27. Затем летите в Feralas.." },
			--[28] = { str = "." },
			--[29] = { str = "." },
		}
	},

--------48-49 Feralas
	--[413] = {
	[4849] = {
		title = "48-49 Ferelas",
		--n = "48-49 Feralas",
		--pID = 412, nID = 414,
		--itemCount = 27,
		items = {
			[1] = { str = "1. 48-49 Feralas" },
			[2] = { str = "2. сдайте #TURNIN\"Testing the Vessel\"# ... возьмите #ACCEPT\"Hippogryph Muisek\"# " },
			[3] = { str = "3. возьмите: #ACCEPT\"Improved Quality\"#, #ACCEPT\"Vengeance on the Northspring\"# и #ACCEPT\"Dark Heart\"# (элитное)" },
			[4] = { str = "4. сделайте его вашим домом." },
			[5] = { str = "5. идите выполнять #DOQUEST\"Hippogryph Muisek\"# " },
			[6] = { str = "6. затем жмите Hearth обратно в Camp Mojache." },
			[7] = { str = "7. сдайте #TURNIN\"Hippogryph Muisek\"# ... возьмите #ACCEPT\"Faerie Dragon Muisek\"# " },
			[8] = { str = "8. идите выполнять #DOQUEST\"Faerie Dragon Muisek\"# .. затем сдайте его ... возьмите #ACCEPT\"Treant Muisek\"# " },
			[9] = { str = "9. идите выполнять #DOQUEST\"Treant Muisek\"# .. затем сдайте его ... возьмите #ACCEPT\"Mountain Giant Muisek\"# (элитное)" },
			[10] = { str = "10. Отправьте пета в стойло." },
			[11] = { str = "11. идите возьмите #ACCEPT\"Zapped Giants\"# (в точке 44.44)" },
			[12] = { str = "12. идите приручите Ironfur Patriarch (для Claw Rank7)" },
			[13] = { str = "13. затем с этим петом выполните следующие задания:" },
			[14] = { str = "14. #DOQUEST\"Improved Quality\"# " },
			[15] = { str = "15. #DOQUEST\"Perfect Yeti Hide\"# (вы должны найти этот предмет/задание, пока выполняете задание: #NPC\"Improved Quality\"#)" },
			[16] = { str = "16. #DOQUEST\"Vengeance on the Northspring\"# " },
			[17] = { str = "17. #DOQUEST\"Dark Heart\"# (элитное)" },
			[18] = { str = "18. #DOQUEST\"Mountain Giant Muisek\"# (элитное) вместе с #DOQUEST\"Zapped Giants\"#" },
			[19] = { str = "19. как только эти задания выполнены и #TURNIN\"Zapped Giants\"# сдано..." },
			[20] = { str = "20. ..жмите Hearth в Camp Mojache." },
			[21] = { str = "21. бросьте медведя, верните кота." },
			[22] = { str = "22. Сдайте #TURNIN\"Mountain Giant Muisek\"# (элитное) ... возьмите #ACCEPT\"Weapons of Spirit\"# ... затем сдайте его, завершите." },
			[23] = { str = "23. Сдайте #TURNIN\"Improved Quality\"#, #TURNIN\"Perfect Yeti Hide\"#, #TURNIN\"Vengeance on the Northspring\"# и #TURNIN\"Dark Heart\"# " },
			[24] = { str = "24. Возьмите #ACCEPT\"The Strength of Corruption\"# " },
			[25] = { str = "25. Летите в Tanaris..." },
			--[26] = { str = "." },
			--[27] = { str = "." },
		}
	},

-----------49-50 Tanaris
	--[414] = {
	[4950] = {
		title = "49-50 Tanaris",
		--n = "49-50 Tanaris",
		--pID = 413, nID = 501,
		--itemCount = 33,
		items = {
			[1] = { str = "1. 49-50 Tanaris" },
			[2] = { str = "2. Идите к машине Egg-O-Matic в Gadgetzan и сдайте #NPCHippogryph Egg# для задания #DOQUEST\"The Super Egg-O-Matic\"#." },
			[3] = { str = "3. Сделайте Gadgetzan вашим домом." },
			[4] = { str = "4. Возьмите: #ACCEPT\"The Thirsty Goblin\"# #ACCEPT\"Noxious Lair Investigation\"# #ACCEPT\"Super Sticky\"# #ACCEPT\"Thistleshrub Valley\"# и #ACCEPT\"The Dunemaul Compound\"# " },
			[5] = { str = "5. Идите сдайте #TURNIN\"The Sunken Temple\"# (в точке 52.45) ... возьмите #ACCEPT\"The Stone Circle\"# и #ACCEPT\"Gahz'ridian\"# ", x = 52, y = 45, zone = "Tanaris" },
			[6] = { str = "6. Выполняйте в следующем порядке:" },
			[7] = { str = "7. #DOQUEST\"The Dunemaul Compound\"# вместе с #DOQUEST\"Gahz'ridian\"# (выполняется в точках 46.66 и 40.73, Gor'marok находится в пещере в точке 40.58)", x = 40, y = 58, zone = "Tanaris" },
			[8] = { str = "8. #DOQUEST\"Noxious Lair Investigation\"# (34.47)", x = 34, y = 47, zone = "Tanaris" },
			[9] = { str = "9. #DOQUEST\"Thistleshrub Valley\"# вместе с #DOQUEST\"The Thirsty Goblin\"# (28.65)", x = 28, y = 65, zone = "Tanaris" },
			[10] = { str = "10. #DOQUEST\"Tooga's Quest\"# (эскорт-задание с черепахой начинается в Thistleshrub Valley, ведите Tooga к Torta в точку 66.25).", x = 66, y = 25, zone = "Tanaris" },
			[11] = { str = "11. Затем сдайте #TURNIN\"Tooga's Quest\"# вместе с #TURNIN\"Screecher Spirits\"# " },
			[12] = { str = "12. Бегите в Gadgetzan." },
			[13] = { str = "13. Сдайте #TURNIN\"The Thirsty Goblin\"# ... возьмите #ACCEPT\"In Good Taste\"#, сдайте его ... возьмите #ACCEPT\"Sprinkle's Secret Ingredient\"# " },
			[14] = { str = "14. Сдайте #TURNIN\"Thistleshrub Valley\"# #TURNIN\"The Dunemaul Compound\"# и #TURNIN\"Noxious Lair Investigation\"# " },
			[15] = { str = "15. Возьмите #ACCEPT\"The Scrimshank Redemption\"# " },
			[16] = { str = "16. Не забудьте забрать свой Sampling Kit из банка и идите выполнять:" },
			[17] = { str = "17. #DOQUEST\"Tanaris Field Sampling\"# и сдайте #TURNIN\"Gahz'ridian\"# (в точке 52.45).", x = 52, y = 45, zone = "Tanaris" },
			[18] = { str = "18. #DOQUEST\"The Scrimshank Redemption\"# (в пещере в точке 53.70). Секрет нахождения предмета для этого задания — постоянно поворачивать направо в пещере, и это приведёт вас к нему. ", x = 53, y = 70, zone = "Tanaris" },
			[19] = { str = "19. Если выпадет предмет \"OOX-17/TN Distress Beacon\", возьмите задание #ACCEPT\"Find OOX-17/TN!\"# " },
			[20] = { str = "20. Сдайте #TURNIN\"Find OOX-17/TN!\"# (в точке 60.64)", x = 60, y = 64, zone = "Tanaris" },
			[21] = { str = "21. Затем выполните эскорт с курицей #DOQUEST\"Rescue OOX-17/TN!\"# " },
			[22] = { str = "22. Как только все эти задания будут выполнены.." },
			[23] = { str = "23. Жмите Hearth в Gadgetzan." },
			[24] = { str = "24. Сдайте #TURNIN\"Tanaris Fiels Sampling\"# ... возьмите #ACCEPT\"Return to Apothecary Zinge\"# " },
			[25] = { str = "25. Сдайте #TURNIN\"The Scrimshank Redemption\"# ... возьмите #ACCEPT\"Insect Part Analysis\"# " },
			[26] = { str = "26. Сдайте #TURNIN\"Insect Part Analysis\"# ... снова возьмите #ACCEPT\"Insect Part Analysis\"#." },
			[27] = { str = "27. Сдайте #TURNIN\"Insect Part Analysis\"# ... возьмите #ACCEPT\"Rise of the Silithid\"# " },
			[28] = { str = "28. Летите в Orgrimmar.." },
			[29] = { str = "29. Сделайте Orgrimmar вашим домом." },
			[30] = { str = "30. Достаньте Box of Empty Vials из банка." },
			[31] = { str = "31. Летите в Azshara..." },
			--[32] = { str = "." },
			--[33] = { str = "." },
		}
	},
}
