--[[--------------------------------------------------
003_Horde_50to60.lua
Авторы: mrmr
Версия: 1.04.2
------------------------------------------------------
Описание: Серия гайдов — 003 С 50 по 60 уровень
    1.04.1
        -- Первый выпуск
            Гайд для Орды
            с 50 по 60 уровень
    1.04.2
    	-- в этой ревизии изменений нет
	1.1.0
		-- Автор перевода и актуализации: Eynschteyn
------------------------------------------------------
Связь:
--]]--------------------------------------------------

Table_003_Horde_50to60 = {
-----------50-50 Azshara
	--[501] = {
	[5049] = {
		title = "50-50 Azshara",
		n = "50-50 Azshara",
		pID = 414, nID = 502,
		itemCount = 23,
		items = {
			[1] = { str = "1. 50-50 Azshara" },
			[2] = { str = "2. Возьмите: #ACCEPT\"Stealing Knowledge\"# " },
			[3] = { str = "3. Идите выполнять:" },
			[4] = { str = "4. #DOQUEST\"Stealing Knowledge\"# (выполняется в Ruins of Eldarath, 36.54)", x = 36, y = 54, zone = "Azshara" },
			[5] = { str = "5. #DOQUEST\"Seeping Corruption\"# (Tide Pools находятся в: 1=47.61, 2=47.51, 3=48.48, 4=47.46)", x = 47, y = 61, zone = "Azshara" },
			[6] = { str = "6. Как только они выполнены, сдайте #TURNIN\"Stealing Knowledge\"# .. возьмите ВСЕ 4 задания на доставку." },
			[7] = { str = "7. Сдайте #TURNIN\"Delivery to Archmage Xylem\"# (телепортёр находится в точке 28.50, #VIDEOSee Video#) ... возьмите #ACCEPT\"Xylem's Payment to Jediga\"# ", x = 28, y = 50, zone = "Azshara" },
			[8] = { str = "8. Затем летите в Thunder Bluff.." },
			[9] = { str = "9. Сдайте #TURNIN\"Delivery to Magatha\"# (на Elder Rise) ... возьмите #ACCEPT\"Magatha's Payment to Jediga\"# " },
			[10] = { str = "10. Жмите Hearth в Orgrimmar." },
			[11] = { str = "11. Идите сдайте #TURNIN\"Rise of the Silithid\"# ... возьмите #ACCEPT\"March of the Silithid\"# (в точке 56.46)", x = 56, y = 46, zone = "Azshara" },
			[12] = { str = "12. Сдайте #TURNIN\"Delivery to Jes'rimon\"# (в точке 55.34) ... возьмите #ACCEPT\"Jes'rimon's Payment to Jediga\"# и #ACCEPT\"Bone-Bladed Weapons\"# ", x = 55, y = 34, zone = "Azshara" },
			[13] = { str = "13. Затем сдайте #TURNIN\"Ripple Delivery\"# (в точке 59.36) (если вы делали раздел Hinterlands)", x = 59, y = 36, zone = "Azshara" },
			[14] = { str = "14. Затем я иду получать новые #HUNTERспособности охотника# ... #HUNTERвозьмите# #ACCEPT\"The Hunter's Charm\"# #HUNTER(если вы охотник).#" },
			[15] = { str = "15. Затем идите в The Undercity, направляйтесь в Apothecarium Quarter..." },
			[16] = { str = "16. Сдайте #TURNIN\"Delivery to Andron Gant\"# ... возьмите #ACCEPT\"Andron's Payment to Jediga\"# " },
			[17] = { str = "17. Затем сдайте #TURNIN\"Seeping Corruption\"# и #TURNIN\"Return to Apothecary Zinge\"# ... возьмите #ACCEPT\"Vivian Lagrave\"# пока вы там." },
			[18] = { str = "18. Затем возьмите #ACCEPT\"Seeping Corruption\"# ... затем сдайте его (у таурена прямо рядом с ним) ..." },
			[19] = { str = "19. ... Затем завершите #TURNIN\"Seeping Corruption\"# в последний раз." },
			[20] = { str = "20. Затем возьмите #ACCEPT\"A Sample of Slime...\"# и #ACCEPT\"... and a Batch of Ooze\"# " },
			[21] = { str = "21. Затем летите в Raventusj Village..." },
			--[22] = { str = "." },
			--[23] = { str = "." },
		}
	},

-----------50-50 Hinterlands
	--[502] = {
	[5050] = {
		title = "50-50 Hinterlands",
		--n = "50-50 Hinterlands",
		--pID = 501, nID = 503,
		--itemCount = 20,
		items = {
			[1] = { str = "1. 50-50 Hinterlands" },
			[2] = { str = "2. Возьмите: #ACCEPT\"Snapjaws, Mon!\"# #ACCEPT\"Gammerita, Mon!\"# (элитное) и #ACCEPT\"Lard Lost His Lunch\"# " },
			[3] = { str = "3. Выполняйте в следующем порядке:" },
			[4] = { str = "4. #DOQUEST\"Snapjaws, Mon!\"# вместе с #DOQUEST\"Gammerita, Mon!\"# и #DOQUEST\"Whiskey Slim's Lost Grog\"# " },
			[5] = { str = "5. #DOQUEST\"Cortello's Riddle\"# (в точке 80.46, маленький сундук в воде, сумка на 14 слотов вместе с 8800 XP)", x = 80, y = 46, zone = "The Hinterlands" },
			[6] = { str = "6. #DOQUEST\"Lard Lost His Lunch\"# (в точке 84.42)", x = 84, y = 42, zone = "The Hinterlands" },
			[7] = { str = "7. Затем идите сдайте #TURNIN\"Snapjaws, Mon!\"# #TURNIN\"Gammerita, Mon!\"# и #TURNIN\"Lard Lost His Lunch\"# " },
			[8] = { str = "8. затем идите выполнять #DOQUEST\"Sprinkle's Secret Ingredient\"# (в точке 41.60)", x = 41, y = 60, zone = "The Hinterlands" },
			[9] = { str = "9. затем жмите Hearth в Orgrimmar." },
			[10] = { str = "10. Летите в Azshara." },
			[11] = { str = "11. сдайте все 4 задания на доставку." },
			[12] = { str = "12. Летите в Crossroads." },
			[13] = { str = "13. сделайте Crossroads вашим домом." },
			[14] = { str = "14. Летите в Ratchet." },
			[15] = { str = "15. заберите \"#NPCStone Circle#\" в магазине Liv Rizzlefix ... также возьмите #ACCEPT\"Volcanic Activity\"# пока вы там." },
			[16] = { str = "16. садитесь на корабль до BB" },
			[17] = { str = "17. Летите в Stonard (Swamp of Sorrows).." },
			[18] = { str = "18. идите в Blasted Lands..." },
			--[19] = { str = "." },
			--[20] = { str = "." },
		}
	},

------------50-51 Blasted Lands
	--[503] = {
	[5051] = {
		title = "50-51 Blasted Lands",
		--n = "50-51 Blasted Lands",
		--pID = 502, nID = 504,
		--itemCount = 27,
		items = {
			[1] = { str = "1. 50-51 Blasted Lands" },
			[2] = { str = "2. Затем я нахожу все предметы для выполнения этих 5 заданий:" },
			[3] = { str = "3. #DOQUEST\"A Boar's Vitality\"# " },
			[4] = { str = "4. #DOQUEST\"Snickerfang Jowls\"# " },
			[5] = { str = "5. #DOQUEST\"The Basilisk's Bite\"# " },
			[6] = { str = "6. #DOQUEST\"The Decisive Striker\"# " },
			[7] = { str = "7. #DOQUEST\"Vulture's Vigor\"# " },
			[8] = { str = "8. вам нужно найти столько предметов для выполнения этих заданий:" },
			[9] = { str = "9. #NPCVulture Gizzards# x14" },
			[10] = { str = "10. #NPCBasilisk Brain# x11" },
			[11] = { str = "11. #NPCBlasted Boar Lungs# x6" },
			[12] = { str = "12. #NPCScorpok Pincers# x6" },
			[13] = { str = "13. #NPCSnickerfang Jowls# x5" },
			[14] = { str = "14. Пока я в Blasted Lands, я открываю почти все области для XP." },
			[15] = { str = "15. Если выпадет \"#NPCImperfect Draenethyst Fragment\", сдайте его для этого задания: #TURNIN\"Everything Counts In Large Amounts\"# " },
			[16] = { str = "16. ПРИМЕЧАНИЕ: я НИКОГДА не находил \"#NPCFlawless Draenethyst Sphere#\" для задания #TURNIN\"To Serve Kum'isha\"# ..удачи с этим." },
			[17] = { str = "17. Сдайте все задания." },
			[18] = { str = "18. Я сдаю #TURNIN\"The Decisive Striker\"# последним ради Ground Scorpok Assay (+50 к ловкости)" },
			[19] = { str = "19. затем жмите Hearth в Crossroads." },
			[20] = { str = "20. Летите в Tanaris (ПОЛУЧИТЕ MITHRIL CASING для позднего задания в Un'Goro!!!)" },
			[21] = { str = "21. сдайте #TURNIN\"Sprinkle's Secret Ingredient\"# ... возьмите #ACCEPT\"Delivery for Marin\"# " },
			[22] = { str = "22. сдайте #TURNIN\"March of the Silithid\"# ... возьмите #ACCEPT\"Bungle in the Jungle\"# " },
			[23] = { str = "23. сдайте #TURNIN\"Delivery for Marin\"# ...возьмите #ACCEPT\"Noggenfogger Elixir\"#, затем сдайте его." },
			[24] = { str = "24. идите сдайте #TURNIN\"The Stone Circle\"# (в точке 52.46 в Tanaris)", x = 52, y = 46, zone = "Tanaris" },
			[25] = { str = "25. затем идите в Un'Goro Crater..." },
			--[26] = { str = "." },
			--[27] = { str = "." },
		}
	},

-----------51-52 Un'Goro Crater
	--[504] = {
	[5152] = {
		title = "51-52 Un'Goro Crater",
		--n = "51-52 Un'Goro Crater",
		--pID = 503, nID = 505,
		--itemCount = 56,
		items = {
			[1] = { str = "1. 51-52 Un'Goro Crater" },
			[2] = { str = "2. Идите возьмите: #ACCEPT\"The Apes of Un'Goro\"# и #ACCEPT\"The Fare of Lar'korwi\"# (в точке 71.75)", x = 71, y = 75, zone = "Un'Goro Crater" },
			[3] = { str = "3. Идите выполнять #DOQUEST\"The Fare of Lar'korwi\"# (в точке 68.56)", x = 68, y = 56, zone = "Un'Goro Crater" },
			[4] = { str = "4. Затем начинайте выполнять: #DOQUEST\"Super Sticky\"# (на севере посередине), пока не выпадет предмет #NPCA Mangled Journal#" },
			[5] = { str = "5. Затем идите в Marshal's Refuge (43.10), возьмите ВСЕ задания там: #ACCEPT\"Chasing A-Me 01\"# #ACCEPT\"Shizzle's Flyer\"# #ACCEPT\"Lost!\"# #ACCEPT\"Beware of Pterrordax\"# #ACCEPT\"Roll the Bones\"# #ACCEPT\"Alien Ecology\"# #ACCEPT\"Expedition Salvation\"# #ACCEPT\"Larion and Muigin\"# ", x = 43, y = 10, zone = "Un'Goro Crater" },
			[6] = { str = "6. Сдайте #TURNIN\"Williden's Journal\"# " },
			[7] = { str = "7. Откройте там полетчика, затем идите на гринд в Un'Goro :)" },
			[8] = { str = "8. ПРИМЕЧАНИЕ: не беспокойтесь о кучах земли в Un'Goro, вы найдёте достаточно почвы из дропа с мобов. Также я не беспокоюсь о Bloodpetal Sprouts, так как за них не дают XP." },
			[9] = { str = "9. Пока выполняете задания, найдите по 7 кристаллов каждого цвета (красный, синий, зелёный и жёлтый для задания #DOQUEST\"Crystals of Power\"#)" },
			[10] = { str = "10. #DOQUEST\"Super Sticky\"# " },
			[11] = { str = "11. #DOQUEST\"The Apes of Un'Goro\"# вместе с #DOQUEST\"Chasing A-Me 01\"# (если у вас есть #NPCmithril casing#, выполните эскорт) (63.17)", x = 63, y = 17, zone = "Un'Goro Crater" },
			[12] = { str = "12. #DOQUEST\"Larion and Muigin\"# " },
			[13] = { str = "13. #DOQUEST\"Beware of Pterrordax\"# вместе с #DOQUEST\"Shizzle's Flyer\"# и.." },
			[14] = { str = "14. #DOQUEST\"Roll the Bones\"# " },
			[15] = { str = "15. #DOQUEST\"Expedition Salvation\"# (68.36 и 38.65)", x = 68, y = 36, zone = "Un'Goro Crater" },
			[16] = { str = "16. #DOQUEST\"... and a Batch of Ooze\"# (я собираю как минимум 30 образцов слизи)" },
			[17] = { str = "17. Идите сдайте #TURNIN\"The Apes of Un'Goro\"# ... возьмите #ACCEPT\"The Mighty U'cha\"# " },
			[18] = { str = "18. Сдайте #TURNIN\"The Fare of Lar'korwi\"# ... возьмите #ACCEPT\"The Scent of Lar'korwi\"# " },
			[19] = { str = "19. Затем идите выполнять:" },
			[20] = { str = "20. #DOQUEST\"Bone-Bladed Weapons\"# вместе с #DOQUEST\"The Scent of Lar'korwi\"# " },
			[21] = { str = "21. #ACCEPT\"It's a Secret to Everybody\"# ... щёлкните по лодке, затем по сумке под водой (в точке 63.68)", x = 63, y = 68, zone = "Un'Goro Crater" },
			[22] = { str = "22. Затем сдайте #TURNIN\"The Scent of Lar'korwi\"# ... возьмите #ACCEPT\"The Bait for Lar'korwi\"# (71.75)", x = 71, y = 75, zone = "Un'Goro Crater" },
			[23] = { str = "23. Затем идите выполнять #DOQUEST\"Alien Ecology\"# вместе с #DOQUEST\"Bungle in the Jungle\"# (50.80)", x = 50, y = 80, zone = "Un'Goro Crater" },
			[24] = { str = "24. Идите возьмите #ACCEPT\"Finding the Source\"# (в точке 30.50), затем выполните его вместе с #DOQUEST\"Volcanic Activity\"# ", x = 30, y = 50, zone = "Un'Goro Crater" },
			[25] = { str = "25. Путь к горячей точке для задания #DOQUEST\"Finding the Source\"# начинается с 51,42, а сама горячая точка находится в 50,46 (#VIDEOSee Video on where to find the hotspot#)", x = 51, y = 42, zone = "Un'Goro Crater" },
			[26] = { str = "26. #DOQUEST\"Lost!\"# Убедитесь, что все задания выполнены до этого (кроме \"#NPCThe Mighty U'cha\"# и \"#NPCThe Bait for Lar'korwi\"#), затем..." },
			[27] = { str = "27. ...Это ведёт обратно в Marshal's Refuge, сдайте там ВСЕ задания, возьмите новые (включая все задания на пилоны в пещере)." },
			[28] = { str = "28. Затем идите выполнять (в следующем порядке):" },
			[29] = { str = "29. #DOQUEST\"The Northern Pylon\"# (в точке 56.13)", x = 56, y = 13, zone = "Un'Goro Crater" },
			[30] = { str = "20. #DOQUEST\"The Mighty U'cha\"# (пещера в 63.13)", x = 63, y = 13, zone = "Un'Goro Crater" },
			[31] = { str = "31. #DOQUEST\"The Eastern Pylon\"# (в точке 77.50)", x = 77, y = 50, zone = "Un'Goro Crater" },
			[32] = { str = "32. #DOQUEST\"The Bait for Lar'korwi\"# (80.50). Затем сдайте его вместе с #TURNIN\"The Mighty U'cha\"# (71.75)", x = 71, y = 75, zone = "Un'Goro Crater" },
			[33] = { str = "33. Идите на запад, убивая слизней по пути.." },
			[34] = { str = "34. Сдайте #TURNIN\"Finding the Source\"# ... возьмите #ACCEPT\"The New Springs\"# (30.50)", x = 30, y = 50, zone = "Un'Goro Crater" },
			[35] = { str = "35. #DOQUEST\"The Western Pylon\"# (в точке 23.58)", x = 23, y = 58, zone = "Un'Goro Crater" },
			[36] = { str = "36. Идите обратно в Marshal's Refuge, убивая слизней по пути.." },
			[37] = { str = "37. Сдайте задания. Убедитесь, что выполнили #DOQUEST\"Making Sense of It\"# (просто поговорите с гномом в пещере)" },
			[38] = { str = "38. Летите в Tanaris." },
			[39] = { str = "39. Сдайте #TURNIN\"Super Sticky\"# и #TURNIN\"Bungle in the Jungle\"# ... я ПРОПУСКАЮ \"#NPCPawn Captures Queen\"# " },
			[40] = { str = "40. Затем летите в Thunder Bluff." },
			[41] = { str = "41. Идите на Elder Rise." },
			[42] = { str = "42. Возьмите #ACCEPT\"Un'goro Soil\"# .. затем сдайте его ... возьмите #ACCEPT\"Morrowgrain Research\"# .. затем сдайте его..." },
			[43] = { str = "43. ...но ПРОПУСТИТЕ следующую часть (ту, где нужно принести 10 Morrowgrain)" },
			[44] = { str = "44. Идите получать новые заклинания/способности." },
			[45] = { str = "45. Жмите Hearth в Crossroads." },
			[46] = { str = "46. Затем летите в Ratchet.." },
			[47] = { str = "47. Сдайте #TURNIN\"Volcanic Activity\"# и #TURNIN\"Marvon's Workshop\"# — я ПРОПУСКАЮ \"#NPCZapper Fuel\"# " },
			[48] = { str = "48. Садитесь на корабль до BB.." },
			[49] = { str = "49. Сдайте #TURNIN\"Whiskey Slim's Lost Grog\"# " },
			[50] = { str = "50. Также сдайте #TURNIN\"Rescue OOX-17/TN!\"# (если вы его делали)" },
			[51] = { str = "51. Летите в Kargath (Badlands).." },
			[52] = { str = "52. Сдайте #TURNIN\"Vivian Lagrave\"# " },
			[53] = { str = "53. Возьмите: #ACCEPT\"Dreadmaul Rock\"# и #ACCEPT\"The Rise of the Machines\"# " },
			[54] = { str = "54. Затем летите в Burning Steppes..." },
			--[55] = { str = "." },
			--[56] = { str = "." },
		}
	},

-----------52-53 Burning Steppes
	--[505] = {
	[5253] = {
		title = "52-53 Burning Steppes",
		--n = "52-53 Burning Steppes",
		--pID = 504, nID = 506,
		--itemCount = 18,
		items = {
			[1] = { str = "1. 52-53 Burning Steppes" },
			[2] = { str = "2. Возьмите: #ACCEPT\"Broodling Essence\"# и #ACCEPT\"Tablet of the Seven\"# " },
			[3] = { str = "3. Затем идите выполнять:" },
			[4] = { str = "4. #DOQUEST\"Broodling Essence\"# (на восток) (также убивайте как можно больше дракончиков, это \"мягкие\" мобы, которые умирают очень быстро)" },
			[5] = { str = "5. #DOQUEST\"Dreadmaul Rock\"# (79.45)... затем #DOQUEST\"Krom'Grul\"# (у Krom'Grul 2 разных точки появления, в любой из пещер)", x = 79, y = 45, zone = "Burning Steppes" },
			[6] = { str = "6. #DOQUEST\"The Rise of the Machines\"# " },
			[7] = { str = "7. #DOQUEST\"Tablet of the Seven\"# (находится в 54.40)", x = 54, y = 40, zone = "Burning Steppes" },
			[8] = { str = "8. Идите сдайте #TURNIN\"Tablet of the Seven\"# и #TURNIN\"Broodling Essence\"# ... возьмите #ACCEPT\"Felnok Steelspring\"# " },
			[9] = { str = "9. Затем летите в Kargath (Badlands)" },
			[10] = { str = "10. Сдайте #TURNIN\"Krom'Grul\"# " },
			[11] = { str = "11. Сдайте #TURNIN\"The Rise of the Machines\"# ... возьмите #ACCEPT\"The Rise of the Machines\"# часть 2" },
			[12] = { str = "12. Идите сдайте #TURNIN\"The Rise of the Machines\"# часть 2 (в точке 25.46 в Badlands)", x = 25, y = 46, zone = "Badlands" },
			[13] = { str = "13. Затем жмите Hearth в Crossroads." },
			[14] = { str = "14. Затем летите в Orgrimmar и сделайте его вашим домом." },
			[15] = { str = "15. Идите сдайте #TURNIN\"Bone-Bladed Weapons\"# (55.34)", x = 55, y = 34, zone = "Orgrimmar" },
			[16] = { str = "16. Летите в Azshara..." },
			--[17] = { str = "." },
			--[18] = { str = "." },
		}
	},

--------------53-54 Azshara
	--[506] = {
	[5354] = {
		title = "53-54 Azshara",
		--n = "53-54 Azshara",
		--pID = 505, nID = 507,
		--itemCount = 28,
		items = {
			[1] = { str = "1. 53-54 Azshara" },
			[2] = { str = "2. возьмите #ACCEPT\"Betrayed\"# " },
			[3] = { str = "3. идите сдайте #TURNIN\"The Hunter's Charm\"# (это задание только для охотника, в точке 41.42) ... возьмите #ACCEPT\"Courser Antlers\"# " },
			[4] = { str = "4. идите возьмите #ACCEPT\"Kim'jael Indeed!\"# (в точке 52.22 на вершине холма)", x = 52, y = 22, zone = "Azshara" },
			[5] = { str = "5. затем идите выполнять:" },
			[6] = { str = "6. #DOQUEST\"Courser Antlers\"# " },
			[7] = { str = "7. #DOQUEST\"Betrayed\"# " },
			[8] = { str = "8. #DOQUEST\"Kim'jael Indeed!\"# " },
			[9] = { str = "9. ПРИМЕЧАНИЕ: я некоторое время гринжу кровяных эльфов, выполняя эти 2 задания." },
			[10] = { str = "10. Как только эти 3 задания выполнены, идите сдайте #TURNIN\"Kim'jael Indeed!\"# ... возьмите #ACCEPT\"Kim'jael's \"Missing\" Equipment\"# " },
			[11] = { str = "11. сдайте #TURNIN\"Courser Antlers\"# ... возьмите #ACCEPT\"Wavethrashing\"# " },
			[12] = { str = "12. затем идите выполнять:" },
			[13] = { str = "13. #DOQUEST\"Kim'jael's \"Missing\" Equipment\"# " },
			[14] = { str = "14. #DOQUEST\"Wavethrashing\"# " },
			[15] = { str = "15. Как только оба выполнены, жмите Hearth в Orgrimmar." },
			[16] = { str = "16. затем летите в Azshara.." },
			[17] = { str = "17. сдайте #TURNIN\"Betrayed\"# ... возьмите #ACCEPT\"Betrayed\"# " },
			[18] = { str = "18. сдайте #TURNIN\"Wavethrashing\"# ... я ПРОПУСКАЮ #NPC\"The Green Drake\"# " },
			[19] = { str = "19. сдайте #TURNIN\"Kim'jael's \"Missing\" Equipment\"# " },
			[20] = { str = "20. В этот момент я обычно примерно на 3/4 пути к 54 уровню, я гринжу до 54 уровня на BloodElfs." },
			[21] = { str = "21. Я гринжу кровяных эльфов, потому что они \"мягкие\" мобы (мобы, у которых на 30% меньше здоровья/брони, чем у среднего моба этого уровня). Раньше я гринжил сатиров в предыдущих спидран-прохождениях, но с кровяными эльфами я смог срезать почти целый час." },
			[22] = { str = "22. ОПЦИОНАЛЬНО: вместо гринда вы можете пойти в подземелье BRD." },
			[23] = { str = "23. Как только я достигаю 54 (или несколько полосок после него), я жму Hearth в Orgrimmar." },
			[24] = { str = "24. Затем я иду сдавать #TURNIN\"Bone-Bladed Weapons\"# и #TURNIN\"Betrayed\"# " },
			[25] = { str = "25. затем летите в Splintertree Post (Ashenvale).." },
			[26] = { str = "26. затем идите в Felwood..." },
			--[27] = { str = "." },
			--[28] = { str = "." },
		}
	},

-----------54-54 Felwood
	--[507] = {
	[5454] = {
		title = "54-54 Felwood",
		--n = "54-54 Felwood",
		--pID = 506, nID = 508,
		--itemCount = 16,
		items = {
			[1] = { str = "1. 54-54 Felwood" },
			[2] = { str = "2. Возьмите #ACCEPT\"Timbermaw Ally\"# (в точке 50.85) (??? TBC Quest?) Просто поговорите с НПС там, он даст вам его.", x = 50, y = 85, zone = "Felwood" },
			[3] = { str = "3. Идите возьмите #ACCEPT\"Forces of Jaedenar\"# и #ACCEPT\"Verifying the Corruption\"# (в Emerald Sanctuary 51.82).", x = 51, y = 82, zone = "Felwood" },
			[4] = { str = "4. Идите возьмите #ACCEPT\"Cleansing Felwood\"# (в точке 46.84)", x = 46, y = 84, zone = "Felwood" },
			[5] = { str = "5. Я начинаю убивать слизней, я убиваю примерно 30/40 слизней здесь всего для задания #DOQUEST\"A Sample of Slime...\"# (40.68)", x = 40, y = 68, zone = "Felwood" },
			[6] = { str = "6. Затем идите завершать #DOQUEST\"Forces of Jaedenar\"# (38.60)", x = 38, y = 60, zone = "Felwood" },
			[7] = { str = "7. Затем идите в BloodVenom Post. (34.52)", x = 34, y = 52, zone = "Felwood" },
			[8] = { str = "8. Возьмите: #ACCEPT\"A Husband's Last Battle\"# и #ACCEPT\"Wild Guardians\"# " },
			[9] = { str = "9. Откройте там полетчика." },
			[10] = { str = "10. Затем выполняйте в следующем порядке:" },
			[11] = { str = "11. #DOQUEST\"Verifying the Corruption\"# (элитное) (41.41)", x = 41, y = 41, zone = "Felwood" },
			[12] = { str = "12. #DOQUEST\"Cleansing Felwood\"# (54.16)", x = 54, y = 16, zone = "Felwood" },
			[13] = { str = "13. Идите возьмите #ACCEPT\"Deadwood of the North\"# (в точке 64.8), но НЕ выполняйте его сейчас.", x = 64, y = 8, zone = "Felwood" },
			[14] = { str = "14. Гриндите свой путь через пещеру, чтобы попасть в Winterspring..." },
			--[15] = { str = "." },
			--[16] = { str = "." },
		}
	},

-----------54-55 Winterspring
	--[508] = {
	[5455] = {
		title = "54-55 Winterspring",
		--n = "54-55 Winterspring",
		--pID = 507, nID = 509,
		--itemCount = 31,
		items = {
			[1] = { str = "1. 54-55 Winterspring" },
			[2] = { str = "2. Выйдите из пещеры и возьмите #ACCEPT\"Winterfall Activity\"# прямо снаружи неё." },
			[3] = { str = "3. Идите к Donova Snowden (в точке 31.45)", x = 31, y = 45, zone = "Winterspring" },
			[4] = { str = "4. Сдайте #TURNIN\"The New Springs\"# и #TURNIN\"It's a Secret to Everybody\"# и возьмите #ACCEPT\"Strange Sources\"#" },
			[5] = { str = "5. ПРИМЕЧАНИЕ: я ПРОПУСКАЮ \"#NPCThe Videre Elixir\"# и остальную часть этой цепочки." },
			[6] = { str = "6. Идите в Everlook.. (61.38)", x = 61, y = 38, zone = "Winterspring" },
			[7] = { str = "7. Возьмите: #ACCEPT\"Are We There, Yeti?\"# #ACCEPT\"The Everlook Report\"# #ACCEPT\"Duke Nicholas Zverenhoff\"# #ACCEPT\"Sister Pamela\"# #ACCEPT\"Trouble in Winterspring\"# и #ACCEPT\"Ursius of the Shardtooth\"#" },
			[8] = { str = "8. Сдайте #TURNIN\"Felnok Steelspring\"# ... возьмите #ACCEPT\"Chillwind Horns\"# " },
			[9] = { str = "9. Сделайте Everlook вашим домом." },
			[10] = { str = "10. Идите выполнять #DOQUEST\"Ursius of the Shardtooth\"# (просто продолжайте гриндить мобов на холме к северу от Everlook, пока не появится #NPCUrsius#)" },
			[11] = { str = "11. Затем сдайте #TURNIN\"Ursius of the Shardtooth\"# ... возьмите #ACCEPT\"Brumeran of the Chillwind\"# " },
			[12] = { str = "12. Идите выполнять #DOQUEST\"Brumeran of the Chillwind\"# (он патрулирует около 60.60, смотрите карту для полного маршрута патруля)", x = 60, y = 60, zone = "Winterspring" },
			[13] = { str = "13. Затем идите открывать Darkwhisper Gorge (в точке 59.73) для задания #DOQUEST\"Strange Sources\"# ", x = 59, y = 73, zone = "Winterspring" },
			[14] = { str = "14. Затем жмите Hearth обратно в Everlook." },
			[15] = { str = "15. Сдайте #TURNIN\"Brumeran of the Chillwind\"# ... ПРОПУСКАЮ \"#NPCShy-Rotam\"# " },
			[16] = { str = "16. Затем идите выполнять следующие задания (шаги 17-20, в любом порядке) на западе и некоторые на севере. Когда будете на западе, не забудьте сдать #TURNIN\"Trouble in Winterspring\"# и взять #ACCEPT\"Threat of the Winterfall\"#:" },
			[17] = { str = "17. #DOQUEST\"Are We There, Yeti?\"# " },
			[18] = { str = "18. #DOQUEST\"Threat of the Winterfall\"# вы должны найти #NPCEmpty Firewater Flask#, который начинает #ACCEPT\"Winterfall Firewater\"# пока выполняете это задание. Когда выпадет предмет #NPC\"Winterfall Ritual Totem\"#, сохраните его и положите в банк, он понадобится позже." },
			[19] = { str = "19. #DOQUEST\"Wild Guardians\"# (Ragged Owls находятся к западу от Everlook, а Raging Owls — прямо к северу от Everlook)" },
			[20] = { str = "20. #DOQUEST\"Chillwind Horns\"# (большую концентрацию химер можно найти около 66.29)", x = 66, y = 29, zone = "Winterspring" },
			[21] = { str = "21. Как только #DOQUEST\"Threat of the Winterfall\"# и #DOQUEST\"Winterfall Firewater\"# выполнены, идите сдавать их вместе с #TURNIN\"Strange Sources\"# (в точке 31.45)... возьмите #ACCEPT\"Falling to Corruption\"# ", x = 31, y = 45, zone = "Winterspring" },
			[22] = { str = "22. Как только остальные из этих заданий выполнены, возвращайтесь в Everlook и сдайте #TURNIN\"Are We There, Yeti?\"# ...возьмите #ACCEPT\"Are We There, Yeti?\"# часть 2. Сдайте #TURNIN\"Chillwind Horns\"# ... я ПРОПУСКАЮ \"#NPCReturn to Tinkee\"# " },
			[23] = { str = "23. Затем идите выполнять:" },
			[24] = { str = "24. #DOQUEST\"Winterfall Activity\"# (67.37)", x = 67, y = 37, zone = "Winterspring" },
			[25] = { str = "25. #DOQUEST\"Are We There, Yeti?\"# (найдите 2 Pristine Yeti Horns) (66.43)", x = 66, y = 43, zone = "Winterspring" },
			[26] = { str = "26. Затем жмите Hearth в Everlook и возьмите #ACCEPT\"A Strange One \"#" },
			[27] = { str = "27. Идите сдайте #TURNIN\"Are We There, Yeti?\"# ... возьмите #ACCEPT\"Are We There, Yeti?\"# часть 3" },
			[28] = { str = "28. идите пугать Legacki механическим йети для задания #DOQUEST\"Are We There, Yeti?\"# часть 3" },
			[29] = { str = "29. Затем летите в Felwood..." },
			--[30] = { str = "." },
			--[31] = { str = "." },
		}
	},

-----------55-55 Felwood
	--[509] = {
	[5554] = {
		title = "55-55 Felwood",
		--n = "55-55 Felwood",
		--pID = 508, nID = 510,
		--itemCount = 31,
		items = {
			[1] = { str = "1. 55-55 Felwood" },
			[2] = { str = "2. Сдайте #TURNIN\"Wild Guardians\"# ... Возьмите #ACCEPT\"Wild Guardians\"# часть 2 и #ACCEPT\"Well of Corruption\"#" },
			[3] = { str = "3. Идите сдайте #TURNIN\"Cleansing Felwood\"# ... затем получите cenarion beacon для задания #DOQUEST\"Salve Via Hunting\"# (просто поговорите с НПС, чтобы получить его) (46.83)", x = 46, y = 83, zone = "Felwood" },
			[4] = { str = "4. Идите сдайте #TURNIN\"Verifying the Corruption\"# и #TURNIN\"Forces of Jaedenar\"# ... возьмите #ACCEPT\"Collection of the Corrupt Water\"# (51.82)", x = 51, y = 82, zone = "Felwood" },
			[5] = { str = "5. Идите выполнять в следующем порядке:" },
			[6] = { str = "6. Идите выполнять #DOQUEST\"A Husband's Last Battle\"# вместе с #DOQUEST\"Timbermaw Ally\"# (48.94)", x = 48, y = 94, zone = "Felwood" },
			[7] = { str = "7. Как только они выполнены, идите сдайте #TURNIN\"Timbermaw Ally\"# (в точке 50.85) ... возьмите #ACCEPT\"Speak to Nafien\"#", x = 50, y = 85, zone = "Winterspring" },
			[8] = { str = "8. Идите выполнять #DOQUEST\"Well of Corruption\"# (в точке 32.66). Также убедитесь, что собрали 6 #NPCCorrupted Soul Shards# для задания #DOQUEST\"Salve Via Hunting\"# ", x = 32, y = 66, zone = "Felwood" },
			[9] = { str = "9. #DOQUEST\"Collection of the Corrupt Water\"# (35.59)", x = 35, y = 59, zone = "Felwood" },
			[10] = { str = "10. Затем идите в Bloodvenom Post" },
			[11] = { str = "11. Сдайте #TURNIN\"A Husband's Last Battle\"# и #TURNIN\"Well of Corruption\"# ... возьмите #ACCEPT\"Corrupted Sabers\"# " },
			[12] = { str = "12. Идите сдайте #TURNIN\"Salve Via Hunting\"# (6 Corrupted Soul Shards) (46.83)", x = 46, y = 83, zone = "Felwood" },
			[13] = { str = "13. Идите сдайте #TURNIN\"Collection of the Corrupt Water\"# ... я ПРОПУСКАЮ \"#NPCSeeking Spiritual Aid\"# (51.82) ", x = 51, y = 82, zone = "Felwood" },
			[14] = { str = "14. Идите выполнять #DOQUEST\"Corrupted Sabers\"# (32.66), затем идите сдавать его. (ПРИМЕЧАНИЕ: когда сдаёте его, вы должны сначала поговорить с котом, когда доберётесь до НПС)", x = 32, y = 66, zone = "Felwood" },
			[15] = { str = "15. Затем идите на север и выполняйте:" },
			[16] = { str = "16. #DOQUEST\"Deadwood of the North\"# (61.9) Когда выпадет предмет \"Deadwood Ritual Totem\", сохраните его и положите в банк, когда будет возможность, он понадобится позже.", x = 61, y = 9, zone = "Felwood" },
			[17] = { str = "17. #DOQUEST\"Falling to Corruption\"# (котёл в 60.5) (подсказка: я использую пета, чтобы отвлекать мобов, пока выполняю это задание) ... затем возьмите #ACCEPT\"Mystery Goo\"# ", x = 60, y = 5, zone = "Felwood" },
			[18] = { str = "18. Идите сдайте #TURNIN\"Deadwood of the North\"# (64.8) ... возьмите #ACCEPT\"Speak to Salfa\"# . И сдайте #TURNIN\"Speak to Nafien\"# ", x = 64, y = 8, zone = "Felwood" },
			[19] = { str = "19. Затем бегите через пещеру (у вас должно быть Unfriendly с Timbermaw, так что они не должны атаковать вас).." },
			[20] = { str = "20. Сдайте #TURNIN\"Winterfall Activity\"# и #TURNIN\"Speak to Salfa\"# " },
			[21] = { str = "21. Затем идите сдайте #TURNIN\"Mystery Goo\"# (в точке 31.45 в Winterspring) ... ПРОПУСКАЮ \"#NPCToxic Horrors\"# ", x = 31, y = 45, zone = "Winterspring" },
			[22] = { str = "22. Затем жмите Hearth в Everlook." },
			[23] = { str = "23. Летите в Orgrimmar и сделайте его вашим домом." },
			[24] = { str = "24. Если вам случится увидеть #NPCWarcaller Gorlach#, возьмите #ACCEPT\"A Call To Arms: The Plaguelands!\"# " },
			[25] = { str = "25. Летите в Thunder Bluff, затем напрямую в Camp Mojache, Feralas" },
			[26] = { str = "26. Сдайте #TURNIN\"The Strength of Corruption\"# " },
			[27] = { str = "27. Затем летите в Tanaris..." },
			[28] = { str = "28. Идите пугать #NPCSprinkle# механическим йети для задания #DOQUEST\"Are We There, Yeti?\"# часть 3" },
			[29] = { str = "29. Затем летите в Silithus" },
			--[30] = { str = "." },
			--[31] = { str = "." },
		}
	},

------------55-55 Silithus
	--[510] = {
	[5555] = {
		title = "55-55 Silithus",
		--n = "55-55 Silithus",
		--pID = 509, nID = 511,
		--itemCount = 25,
		items = {
			[1] = { str = "1. 55-55 Silithus" },
			[2] = { str = "2. возьмите: #ACCEPT\"The Twilight Mystery\"# #ACCEPT\"Securing the Supply Lines\"# и #ACCEPT\"Deadly Desert Venom\"# " },
			[3] = { str = "3. идите выполнять: #DOQUEST\"Securing the Supply Lines\"# и #DOQUEST\"Deadly Desert Venom\"# (выполняйте эти 2 задания к северо-востоку от Cenarion Hold)" },
			[4] = { str = "4. затем сдайте их и возьмите новые задания." },
			[5] = { str = "5. затем идите выполнять:" },
			[6] = { str = "6. #DOQUEST\"Stepping Up Security\"# " },
			[7] = { str = "7. #DOQUEST\"The Twilight Mystery\"# " },
			[8] = { str = "8. #DOQUEST\"Noggle's Last Hope\"# " },
			[9] = { str = "9. Как только все три выполнены, идите сдавать их и берите новые." },
			[10] = { str = "10. идите выполнять:" },
			[11] = { str = "11. #DOQUEST\"Noggle's Lost Satchel\"# (находится около 40.90)", x = 40, y = 90, zone = "Silithus" },
			[12] = { str = "12. ПРИМЕЧАНИЕ: я пропускаю #NPC\"Wanted - Deathclasp, Terror of the Sands\"# (элитное), потому что его слишком сложно солоить на 55, но сделайте его, если найдёте группу." },
			[13] = { str = "13. #DOQUEST\"The Deserter\"# (он в пещере в 67.71) ... я ПРОПУСКАЮ #NPC\"The Twilight Lexicon\"# ", x = 67, y = 71, zone = "Silithus" },
			[14] = { str = "14. затем я специально умираю, чтобы оказаться в Cenarion Hold." },
			[15] = { str = "15. сдайте #TURNIN\"Noggle's Lost Satchel\"# " },
			[16] = { str = "16. затем идите в Marshal's Refuge в Un'Goro Crater." },
			[17] = { str = "17. идите пугать Quixxil механическим йети для задания #DOQUEST\"Are We There, Yeti?\"# часть 3" },
			[18] = { str = "18. затем жмите Hearth в Orgrimmar." },
			[19] = { str = "19. идите в Undercity." },
			[20] = { str = "20. идите завершать #TURNIN\"A Sample of Slime...\"# и #TURNIN\"... and a Batch of Ooze\"# " },
			[21] = { str = "21. идите возьмите #ACCEPT\"A Call To Arms: The Plaguelands!\"# " },
			[22] = { str = "22. сделайте Undercity вашим домом." },
			[23] = { str = "23. идите к The Bulwark... (это небольшая деревня к востоку от Tirisfal Glades)" },
			--[24] = { str = "." },
			--[25] = { str = "." },
		}
	},

-----------55-56 Western Plaguelands
	--[511] = {
	[5556] = {
		title = "55-56 Western Plaguelands",
		--n = "55-56 Western Plaguelands",
		--pID = 510, nID = 512,
		--itemCount = 24,
		items = {
			[1] = { str = "1. 55-56 Western Plaguelands" },
			[2] = { str = "2. Сдайте #TURNIN\"A Call To Arms: The Plaguelands!\"# возьмите #ACCEPT\"Scarlet Diversions\"# ..." },
			[3] = { str = "3. ... (убедитесь, что сначала получили Flame in a Bottle, прежде чем делать это задание, оно в коробке)" },
			[4] = { str = "4. Сдайте #TURNIN\"The Everlook Report\"# " },
			[5] = { str = "5. Возьмите и выполните #DOQUEST\"Argent Dawn Commission\"# " },
			[6] = { str = "6. Возьмите #ACCEPT\"A Plague Upon Thee\"# " },
			[7] = { str = "7. Идите в Western Plaguelands (Felstone field в 37.56) и...", x = 37, y = 56, zone = "Western Plaguelands" },
			[8] = { str = "8. Возьмите #ACCEPT\"Better Late Than Never\"# (леди в доме)" },
			[9] = { str = "9. Затем идите в амбар по соседству, и..." },
			[10] = { str = "10. Завершите #DOQUEST\"Better Late Than Never\"# .. щёлкните по сундуку снова, чтобы взять #ACCEPT\"Better Late Than Never\"# снова." },
			[11] = { str = "11. Идите выполнять #DOQUEST\"Scarlet Diversions\"# (сожгите палатку и установите знамя, 40.51) ", x = 40, y = 51, zone = "Western Plaguelands" },
			[12] = { str = "12. Идите обратно к The Bulwark.. (#VIDEONOTE:# Убедитесь, что сохраняете все #NPCBone Fragments#, которые найдёте, вам понадобится 30 штук для позднего #NPCquest#)" },
			[13] = { str = "13. Сдайте #TURNIN\"Scarlet Diversions\"# ... возьмите #ACCEPT\"All Along the Watchtowers\"# (элитное) и #ACCEPT\"The Scourge Cauldrons\"# " },
			[14] = { str = "14. Сдайте #TURNIN\"The Scourge Cauldrons\"# ... возьмите #ACCEPT\"Target: Felstone Field\"# " },
			[15] = { str = "15. Выполните всю цепочку заданий с котлами, вам нужно убить Cauldron Lord на каждом целевом поле (перечислены ниже), взять их ключ и использовать его у большого котла в центре поля. (Просто продолжайте ходить туда-сюда от The Bulwark к следующему полю, завершая каждое, сдавая их, а затем беря и выполняя следующее)..." },
			[16] = { str = "16. #DOQUEST\"Target: Felstone Field\"# (37.56)", x = 37, y = 56, zone = "Western Plaguelands" },
			[17] = { str = "17. #DOQUEST\"Target: Dalson's Tears\"# (46.52). #VIDEONOTE:# Пока вы здесь, тут есть небольшая цепочка заданий, которая начинается с маленького дневника в амбаре (47.50) под названием #TURNIN\"Mrs. Dalson's Diary\"#, просто щёлкните по нему, чтобы завершить задание. Теперь, после этого, вам нужно убить #NPCWandering Skeleton#, чтобы получить ключ, который открывает уборную за амбаром. После того как вы получите ключ и откроете уборную, оттуда выйдет #NPCFarmer Dalson#, 56 уровня нежить. Убейте его, заберите ключ, затем бегите в дом (прямо рядом с амбаром) и поднимитесь по лестнице, там вы найдёте шкаф, откройте шкаф этим ключом (для задания #DOQUEST\"Locked Away\"#) и наконец всё закончено. Лёгкие 10200 XP! Или нет?", x = 46, y = 52, zone = "Western Plaguelands" },
			[18] = { str = "18. #DOQUEST\"Target: Writhing Haunt\"# (53.65) (пока вы там, возьмите #ACCEPT\"The Wildlife Suffers Too\"# (в 53.64, почти мёртвый таурен в хижине)", x = 53, y = 65, zone = "Western Plaguelands" },
			[19] = { str = "19. #DOQUEST\"Target: Gahrron's Withering\"# (62.59)", x = 62, y = 59, zone = "Western Plaguelands" },
			[20] = { str = "20. Просто продолжайте ходить туда-сюда, завершая каждое." },
			[21] = { str = "21. Затем идите возьмите и выполните #DOQUEST\"Mission Accomplished!\"# " },
			[22] = { str = "22. Затем направляйтесь в Eastern Plaguelands..." },
			--[23] = { str = "." },
			--[24] = { str = "." },
		}
	},

-----------56-57 Eastern Plaguelands
	--[512] = {
	[5657] = {
		title = "56-57 Eastern Plaguelands",
		--n = "56-57 Eastern Plaguelands",
		--pID = 511, nID = 513,
		--itemCount = 38,
		items = {
			[1] = { str = "1. 56-57 Eastern Plaguelands" },
			[2] = { str = "2. Идите возьмите: #ACCEPT\"Demon Dogs\"# #ACCEPT\"Blood Tinged Skies\"# и #ACCEPT\"Carrion Grubbage\"# (в точке 7.43)", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[3] = { str = "3. Гриндите свой путь к (26.74) и возьмите: #ACCEPT\"To Kill With Purpose\"# и #ACCEPT\"Un-Life's Little Annoyances\"# . ПРИМЕЧАНИЕ: я ПРОПУСКАЮ \"#NPCThe Ranger Lord's Behest\"# ", x = 26, y = 74, zone = "Eastern Plaguelands" },
			[4] = { str = "4. Спуститесь в склеп в The Undercroft (27.85) и возьмите #ACCEPT\"Hameya's Plea\"# (свиток на земле). (??? TBC Quest?)", x = 27, y = 85, zone = "Eastern Plaguelands" },
			[5] = { str = "5. Гриндите свой путь к Darrowshire (36.90), выполняя эти задания:", x = 36, y = 90, zone = "Eastern Plaguelands" },
			[6] = { str = "6. #DOQUEST\"Demon Dogs\"# " },
			[7] = { str = "7. #DOQUEST\"Blood Tinged Skies\"# " },
			[8] = { str = "8. #DOQUEST\"Carrion Grubbage\"# " },
			[9] = { str = "9. Затем сдайте #TURNIN\"Sister Pamela\"# ... возьмите и выполните #ACCEPT\"Pamela's Doll\"# (у куклы 3 части)" },
			[10] = { str = "10. Сдайте #TURNIN\"Pamela's Doll\"# ... возьмите #ACCEPT\"Auntie Marlene\"# и #ACCEPT\"Uncle Carlin\"# " },
			[11] = { str = "11. Затем идите завершать #DOQUEST\"Blood Tinged Skies\"# " },
			[12] = { str = "12. Затем убедитесь, что убили 20 Plaguehound Runts для задания #DOQUEST\"Demon Dogs\"# " },
			[13] = { str = "13. Затем идите в Light's Hope Chapel (в точке 81.60)", x = 81, y = 60, zone = "Eastern Plaguelands" },
			[14] = { str = "14. Возьмите: #ACCEPT\"Zaeldarr the Outcast\"# и #ACCEPT\"The Restless Souls\"# " },
			[15] = { str = "15. Сдайте #TURNIN\"Duke Nicholas Zverenhoff\"# и #TURNIN\"Uncle Carlin\"# ... возьмите #ACCEPT\"Defenders of Darrowshire\"# " },
			[16] = { str = "16. Откройте там полетчика. Затем идите выполнять:" },
			[17] = { str = "17. #DOQUEST\"To Kill With Purpose\"# " },
			[18] = { str = "18. #DOQUEST\"Defenders of Darrowshire\"# " },
			[19] = { str = "19. #DOQUEST\"Hameya's Plea\"# (72.14) (??? TBC Quest?)", x = 72, y = 14, zone = "Eastern Plaguelands" },
			[20] = { str = "20. #DOQUEST\"Demon Dogs\"# " },
			[21] = { str = "21. #DOQUEST\"Carrion Grubbage\"# " },
			[22] = { str = "22. #DOQUEST\"Un-Life's Little Annoyances\"# " },
			[23] = { str = "23. #DOQUEST\"A Plague Upon Thee\"# (выполняется в Plaguewood на севере)" },
			[24] = { str = "24. #DOQUEST\"Augustus' Receipt Book\"# (возьмите это задание в хижине в 13.34, книга наверху в таверне в 15.33)", x = 15, y = 33, zone = "Eastern Plaguelands" },
			[25] = { str = "25. #DOQUEST\"The Restless Souls\"# (#NPCEgan# находится в хижине в 13.34) (следующая часть относится к Stratholme, которую я пропускаю)", x = 13, y = 34, zone = "Eastern Plaguelands" },
			[26] = { str = "26. Затем идите сдавать: #TURNIN\"Augustus' Receipt Book\"# " },
			[27] = { str = "27. Гриндите свой путь через пещеру (15.29) (осторожно, это непросто) ", x = 15, y = 29, zone = "Eastern Plaguelands" },
			[28] = { str = "28. #VIDEONOTE:# Если пещера слишком сложна для вас, другая лёгкая альтернатива — проехаться на грифоне с Plaguewood Tower (22.32) до Crown Guard tower (39.75), при условии, что Орда контролирует башни. Затем сдайте #TURNIN\"Demon Dogs\"# #TURNIN\"Blood Tinged Skies\"# и #TURNIN\"Carrion Grubbage\"# возьмите #ACCEPT\"Redemption\"# ... Просто поговорите с парнем, чтобы завершить его ... я ПРОПУСКАЮ \"#NPCOf Forgotten Memories\"# (можете попробовать, если найдёте группу)", x = 22, y = 32, zone = "Eastern Plaguelands" },
			[29] = { str = "29. Затем идите сдавать: #TURNIN\"To Kill With Purpose\"# и #TURNIN\"Un-Life's Little Annoyances\"# (в точке 26.74)", x = 26, y = 74, zone = "Eastern Plaguelands" },
			[30] = { str = "30. Затем идите выполнять #DOQUEST\"Zaeldarr the Outcast\"# (27.85)", x = 27, y = 85, zone = "Eastern Plaguelands" },
			[31] = { str = "31. Затем идите к куче земли за склепом и сдайте #TURNIN\"Hameya's Plea\"# (??? TBC Quest?)" },
			[32] = { str = "32. Затем сдайте: #TURNIN\"Zaeldarr the Outcast\"# и #TURNIN\"Defenders of Darrowshire\"# в Light's Hope Chapel" },
			[33] = { str = "33. Жмите Hearth в Undercity.." },
			[34] = { str = "34. Сдайте #TURNIN\"Better Late Than Never\"# ... возьмите #ACCEPT\"The Jeremiah Blues\"# " },
			[35] = { str = "35. Сдайте #TURNIN\"The Jeremiah Blues\"# (прямо под банком) ... возьмите #ACCEPT\"Good Luck Charm\"# " },
			[36] = { str = "36. Идите обратно к The Bulwark..." },
			--[37] = { str = "." },
			--[38] = { str = "." },
		}
	},

-----------57-58 Western Plaguelands
	--[513] = {
	[5758] = {
		title = "57-58 Western Plaguelands",
		--n = "57-58 Western Plaguelands",
		--pID = 512, nID = 514,
		--itemCount = 37,
		items = {
			[1] = { str = "1. 57-58 Western Plaguelands" },
			[2] = { str = "2. Сдайте #TURNIN\"A Plague Upon Thee\"# ... возьмите #ACCEPT\"A Plague Upon Thee\"# часть 2." },
			[3] = { str = "3. Идите сдайте #TURNIN\"Good Luck Charm\"# ...возьмите #ACCEPT\"Two Halves Become One\"# (леди в доме в 37.56)", x = 37, y = 56, zone = "Western Plaguelands" },
			[4] = { str = "4. Выполните #DOQUEST\"Two Halves Become One\"# (#NPCJabbering ghouls# в Felstone Field дропают нужный вам предмет, как только получите предмет, щёлкните по нему правой кнопкой в инвентаре), затем возвращайтесь к леди в доме, чтобы сдать его." },
			[5] = { str = "5. Затем выполните #DOQUEST\"A Plague Upon Thee\"# часть 2 ... возьмите #ACCEPT\"A Plague Upon Thee\"# часть 3 (всё это делается в 48.31) " },
			[6] = { str = "6. Затем идите возьмите #ACCEPT\"Unfinished Business\"# часть 1 (в 51.28), затем выполните его. (мобы для этого задания находятся в 50.42 и 53.44)", x = 51, y = 28, zone = "Western Plaguelands" },
			[7] = { str = "7. Сдайте #TURNIN\"Unfinished Business\"# часть 1 (обратно в 51.28) ... возьмите #ACCEPT\"Unfinished Business\"# часть 2, затем идите выполнять его. 2 моба для этого задания находятся в (57.37 и 54.24).", x = 55, y = 30, zone = "Western Plaguelands" },
			[8] = { str = "8. Сдайте #TURNIN\"Unfinished Business\"# часть 2 (обратно в 51.28) ... возьмите #ACCEPT\"Unfinished Business\"# часть 3, затем идите выполнять его. Нужно подняться в башню (в 45.19) в определённом месте, осторожно с элитными мобами.", x = 51, y = 28, zone = "Western Plaguelands" },
			[9] = { str = "9. Затем сдайте #TURNIN\"Unfinished Business\"# часть 3" },
			[10] = { str = "10. Затем идите завершать и сдавать #TURNIN\"The Wildlife Suffers Too\"# ... возьмите #ACCEPT\"The Wildlife Suffers Too\"# часть 2 (53.64)", x = 53, y = 64, zone = "Western Plaguelands" },
			[11] = { str = "11. Выполните #DOQUEST\"The Wildlife Suffers Too\"# часть 2, затем сдайте его ... возьмите #ACCEPT\"Glyphed Oaken Branch\"# " },
			[12] = { str = "12. Идите сдайте #TURNIN\"Auntie Marlene\"# (в доме в 49.78) ...возьмите #ACCEPT\"A Strange Historian\"# ", x = 49, y = 78, zone = "Western Plaguelands" },
			[13] = { str = "13. Идите взять кольцо для #DOQUEST\"A Strange Historian\"# (кольцо находится на кладбище)" },
			[14] = { str = "14. Идите в Andorhal.." },
			[15] = { str = "15. Выполните #DOQUEST\"All Along the Watchtowers\"# по пути к таверне (в 39.66)", x = 39, y = 66, zone = "Western Plaguelands" },
			[16] = { str = "16. Сдайте #TURNIN\"A Strange Historian\"# (у #NPCChromie# наверху в таверне в 39.68) ... возьмите #ACCEPT\"The Annals of Darrowshire\"# и #ACCEPT\"A Matter of Time\"# ", x = 39, y = 68, zone = "Western Plaguelands" },
			[17] = { str = "17. Затем идите выполнять (гринда мобов по пути):" },
			[18] = { str = "18. #DOQUEST\"All Along the Watchtowers\"# (элитное) " },
			[19] = { str = "19. #DOQUEST\"A Matter of Time\"# (47.62)", x = 47, y = 62, zone = "Western Plaguelands" },
			[20] = { str = "20. #DOQUEST\"The Annals of Darrowshire\"# книга для этого находится в здании в (42.67), сама книга Annals of Darrowshire выглядит иначе, чем остальные, у неё более светлый оттенок на верхней части страниц книги, в отличие от остальных, у которых более тёмный оттенок на верхней части страниц.", x = 42, y = 67, zone = "Western Plaguelands" },
			[21] = { str = "21. Идите сдайте #TURNIN\"A Matter of Time\"# и #TURNIN\"The Annals of Darrowshire\"# ... возьмите #ACCEPT\"Counting Out Time\"# и #ACCEPT\"Brother Carlin\"# " },
			[22] = { str = "22. Идите выполнять #DOQUEST\"Counting Out Time\"#, затем сдайте его. (он повторяемый, но XP дают только один раз)" },
			[23] = { str = "23. Затем я продолжаю гриндить мобов в Andorhal, пока не стану Friendly с Argent Dawn, чтобы иметь возможность покупать Enriched Manna Biscuits (которые быстрее восстанавливают ману при питье). Как только я достигаю friendly с AD, я иду обратно к The Bulwark.." },
			[24] = { str = "24. Сдайте #TURNIN\"A Plague Upon Thee\"# часть 3" },
			[25] = { str = "25. Сдайте #TURNIN\"All Along the Watchtowers\"# ... возьмите #ACCEPT\"Scholomance\"# " },
			[26] = { str = "26. Сдайте #TURNIN\"Scholomance\"# у нежити прямо рядом с ним ... возьмите #ACCEPT\"Skeletal Fragments\"# " },
			[27] = { str = "27. Запаситесь #NPCEnriched Manna Biscuits# (которые быстрее восстанавливают ману при питье)" },
			[28] = { str = "28. Затем я возвращаюсь в Andorhal и гринжу до 58 уровня, выполняя задание #DOQUEST\"Skeletal Fragments\"#." },
			[29] = { str = "29. Как только я достигаю 58 и #DOQUEST\"Skeletal Fragments\"# выполнено, а также у вас есть 30 #NPCBone Fragments# (обратите внимание: если вы далеки от 30 костяных фрагментов, можете просто пропустить это), возвращайтесь к The Bulwark и сдайте #TURNIN\"Skeletal Fragments\"# .. я ПРОПУСКАЮ \"#NPCMold Rhymes With...\"# " },
			[30] = { str = "30. Я сдаю все scourge stones, которые у меня есть." },
			[31] = { str = "31. Затем я запасаюсь #NPCEnriched Manna Biscuits# (около 600? :D)" },
			[32] = { str = "32. затем садитесь на дирижабль до Orgrimmar. (пока ждёте, делайте heavy runecloth bandages)" },
			[33] = { str = "33. Оказавшись в Orgrimmar, получаю новые заклинания/способности." },
			[34] = { str = "34. кладу 2/3 своих manna biscuits в банк." },
			[35] = { str = "35. затем летите в Winterspring..." },
			--[36] = { str = "." },
			--[37] = { str = "." },
		}
	},

------------58-60 Winterspring
	--[514] = {
	[5860] = {
		title = "58-60 Winterspring",
		--n = "58-60 Winterspring",
		--pID = 513, nID = 514,
		--itemCount = 32,
		items = {
			[1] = { str = "1. 58-60 Winterspring" },
			[2] = { str = "2. Первым делом я ставлю пета в стойло." },
			[3] = { str = "3. затем делаю Everlook своим домом." },
			[4] = { str = "4. сдаю #TURNIN\"Are We There, Yeti?\"# часть 3" },
			[5] = { str = "5. беру: #ACCEPT\"Luck Be With You\"# (элитное) и #ACCEPT\"Ursius of the Shardtooth\"# (элитное)" },
			[6] = { str = "05) затем иду приручать Winterspring Screecher (для Claw Rank8) (для этого идите на юг)" },
			[7] = { str = "06) затем использую этого пета для выполнения #DOQUEST\"Luck Be With You\"# (просто используйте пета, чтобы отвлекать великанов, пока собираете Frostmaul Shards)" },
			[8] = { str = "07) затем жмите Hearth в Everlook." },
			[9] = { str = "08) идите выполнять #DOQUEST\"Ursius of the Shardtooth\"# (элитное) (просто продолжайте гриндить мобов на холме к северу от Everlook, пока не появится Ursius)" },
			[10] = { str = "09) идите сдавать #TURNIN\"Luck Be With You\"# (если уже выполнено) и #TURNIN\"Ursius of the Shardtooth\"# ... возьмите #ACCEPT\"Brumeran of the Chillwind\"# (элитное)" },
			[11] = { str = "10) затем идите на юг и выполняйте:" },
			[12] = { str = "11) #DOQUEST\"Brumeran of the Chillwind\"# (элитное)" },
			[13] = { str = "12) #DOQUEST\"Luck Be With You\"# (элитное) (если всё ещё нужно его завершить)" },
			[14] = { str = "13) #DOQUEST\"Wild Guardians\"# часть 2 (я гринжу сов в Owl Wing Thicket несколько часов, перед тем как покинуть это место)" },
			[15] = { str = "14) затем, когда мне остаётся несколько полосок до 59, я иду обратно в Everlook (НЕ жмите Hearth).." },
			[16] = { str = "15) сдаю #TURNIN\"Luck Be With You\"# и #TURNIN\"Brumeran of the Chillwind\"# ... я ПРОПУСКАЮ #NPC\"Shy-Rotam\"# (элитное)" },
			[17] = { str = "16) Летите в Bloodvenom Post (Felwood).." },
			[18] = { str = "17) сдаю #TURNIN\"Wild Guardians\"# часть 2 ... беру #ACCEPT\"Wild Guardians\"# часть 3" },
			[19] = { str = "18) затем жмите Hearth обратно в Everlook." },
			[20] = { str = "19) Затем идите вниз в Owl Wing Thicket и выполняйте #DOQUEST\"Wild Guardians\"# часть 3" },
			[21] = { str = "20) Я продолжаю гриндить сов, пока не достигну примерно 59 с половиной, затем..." },
			[22] = { str = "21) Я специально умираю, чтобы оказаться в Everlook (не жмите Hearth)" },
			[23] = { str = "22) затем летите в Bloodvenom Post (Felwood).." },
			[24] = { str = "23) сдаю #TURNIN\"Wild Guardians\"# часть 3 и #TURNIN\"Guarding Secrets\"# ... беру #ACCEPT\"Guarding Secrets\"# часть 2" },
			[25] = { str = "24) Затем я лечу в Crossroads, затем в Thunderbluff, иду на Elder Rise.." },
			[26] = { str = "25) сдаю #TURNIN\"Guarding Secrets\"# часть 2 и #TURNIN\"Glyphed Oaken Branch\"# (оба у Nara Wildmane)" },
			[27] = { str = "26) Жмите Hearth обратно в Everlook." },
			[28] = { str = "27) В этот момент я обычно примерно на 3/4 пути к 60." },
			[29] = { str = "28) Затем я возвращаюсь в Owl Wing Thicket и гринжу до 60. (Смотрите End Game Credits)" },
			[30] = { str = "." },
			[31] = { str = "." },
			[32] = { str = "ПОЗДРАВЛЯЮ, теперь вы 60 уровень!"},
			[33] = { str = "." },
			--[34] = { str = "." },
		}
	},
}
