--[[--------------------------------------------------
003_Alliance_50to60.lua
Авторы: mrmr
Версия: 1.04.3
------------------------------------------------------
Описание: Серия гайдов — 003 С 50 по 60 уровень
    1.04.1
        -- Первый выпуск
            Гайд для Альянса
            с 50 по 60 уровень
    1.04.2
    	-- в этой ревизии изменений нет
	1.04.3
		-- Добавлены цветовые коды
			Исправлены различные орфографические ошибки
	1.05.0
        -- Добавлены шаги для охотника
        -- В этом разделе всё ещё нужно добавить нумерованные шаги в остальной части гайда, добавить кавычки к заданиям, добавить цвет COORDS к направлениям передвижения и проверить, не пропущен ли где-то цвет NPC
	1.1.0
		-- Автор перевода и актуализации: Eynschteyn
------------------------------------------------------
Связь:
--]]--------------------------------------------------

Table_003_Alliance_50to60 = {
-----------50-51 Searing Gorge
	--[501] = {
	[5051] = {
		title = "50-51 Searing Gorge",
		--n = "50-51 Searing Gorge",
		--pID = 413, nID = 502,
		--itemCount = 72,
		items = {
			[1] = { str = "1. 50-51 Searing Gorge" },
			[2] = { str = "2. Идите в точку 65,62 у туалета возьмите задание #ACCEPTCaught!#", x = 65, y = 62, zone = "Searing Gorge" },
			[3] = { str = "3. Спуститесь с горки и убивайте геологов для задания #DOQUESTCaught!#" },
			[4] = { str = "4. Уничтожте всех мобов и в яме возьмите задание #ACCEPTSuntara Stones pt.1#, сопроводите до точки 74,19 и когда он умрет возьмите записку и примите задание #ACCEPTSuntara Stones pt.2#", x = 74, y = 19, zone = "Searing Gorge" },
			[5] = { str = "5. Спуститесь снова от туалета в точку 65,62 и убейте последних геологов если они вам нужны и сдайте задание #TURNINCaught!#, возьмите задание #ACCEPTLedger From Tanaris# и возьмите книгу которую он подсунет вам под дверь", x = 65, y = 62, zone = "Searing Gorge" },
			[6] = { str = "6. Идите в точку 71,72 и убейте #NPCMargol the Rager# и заберите у него Margol's Horn который дает задание #ACCEPTThe Horn of the Beast# это даст вам ключ searing gorge key бесполезный сейчас, откройте полетчика в точке 38,30", x = 71, y = 72, zone = "Searing Gorge" },
			[7] = { str = "7. Идите в точку 39,38 возьмите задание #ACCEPTDivine Retribution# говорите с НПС пока не выполните задание потом возьмите следующее задание #ACCEPTThe Flawless Flame#", x = 39, y = 38, zone = "Searing Gorge" },
			[8] = { str = "8. Поднимитесь на верх в Thorium Point в точке 38,26", x = 38, y = 26, zone = "Searing Gorge" },
			[9] = { str = "9. Возьмите задания с таблички #ACCEPTWANTED: Overseer Maltorius#, (для этого потребуется группа) #ACCEPTSTOLEN: Smithing Tuyere and Lookout's Spyglass# и #ACCEPTJOB OPPORTUNITY: Culling the Competition#" },
			[10] = { str = "10. Возьмите задания #ACCEPTCurse These Fat Fingers#, #ACCEPTFiery Menace!#, #ACCEPTIncendosaurs? Whateverosaur is More Like It# около башни" },
			[11] = { str = "11. Под шатрром возьмите задание #ACCEPTWhat The Flux?#" },
			[12] = { str = "12. Откройте полетчика и летите в IF" },
			[13] = { str = "13. Идите в точку 71,16 и сдайте задание #TURNINSuntara Stones pt.2#, возьмите следующее #ACCEPTDwarven Justice#", x = 71, y = 16, zone = "Searing Gorge" },
			[14] = { str = "14. Летите в Thelsamar" },
			[15] = { str = "15. Идите в точку 18,83 и сдайте задание #TURNINThe Horn of the Beast#, возьмите следующее #ACCEPTProof of Deed#", x = 18, y = 83, zone = "Searing Gorge" },
			[16] = { str = "16. Жмите Hearth в IF" },
			[17] = { str = "17. Идите в точку 69,11 и сдайте задание #TURNINProof of Deed#, и возьмите следующее #ACCEPTAt Last!#", x = 69, y = 11, zone = "Searing Gorge" },
			[18] = { str = "18. Идите в точку 75,23 и возьмите задание #ACCEPTA Little Slime Goes A Long Way#", x = 75, y = 23, zone = "Searing Gorge" },
			[19] = { str = "19. Летите в Thelsamar и бегите в точку 18,83", x = 18, y = 83, zone = "Searing Gorge" },
			[20] = { str = "20. Сдайте задание #TURNINAt Last!# и прикрепите ключ к брелку. Легко получите 12 000 опыта" },
			[21] = { str = "21. Теперь самое интересное - выполнение всех этих заданий некоторые монстры находятся на обширной территории по этому я не буду указывать их координаты" },
			[22] = { str = "22. Спуститесь южнее и убивайте пауков glassweb spiders для задания #DOQUESTLedger From Tanaris#" },
			[23] = { str = "23. Убивайте всех големов которых видите для задания #DOQUESTThe Flawless Flame#" },
			[24] = { str = "24. Обойдите южную часть котла (яму) и вернитесь к TP затем выполните следующие действия:" },
			[25] = { str = "25. Убивайте heavy war golems и infernal elementals (кроме magma elementals для задания #DOQUESTThe Flawless Flame# и heavy war golems для задания #DOQUESTCurse These Fat Fingers#" },
			[26] = { str = "26. Бейте dark iron lookouts и steamsmiths (Их всего 6, так что если не упадет вернитесь если ничего не выпадет с них падает ключ от туалета) для задания #DOQUESTSTOLEN: Smithing Tuyere and Lookout's Spyglass#" },
			[27] = { str = "27. Сдайте задание #TURNINThe Flawless Flame# и возьмите задание #ACCEPTForging the Shaft# когда снова окажетесь рядом с TB (как я понял это туалет)." },
			[28] = { str = "28. Бейте greater lava spiders (не searing) для задания #DOQUESTFiery Menace!# на юго-западе" },
			[29] = { str = "29. Если вам выпал Grimesilt Outhouse Key используйте его и возьмите задание #ACCEPTThe Key to Freedom# и сдайте его в точке 65,62", x = 65, y = 62, zone = "Searing Gorge" },
			[30] = { str = "30. Идите в точку 63,38 и спуститесь в котлован", x = 63, y = 38, zone = "Searing Gorge" },
			[31] = { str = "31. Бейте dark iron taskmasters и slavers внутри пещеры если увидите их для задания #DOQUESTJOB OPPORTUNITY: Culling the Competition and Forging the Shaft#" },
			[32] = { str = "32. Вход в пещеру находится в точке 41,54", x = 41, y = 54, zone = "Searing Gorge" },
			[33] = { str = "33. Идите в пещеру по координатам 41,25 пройдите через дверь с решоткой и сдайте задание #TURNINDwarven Justice# и возьмите #ACCEPTRelease Them#", x = 41, y = 25, zone = "Searing Gorge" },
			[34] = { str = "34. Поднимитесь по пандусу и держитесь правее пока не дойдете до точки 40,35, убейте босса для задания #DOQUESTWANTED: Overseer Maltorius# и заюзайте чертежи для задания #DOQUESTWhat The Flux?# это задание можно сделать в 2ем но сложно", x = 40, y = 35, zone = "Searing Gorge" },
			[35] = { str = "35. Идите по танелю который ведет наружу и поворачивает снова внутрь пещеры идите туда и убивайте Incendosaur для задания #DOQUESTIncendosaurs? Whateverosaur is More Like It# Собивайте чащуйки они пригодятся позже" },
			[36] = { str = "36. Гриндите пока не останется до следующего уровня около 36 000 опыта" },
			[37] = { str = "37. Умрите специально и реснитесь на кладбоне идите сдайте выполненные задания" },
			[38] = { str = "38. Сдайте задание #TURNINWANTED: Overseer Maltorius#" },
			[39] = { str = "39. С права от башни поверните и сдайте #TURNINCurse These Fat Fingers#, #TURNINFiery Menace!# и #TURNINIncendosaurs? Whateverosaur is More Like It#" },
			[40] = { str = "40. Идите в палатку позади и сдайте #TURNINSTOLEN: Smithing Tuyere and Lookout's Spyglass# и #TURNINJOB OPPORTUNITY: Culling the Competition#" },
			[41] = { str = "41. Идите к следующей палатке и сдайте #TURNINWhat The Flux?#" },
			[42] = { str = "42. После того как выполните все задания, вы можете делать эти задания повторно получая немного опыта и репутицию у TB. Сохронять чашуйки нужно было для того что бы:" },
			[43] = { str = "43. Сейчас вам осталось совсем не много до 51 уровня, идите на юг от базы в точку 38,38", x = 38, y = 38, zone = "Searing Gorge" },
			[44] = { str = "44. Сдайте задание #TURNINForging the Shaft# и возьмите #ACCEPTThe Flame’s Casing#" },
			[45] = { str = "45. Сейчас у вас должно не хватать 1 или 2 клеток до 51 уровня" },
			[46] = { str = "46. Идите по тропе в гору в точку 24,32", x = 24, y = 32, zone = "Searing Gorge" },
			[47] = { str = "47. Убивайте элитных мобов по одному на пути к лавовой яме в точке 29,25, зачистите мобов вокруг нее, idolators не нападают если вы стоите на камне в центре. Запрыгивайте на камень используя маунта. Откройте и возьмите задание #ACCEPTRelease Them#", x = 29, y = 25, zone = "Searing Gorge" },
			[48] = { str = "47. Убивая этих мобов вокруг бассейна вы должны были найти символ рагнороса Symbol of Ragnaros для задания #DOQUESTThe Flame’s Casing# если нет убивайте пока не найдете его" },
			[49] = { str = "49. Поговорите с НПС в клетке он даст задание #ACCEPTPrayer to Elune pt.1# прослкшайте рассказ и сдайте задание, берите следующее #ACCEPTPrayer to Elune pt.2# сейчас нужно бить существ что бы получить Rag и Prayer of Elune, это легко получить" },
			[50] = { str = "50. Идите в точку 38,38 и сдайте #TURNINThe Flame’s Casing# и возьмите следующее #ACCEPTThe Torch of Retribution pt.1#, сдайте его обратно. Возьмите задание #ACCEPTThe Torch of Retribution pt.2# затем возьмите факел перед ним и завершите задание. Берите следующее #ACCEPTSquire Maltrake# сдайте его и берите следующее #ACCEPTSet Them Ablaze!#", x = 38, y = 38, zone = "Searing Gorge" },
			[51] = { str = "51. Наденьте посох вместо нормального оружия и бегите к каждой башни 4 башен по координатам: 33,53; 36,60; 44,61; 50,54 убейте дворфов внизу (если сможете) поднимитесь на башню и зажгите чашки" },
			[52] = { str = "52. Когда найдете все башни найтите безопасное место что бы спрыгнуть вниз и зайьти в пещеру в точке 41,54 и через дверь тюремной решетки по координатам 37,44 и бегите до комнаты с големом в точке 41,25 коснитесь камня со свечами и сдайте задание. Следующее задание ПРОПУСТИТЕ если у вас нет группы там нужно убить 2 элитных моба golem и dwarf", x = 41, y = 54, zone = "Searing Gorge" },
			[53] = { str = "53. Специально умри что бы оказаться в TP и идите в точку 29,38 сдайте задание #TURNINSet Them Ablaze!#, посмотри сцену где он превращается в дракона", x = 29, y = 38, zone = "Searing Gorge" },
			[54] = { str = "54. Откройте сундук на земле и возьмите задание #ACCEPTTrinkets...# затем откройте его снова и завершите задание. Откройте его и сохраните the Black Dragonflight Molt она пргодится в Burning Steppes." },
			[55] = { str = "55. Летите в Blasted Lands и бегите в Swamp of Sorrows" },
			[56] = { str = "56. Идите в точку 81,91 и найдите мурлока #NPCJarquia# для задания #DOQUESTLedger From Tanaris#", x = 81, y = 91, zone = "Swamp of Sorrows" },
			[57] = { str = "57. После того как вы его убьете вернитесь в IF затем используйте портал в Darnassus или летите Menethil и плывите на коробле в Auberdine и летите в Darnassus" },
			[58] = { str = "58. Поднимитесь на вершину холма в точке 38,80 и сдайте задание #TURNINPrayer to Elune pt.2#", x = 38, y = 80, zone = "darnassus" },
			[59] = { str = "59. Идите выше и сдайте задание #TURNINRise of the Silithid# и возьмите новое #ACCEPTMarch of the Silithid#" },
			[60] = { str = "60. Идите в точку 34,9 на вершине башни сдайте задание #TURNINAssisting Arch Druid Staghelm# и возьмите #ACCEPTUn'Goro Soil#", x = 34, y = 9, zone = "darnassus" },
			[61] = { str = "61. Сделайте Darnassus своим домом в точке 67,15", x = 67, y = 15, zone = "darnassus" },
			[62] = { str = "62. Теперь летите в Theramore или садитесь на корабль до Menethil затем плывите в Theramore" },
			[63] = { str = "63. Если у вас нет еще навыка первой помощи 290 приобретите heavy runecloth bandages" },
			[64] = { str = "64. Идите в точку 54,55 к затонувшему караблю и заберите overdue package для задания #DOQUESTLedger From Tanaris#", x = 54, y = 55, zone = "Duskwallow Marsh" },
			[65] = { str = "65. Идите в пещеру в точке 31,66 и коснитесь свитка в конце пещеры и сдайте задание #TURNINCortello's Riddle pt.2#, берите следующее #ACCEPTCortello's Riddle pt.3#", x = 31, y = 66, zone = "Duskwallow Marsh" },
			[66] = { str = "66. натравите на себя рапторов сто бы умереть и оказаться в Theramore" },
			[67] = { str = "67. Летите в Gadgetzan" },
			[68] = { str = "68. На входе в Gadgetzanсдайте задание #TURNINLedger From Tanaris#" },
			[69] = { str = "69. Достаньте свои перчатки 52 уровня и отправьте их по почте что бы получить их позже" },
			[70] = { str = "70. Между двумя северными воротами возьмите задание #ACCEPTSuper Sticky#" },
			[71] = { str = "71. Идте к хижине на западе и сдайте #TURNINMarch of the Silithid#, возьмите #ACCEPTBungle in the Jungle#" },
			[72] = { str = "72. Спуститесь в кратер Un’Goro в точке 26,52", x = 26, y = 52, zone = "Tanaris" },
		}
	},

-----------51-52 Un’Goro Crater
	--[502] = {
	[5152] = {
		title = "51-52 Un’Goro Crater",
		--n = "51-52 Un’Goro Crater",
		--pID = 501, nID = 503,
		--itemCount = 60,
		items = {
			[1] = { str = "1. 51-52 Un’Goro Crater" },
			[2] = { str = "2. Начинайте собирать предметы для заданий сразу вам понадобится: Power Crystals (нужно по 7 штук красных, голубых, зеленых, желтых), Так же собирайте кучи земли Un’Goro (соберите как можно больше), и Bloodpetal Sprouts соберите по 15 штук" },
			[3] = { str = "3. Гриндите птеродактелей что бы получить предмет #NPCA Mangled Journal# (шанс выпадения низкий) как только вы его найдете вам больше не придется их гриндить" },
			[4] = { str = "4. Идите к водопаду в точку 71,75 и возьмите задания #ACCEPTThe Apes of Un'Goro# и #ACCEPTThe Fare of Lar'Korwi#", x = 71, y = 75, zone = "Un’Goro Crater" },
			[5] = { str = "5. Гриндите до точки 62,68 и нажмите на утонувшую лодку и возьмите задание #ACCEPTIt's A Secret to Everybody pt.1# недалеко отсюда под водой сдайте задание и возьмите следующее #ACCEPTIt's A Secret to Everybody pt.2#", x = 62, y = 68, zone = "Un’Goro Crater" },
			[6] = { str = "6. Гриндите до точки 68,56 и убейте огромного динозавра для задания #DOQUESTThe Fare of Lar'Korwi#", x = 68, y = 56, zone = "Un’Goro Crater" },
			[7] = { str = "7. Вернитесь в точку 71,75 и сдайте задание #TURNINThe Fare of Lar'Korwi#, берите следующее #ACCEPTThe Scent of Lar'Korwi#", x = 71, y = 75, zone = "Un’Goro Crater" },
			[8] = { str = "8. Гриндите до точки 67,63 там будет 2 места с яйцами уничтожте всех raptors вокруг яиц и встаньте на яйца что бы появился нужный моб для задания #DOQUESTThe Scent of Lar'Korwi#", x = 67, y = 63, zone = "Un’Goro Crater" },
			[9] = { str = "9. Идите назад в точку 71,75 и сдайте задание #TURNINThe Scent of Lar'Korwi#, возьмите следующее #ACCEPTThe Bait For Lar'Korwi# к этому моменту вы должны дневник jornal если нет продолжайте убивать raptors пока выполняете задание в этом месте. Если журнал выпал возьмите задание #ACCEPTWilliden’s Journal#", x = 71, y = 75, zone = "Un’Goro Crater" },
			[10] = { str = "10. Идите в точку 79,49 на востоке между гор увидите большой скелет рядом есть плоский камень встаньте на него и используйте meat и phermone из сумки. Это призавет Lar’Korwi для задания #DOQUESTThe Bait For Lar'Korwi# его довольно легко убить", x = 79, y = 49, zone = "Un’Goro Crater" },
			[11] = { str = "11. Идите в точку 46,13 и возьмите задание #ACCEPTChasing A-Me 01# и бегите позади нее в убежище маршала Marshal’s Refuge.", x = 46, y = 13, zone = "Un’Goro Crater" },
			[12] = { str = "12. С лева возьмите задание #ACCEPTShizzle's Flyer#" },
			[13] = { str = "13. Дальше в лева чуть позади возьмите задание #ACCEPTMuigin and Larion#" },
			[14] = { str = "14. Далее возьмите задания #ACCEPTLost!# и #ACCEPTBeware of Pterrordax#" },
			[15] = { str = "15. Перед пещерой возьмите задание #ACCEPTRoll the Bones#" },
			[16] = { str = "16. Если у вас есть 15 bloodpetal sprouts, сдайте их для задания дейлика #ACCEPTDadanga is Hungry!# вы можете получить редкий и дорогой предмет по этому стоит попробовать" },
			[17] = { str = "17. Справа от пещеры возьмите задание #ACCEPTAlien Ecology#" },
			[18] = { str = "18. Снова поверните на право и сдайте #TURNINWilliden’s Journal# и возьмите #ACCEPTExpedition Salvation#" },
			[19] = { str = "19. Пройдите на юг и вы найдете Linken прямо возле полуполого дерева. Сдайте задание #TURNINIt's A Secret to Everybody pt.2# и возьмите следующее #ACCEPTIt's A Secret to Everybody pt.3#" },
			[20] = { str = "20. Откройте полетчика справа от пещеры потом зайдите в пещеру пройдите до конца и возьмите задание #ACCEPTCrystals of Power# и сдайте его. Возьмите 3 задания #ACCEPTThe Northern Pylon#, #ACCEPTThe Eastern Pylon# и #ACCEPTThe Western Pylon#" },
			[21] = { str = "21. При появлении следующих мобов сразу убивайте их при первой же возможности пока не завершится связанное с ним задание" },
			[22] = { str = "22. Убивайте bloodpetals для задания #DOQUESTMuigin and Larion#" },
			[23] = { str = "23. Убивайте diametradons и pterrodaxes для заданий #DOQUESTShizzle's Flyer# и #DOQUESTRoll the Bones#" },
			[24] = { str = "24. Убивайте pterrodaxes и frenzied pterrodaxes для задания #DOQUESTBeware of Pterrordax#" },
			[25] = { str = "25. Идите на восток вдоль гор в точку 54,13 поднимитесь и исследуйте  пилон pylon для задания #DOQUESTThe Northern Pylon# и идите на север там должны быть pterrodaxes.", x = 54, y = 13, zone = "Un’Goro Crater" },
			[26] = { str = "26. Идите на восток в товку 63,16 и убивайте gorillas для задания #DOQUESTThe Apes of Un'Goro# затем войдите в пещеру и держитесь правее что бы сдать задание #TURNINChasing A-Me 01# следующую часть задания ПРОПУСТИТЕ", x = 63, y = 16, zone = "Un’Goro Crater" },
			[27] = { str = "27. На черных озерах в точке 52,23 бейте monsters для задания #DOQUESTSuper Sticky#, в 3х озерах к югу от гарилл в точке 61,27 обитают такие же монстры более низкого уровня. Так же тут встречаются bloodpetals для задания #DOQUESTMuigin and Larion# тут рядом обитают diametradons и pterrodaxes для задания #DOQUESTShizzle's Flyer# running around", x = 61, y = 27, zone = "Un’Goro Crater" },
			[28] = { str = "28. Идите в точку 68,36 и возьмите ящик с продуктами для задания #DOQUESTExpedition Salvation#", x = 68, y = 36, zone = "Un’Goro Crater" },
			[29] = { str = "29. Постарайтесь собрать все предметы для задания #DOQUESTShizzle's Flyer# если вы не просто ходите ии щите их в одиночку. Мне кажется я всегда нахожу их раньше чем заканчиваю собирать bloodpetals." },
			[30] = { str = "30. Идите в точку 76,51 следуйте по тропе к пилону для задания #DOQUESTThe Eastern Pylon# южнее должны быть pterrodaxes в точке 75,61", x = 76, y = 51, zone = "Un’Goro Crater" },
			[31] = { str = "31. Идите в точку 71,75 и сдайте задания #TURNINThe Bait For Lar'Korwi# и #TURNINThe Apes of Un'Goro# следующее задание пока ПРОПУСТИТЕ", x = 71, y = 75, zone = "Un’Goro Crater" },
			[32] = { str = "32. Если вы много гриндили растений и динозавров вы должны быть близки к 52 уровню, если уже не получили его" },
			[33] = { str = "33. К востоку от вулкана (в середине карты) обитают pterrodaxes они нужны для задания #DOQUESTBeware of Pterrordax# если возникли проблемы с их поиском то 6 штук появлюятся южнее в точке 55,90", x = 55, y = 90, zone = "Un’Goro Crater" },
			[34] = { str = "34. Бегите на запад в точку 55,73 там спавн diametradon 5-6 штук убейте их если они вам все еще для задания #DOQUESTShizzle's Flyer# или #DOQUESTRoll the Bones#", x = 55, y = 73, zone = "Un’Goro Crater" },
			[35] = { str = "35. Идите на запад в точку 50,77 в извилистую пещеру на развилке поверните на лево в большую комнату по середине используйте флакон scraping vial для задания #DOQUESTAlien Ecology#", x = 50, y = 77, zone = "Un’Goro Crater" },
			[36] = { str = "36. Есть еще один респ diametradon camp если они вам еще нужны scales или bones для задания #DOQUESTShizzle's Flyer# или #DOQUESTRoll the Bones#" },
			[37] = { str = "37. Бегите по координатам 38,65 и возьмите research equipment для задания #DOQUESTExpedition Salvation#", x = 38, y = 65, zone = "Un’Goro Crater" },
			[38] = { str = "38. Бейте frenzied pterrodaxes около координат 35,38 в северо-западной части карты для задания #DOQUESTBeware of Pterrordax# а так же тут много diametradons для задания #DOQUESTShizzle's Flyer# или #DOQUESTRoll the Bones#", x = 35, y = 38, zone = "Un’Goro Crater" },
			[39] = { str = "39. Спуститесь в точку 23,59 и коснитесь западного пилона для задания #DOQUESTThe Western Pylon# и убивайте pterrodaxes которые вам нужны за ней", x = 23, y = 59, zone = "Un’Goro Crater" },
			[40] = { str = "40. Идите в точку 30,50 и выполните задание #DOQUESTFinding the Source#", x = 30, y = 50, zone = "Un’Goro Crater" },
			[41] = { str = "41. Идите в точку 51,48 и убивайте елементалей, старайтесь избегать мобов выше 56+ уровня для задания #DOQUESTVolcanic Activity# не трогайте blazing invaders alone", x = 51, y = 48, zone = "Un’Goro Crater" },
			[42] = { str = "42. После того отпустите питомца поднимитесь на маунте на вершину вулкана увидите скалы похожие на камни сумона слезьте с маунта и используйте thermometer" },
			[43] = { str = "43. Если вам не нужен пепел всеравно идите в точку 30,50 и сдайте задание #TURNINFinding the Source# и возьмите задание #ACCEPTThe New Springs#", x = 30, y = 50, zone = "Un’Goro Crater" },
			[44] = { str = "44. Поднимитесь в пещеру тем же способов в точке 51,49 и сдайте задание #TURNINLost!# задем возьмите #ACCEPTA Little Help From My Friends# выходите из пещеры аккуратно что бы не агрить все подряд как только уйдете от вулкана там уже будет легко. Не забывайте охлаждать его время от времени", x = 51, y = 49, zone = "Un’Goro Crater" },
			[45] = { str = "45. Когда приведете его в город подойдите к знаку и задание завершится, затем сдайте задание #TURNINBeware of Pterrordax#" },
			[46] = { str = "46. Сдайте задание #TURNINShizzle's Flyer#" },
			[47] = { str = "47. Сдайте задание #TURNINMuigin and Larion# следующее задание ПРОПУСТИТЕ" },
			[48] = { str = "48. Сдайте задание #TURNINRoll the Bones#" },
			[49] = { str = "49. Сдайте задание #TURNINAlien Ecology#" },
			[50] = { str = "50. Сдайте задание #TURNINExpedition Salvation#" },
			[51] = { str = "51. В пещере сдайте задания #TURNINThe Northern Pylon#, #TURNINThe Eastern Pylon#, #TURNINThe Western Pylon# и возьмите #ACCEPTMaking Sense of It# и сдайте его обратно. Она расскажет о бонусах пилонов" },
			[52] = { str = "52. Идите в точку 29,22 м идите по тропе в Slithus в точку 50,34 откройте полетчика и летите в Gadgetzan.", x = 29, y = 22, zone = "Un’Goro Crater" },
			[53] = { str = "53. Идите в северо-западную часть города и сдайте задание #TURNINBungle in the Jungle#, ПРОПУСТИТЕ следующее задание. Сдайте другое задание #TURNINSuper Sticky# между 2 выходами" },
			[54] = { str = "54. Жмите Hearth в Darnassus и выучите новые навыки у классового тренера" },
			[55] = { str = "55. У вас должно быть более 50 штук земли унгоро" },
			[56] = { str = "56. Идите в точку 31,8 и сдайте задание #TURNINUn'Goro Soil#", x = 31, y = 8, zone = "Darnassus" },
			[57] = { str = "57. Идите на вершину башни и возьмите задание #ACCEPTMorrowgrain Research pt.1# затем спуститесь и сдайте его. Берите следующее #ACCEPTMorrowgrain Research pt.2#" },
			[58] = { str = "58. В зависимости от количества почвенных участков, вам могут понадобиться дополнительные пакетики с семенами. Пакетик можно использовать каждые 10 минут, и урожай не всегда будет достаточным. В любом случае, вам нужно всего 10 пакетиков" },
			[59] = { str = "59. Идите в Rut’theran Village войдите в дом справа возьмите задание #ACCEPTMoontouched Wildkin# это задание в winterspring" },
			[60] = { str = "60. Летите в Astranaar, затем идите в точку 91,46 там мост ведет в Azshara", x = 91, y = 46, zone = "Ashenvale" },
		}
	},

-----------52-53 Azshara
	--[503] = {
	[5253] = {
		title = "52-53 Azshara",
		--n = "52-53 Azshara",
		--pID = 502, nID = 504,
		--itemCount = 10,
		items = {
			[1] = { str = "1. 52-53 Azshara" },
			[2] = { str = "2. Сразу с права в точке 11,77 откройте полетчика", x = 11, y = 77, zone = "Azshara" },
			[3] = { str = "3. За ним возьмите задания #ACCEPTSpiritual Unrest# и #ACCEPTA Land Filled With Hatred#" },
			[4] = { str = "4. Идите на север уничтожать призраков в точку 14,72 и 16,67 бейте их для задания #DOQUESTSpiritual Unrest#", x = 14, y = 72, zone = "Azshara" },
			[5] = { str = "5. Идите севернее в точку 19,61 и бейте satyr’s в этом районе для задания #DOQUESTA Land Filled With Hatred", x = 19, y = 61, zone = "Azshara" },
			[6] = { str = "6. Вернитесь в точку 11,77 и сдайте задания #TURNINSpiritual Unrest# и #TURNINA Land Filled With Hatred#", x = 11, y = 77, zone = "Azshara" },
			[7] = { str = "7. Идите в точку 39,55 и получите оттиск Markri rubbing для задания #DOQUESTArcane Runes#", x = 39, y = 55, zone = "Azshara" },
			[8] = { str = "8. Идите в точку 36,53 и получите оттиск Beth’Amara Rubbing для задания #DOQUESTArcane Runes#", x = 36, y = 53, zone = "Azshara" },
			[9] = { str = "9. Идите в точку 39,50 и получите оттиск Jin’yael rubbing для задания #DOQUESTArcane Runes#", x = 39, y = 50, zone = "Azshara" },
			[10] = { str = "10. Идите в точку 42,42 и сдайте задание #TURNINThe Hunter's Charm#, возьмите следующее #ACCEPTCourser Antlers# это задание является не обязательным и выполняется после получения 53 уровня. Я его выполняю потому что если его не выполнить то немного отстанете от руководства, на сбор этого и следующего задания уходит около 1-2 часов это позволит вам на 20-25% от необходимого уровня", x = 42, y = 42, zone = "Azshara" },
		}
	},

------------53-54 Felwood
	--[504] = {
	[5354] = {
		title = "53-54 Felwood",
		--n = "53-54 Felwood",
		--pID = 503, nID = 505,
		--itemCount = 54,
		items = {
			[1] = { str = "1. 53-54 Felwood" },
			[2] = { str = "2. Остановитесь в 54,86 и возьмите #ACCEPTCleansing Felwood#", x = 54, y = 86, zone = "Felwood" },
			[3] = { str = "3. Бегите немного на север к 51,81 и возьмите #ACCEPTForces of Jaedenar#", x = 51, y = 81, zone = "Felwood" },
			[4] = { str = "4. Внутри дома возьмите #ACCEPTThe Corruption of the Jadefire#" },
			[5] = { str = "5. Под палаткой возьмите #ACCEPTVerifying the Corruption# и #ACCEPTTo Winterspring!#" },
			[6] = { str = "6. Прямо через дорогу возьмите #ACCEPTTimbermaw Ally#" },
			[7] = { str = "7. Идите чуть юго-западнее отсюда около 48,91 и убивайте фурболгов, пока не выполните #DOQUESTTimbermaw Ally# Просто гриндите их всех на репутацию, пока не закончите", x = 48, y = 91, zone = "Felwood" },
			[8] = { str = "8. Идите обратно к 50,85 и сдайте #TURNINTimbermaw Ally# возьмите #ACCEPTSpeak to Nefian# другое — повторяемое на репутацию", x = 50, y = 85, zone = "Felwood" },
			[9] = { str = "9. Идите наверх около 2 озёр в 40,69 и убивайте проклятых слизней для первой части #DOQUESTA Little Slime Goes A Long Way pt.1#", x = 40, y = 69, zone = "Felwood" },
			[10] = { str = "10. Идите теперь на запад отсюда к 37,69 и убивайте демонов jadefire для #DOQUESTThe Corruption of the Jadefire# их также хорошо фармить.", x = 37, y = 69, zone = "Felwood" },
			[11] = { str = "11. Идите наверх к 39,59 и убивайте осквернённых слизней для второй части #DOQUESTA Little Slime Goes A Long Way pt.1", x = 39, y = 59, zone = "Felwood" },
			[12] = { str = "12. Идите чуть западнее отсюда около 37,59 и убивайте Jaedenar для #DOQUESTForces of Jaedenar# В пещеры заходить не обязательно.", x = 37, y = 59, zone = "Felwood" },
			[13] = { str = "13. Идите обратно к 51,82 и сдайте #TURNINForces of Jaedenar# возьмите #ACCEPTCollection of the Corrupt Water#.", x = 51, y = 82, zone = "Felwood" },
			[14] = { str = "14. Внутри дома сдайте #TURNINThe Corruption of the Jadefire# возьмите #ACCEPTFurther Corruption#" },
			[15] = { str = "15. Идите обратно наверх к Jaedenar к зелёному пруду в 35,59 и наполните флягу для #DOQUESTCollection of the Corrupt Water#", x = 35, y = 59, zone = "Felwood" },
			[16] = { str = "16. Идите обратно к 51,82 и сдайте #TURNINCollection of the Corrupt Water# возьмите #ACCEPTSeeking Spiritual Aid#", x = 51, y = 82, zone = "Felwood" },
			[17] = { str = "17. Идите наверх к 42,20 и убивайте Entropic beasts и horrors и исследуйте кратеры для #DOQUESTVerifying the Corruption#.", x = 42, y = 20, zone = "Felwood" },
			[18] = { str = "18. Идите наверх к 46,14 и следуйте вглубь, убивая демонов для #DOQUESTFurther Corruption# Когда убьёте Xavaric, он дропнет Flute of Xavaric, что начнёт #ACCEPTFlute of Xavaric# убивайте сатиров, чтобы завершить это.", x = 46, y = 14, zone = "Felwood" },
			[19] = { str = "19. Бегите к Irontree Cavern в 55,17 и убейте 15 элементалей, этого должно хватить для #DOQUESTCleansing Felwood#", x = 55, y = 17, zone = "Felwood" },
			[20] = { str = "20. Идите наверх к 62,24 и возьмите полетчика", x = 62, y = 24, zone = "Felwood" },
			[21] = { str = "21. Идите на север к 64,8 и сдайте #TURNINSpeak to Nefian# возьмите #ACCEPTDeadwood of the North#", x = 64, y = 8, zone = "Felwood" },
			[22] = { str = "22. Теперь спрыгните со скалы на запад и начинайте убивать для Deadwood of the North, как закончите — убивайте, пока не останется 150 репутации до следующего ранга с timbermaw (поставьте репутацию как полосу опыта для удобства)" },
			[23] = { str = "23. Идите обратно к 64,8 и сдайте #TURNINDeadwood of the North# теперь вы должны быть unfriendly и больше не агриться. Возьмите #ACCEPTSpeak to Salfa# и сдайте любые 5 наборов перьев для дополнительной репутации и 550 опыта", x = 64, y = 8, zone = "Felwood" },
			[24] = { str = "24. Идите через пещеру в Winterspring и прямо снаружи пещеры справа в 27,34 сдайте #TURNINSpeak to Salfa#", x = 27, y = 34, zone = "Winterspring" },
			[25] = { str = "25. Бегите на юг к 31,45 и сдайте #TURNINThe New Springs# возьмите #ACCEPTStrange Sources# также сдайте #TURNINIt's A Secret to Everybody pt.3# возьмите #ACCEPTThe Videre Elixir# и #ACCEPTThreat of the Winterfall#", x = 31, y = 45, zone = "Winterspring" },
			[26] = { str = "26. Бегите обратно через пещеру и идите на запад на развилке в Moonglade." },
			[27] = { str = "27. Идите к 48,67 и возьмите полетчика", x = 48, y = 67, zone = "Moodglade" },
			[28] = { str = "28. Сейчас вы должны быть очень близко к левелапу. Можете догриндить остаток или подождать. #PICTUREHearth в Astranaar и летите в Feralas#" },
			[29] = { str = "29. Зайдите в таверну, возьмите #ACCEPTJonespyre's Request#" },
			[30] = { str = "30. Поднимитесь на верх башни, сдайте его, возьмите #ACCEPTThe Mystery of Morrowgrain# сдайте его обратно, если вы всё ещё делаете эту штуку." },
			[31] = { str = "31. #HUTNERStable your pet# и езжайте или плывите на материк" },
			[32] = { str = "32. #HUNTER31) Приручите Ironfur Patriarch 48+ для Claw rank 7#"},
			[33] = { str = "33. Идите наверх к 45,25 и купите приманку и прочитайте, как получить videre elixir", x = 45, y = 25, zone = "Feralas" },
			[34] = { str = "34. В 45,16 вас могут поднять на верх колоссальной башни и сбросить с парашютом. Только убедитесь, что сняли маунта!", x = 45, y = 16, zone = "Feralas" },
			[35] = { str = "35. Идите наверх к 44,10 и положите приманку на землю, затем идите лутать everroot", x = 44, y = 10, zone = "Felalas" },
			[36] = { str = "36. Идите обратно на юг к 45,25, чтобы получить свои 3 videre elixir", x = 45, y = 25, zone = "Felalas" },
			[37] = { str = "37. #PICTUREHearth# в Astranaar" },
			[38] = { str = "38. #HUTNER37) Достаньте кота обратно#"},
			[39] = { str = "39. Бегите обратно наверх в Felwood к 54,86 и сдайте #TURNINCleansing Felwood#", x = 54, y = 86, zone = "Felwood" },
			[40] = { str = "40. Теперь она позволяет вам получать материалы для неплохих зелий, у которых другие кулдауны, чем у обычных зелий." },
			[41] = { str = "41. Идите наверх к 51,81 и в доме сдайте #TURNINFurther Corruption# и #TURNINFlute of Xavaric# возьмите #ACCEPTFelbound Ancients#", x = 51, y = 81, zone = "Felwood" },
			[42] = { str = "42. Под палаткой сдайте #TURNINVerifying the Corruption#" },
			[43] = { str = "43. Бегите наверх к 62,23", x = 62, y = 23, zone = "Felwood" },
			[44] = { str = "44. Идите через пещеру в Winterfall и прямо снаружи пещеры возьмите #ACCEPTWinterfall Activity#" },
			[45] = { str = "45. Идите к 31,45 и сдайте #TURNINThe Videre Elixir# возьмите #ACCEPTMeet at the Grave#", x = 31, y = 45, zone = "Winterspring" },
			[46] = { str = "46. Идите к 62,36 и возьмите полетчика", x = 62, y = 36, zone = "Winterspring" },
			[47] = { str = "47. Летите в Rachet" },
			[48] = { str = "48. Бегите на запад от дока и сдайте #TURNINVolcanic Activity#" },
			[49] = { str = "49. Бегите вниз к 65,43 и сдайте #TURNINSeeking Spiritual Aid# возьмите Cleansed Water Returns to Felwood", x = 65, y = 43, zone = "The Barrens" },
			[50] = { str = "50. Летите в Theramore и плывите в Menethil, затем летите в IF" },
			[51] = { str = "51. Прямо снаружи Military Ward должен быть бродячий НПС, один также рядом с полетчиком, возьмите задание #ACCEPTThe New Frontier pt.1#" },
			[52] = { str = "52. Идите к 75,23 и сдайте #TURNINA Little Slime Goes A Long Way pt.1# возьмите #ACCEPTA Little Slime Goes A Long Way pt.2#", x = 75, y = 23, zone = "Ironforge" },
			[53] = { str = "53. Идите к 31,4 и сдайте #TURNINReturn to Tymor#", x = 31, y = 4, zone = "Ironforge" },
			[54] = { str = "54. Летите в Menethil, затем плывите в Theramore и летите в Gadgetzan" },
		}
	},

-----------54-54 Tanaris
	--[505] = {
	[5453] = {
		title = "54-54 Tanaris",
		--n = "54-54 Tanaris",
		--pID = 504, nID = 506,
		--itemCount = 20,
		items = {
			[1] = { str = "1. 54-54 Tanaris" },
			[2] = { str = "2. Достаньте свой mithril casing из банка или почтового ящика" },
			[3] = { str = "3. Идите на восток к кладбищу в 54,28 и выпейте свой videre elixir", x = 54, y = 28, zone = "Tanaris" },
			[4] = { str = "4. Теперь вы умрёте, не воскрешайтесь, просто выйдите духом и бегите на север к 53,23 и сдайте #TURNINMeet at the Grave# возьмите #ACCEPTA Grave Situation#", x = 53, y = 23, zone = "Tanaris" },
			[5] = { str = "5. Идите обратно и воскресните в 54,28 и коснитесь единственного надгробия там, сдайте #TURNINA Grave Situation# возьмите #ACCEPTLinken's Sword#", x = 54, y = 28, zone = "Tanaris" },
			[6] = { str = "6. Бегите в Un’Goro, я бы сказал летите, но нам нужно очень далеко на юго-восток" },
			[7] = { str = "7. Бегите наверх к 71,75 и возьмите #ACCEPTThe Mighty U'cha#", x = 71, y = 75, zone = "Un’Goro" },
			[8] = { str = "8. Продолжайте собирать землю здесь, если вам нужно больше morrowgrain" },
			[9] = { str = "9. Теперь по всему кратеру есть слизни, но всех нужных можно найти к западу от вулкана около 37,37 для #DOQUESTA Little Slime Goes A Long Way pt.2# Думаю, их больше на западной стороне вулкана, но можете поискать с обеих сторон, они разбросаны. Если написано, что они клонируются, добивайте их очень быстро или станьте их. Если они склонируются — это моб с полным здоровьем, которого нельзя собрать.", x = 37, y = 37, zone = "Un’Goro" },
			[10] = { str = "10. Идите в пещеру в 64,16 и идите направо, когда увидите A-Me 01, возьмите #ACCEPTChasing A-Me 01 pt.1# и сдайте обратно. Упадите за край и направо и вверх вокруг, пока не увидите U’cha для #DOQUESTThe Mighty U'cha#", x = 64, y = 16, zone = "Un’Goro" },
			[11] = { str = "11. Бегите обратно к входу и снова направо и возьмите #ACCEPTChasing A-Me 01 pt.2# теперь сопроводите её наружу" },
			[12] = { str = "12. Сопроводите A-Me к Marshal’s в 46,13 и сдайте #TURNINChasing A-Me 01 pt.2#", x = 46, y = 13, zone = "Un’Goro" },
			[13] = { str = "13. Зайдите в Marshal’s и сдайте #TURNINLinken's Sword# возьмите #ACCEPTA Gnome's Assistance#" },
			[14] = { str = "14. Идите в глубь пещеры и сдайте #TURNINA Gnome's Assistance# и возьмите #ACCEPTLinken’s Memory#" },
			[15] = { str = "15. Бегите вниз и дайте смоляным монстрам убить вас, чтобы оказаться ближе к юго-востоку" },
			[16] = { str = "16. Бегите вниз к 71,75 и сдайте #TURNINThe Mighty U'cha#", x = 71, y = 75, zone = "Un’Goro" },
			[17] = { str = "17. Теперь вы должны быть больше чем на половине пути к 55 уровню" },
			[18] = { str = "18. Жмите Hearth обратно в Astranaar и летите в Darnassus" },
			[19] = { str = "19. Зайдите в Temple of the Moon в 39,84 и наполните флакон для #DOQUESTFelbound Ancients#", x = 39, y = 84, zone = "Darnassus" },
			[20] = { str = "20. Бегите в Felwood" },
		}
	},

-----------54-54 Felwood
	--[506] = {
	[5454] = {
		title = "54-54 Felwood",
		--n = "54-54 Felwood",
		--pID = 505, nID = 507,
		--itemCount = 16,
		items = {
			[1] = { str = "1. 54-54 Felwood" },
			[2] = { str = "2. Идите к 51,82 и сдайте #TURNINCleansed Water Returns to Felwood# возьмите #ACCEPTDousing the Flames of Protection#", x = 51, y = 82, zone = "Felwood" },
			[3] = { str = "3. Зайдите в дом, сдайте #TURNINFelbound Ancients# возьмите #ACCEPTPurified!# затем сдайте его обратно, лёгкие 10к опыта. Также сдайте #TURNINLinken’s Memory# возьмите #ACCEPTSilver Heart#" },
			[4] = { str = "4. Теперь вы должны быть на 70% пути или близко к тому" },
			[5] = { str = "5. Начните убивать всех медведей и волков отсюда на север, пока не получите 11 серебристых когтей для #DOQUESTSilver Heart#" },
			[6] = { str = "6. Идите в пещеру в 35,58", x = 35, y = 58, zone = "Felwood" },
			[7] = { str = "7. В первой открытой области с НПС в клетке в 36,56 находится жаровня для #DOQUESTDousing the Flames of Protection# 2-я прямо вверх по пандусу", x = 36, y = 56, zone = "Felwood" },
			[8] = { str = "8. Продолжайте мимо комнаты со свечами вокруг дыры к следующей открытой комнате в 36,53 для 3-й и 4-й жаровни для #DOQUESTDousing the Flames of Protection#", x = 36, y = 53, zone = "Felwood" },
			[9] = { str = "9. Даже не пытайтесь делать эскорт, если не найдёте группу, я всегда его пропускаю, даже если нахожу ключ." },
			[10] = { str = "10. Бегите обратно наружу и наверх к 51,19 и убивайте элементалей-деревья для #DOQUESTSilver Heart#", x = 51, y = 19, zone = "Felwood" },
			[11] = { str = "11. Если хотите сделать эскорт с флейтой, советую найти группу, на вас нападает много мобов." },
			[12] = { str = "12. Бегите всю дорогу обратно вниз к 51,82 (я знаю, никто не хочет бежать сюда обратно, почему квестовый хаб так далеко от полетчика — выше моего понимания)", x = 51, y = 82, zone = "Felwood" },
			[13] = { str = "13. Сдайте #TURNINDousing the Flames of Protection# ПРОПУСТИТЕ следующую часть пока" },
			[14] = { str = "14. В доме сдайте #TURNINSilver Heart# возьмите #ACCEPTAquementas#" },
			[15] = { str = "15. Если у вас есть скиннинг, уверен, у вас есть как минимум 5 tainted hides, идите вниз к 54,86 и сдайте их для #TURNINSalve via Skinning#", x = 54, y = 86, zone = "Felwood" },
			[16] = { str = "16. Жмите Hearth в Astranaar и летите в Winterspring" },
		}
	},

--------------54-55 Winterspring
	--[507] = {
	[5455] = {
		title = "54-55 Winterspring",
		--n = "54-55 Winterspring",
		--pID = 506, nID = 508,
		--itemCount = 34,
		items = {
			[1] = { str = "1. 54-55 Winterspring" },
			[2] = { str = "2. Зайдите в Everlook возьмите #ACCEPTEnraged Wildkin pt.1#" },
			[3] = { str = "3. Зайдите в таверну, сделайте её своим домом" },
			[4] = { str = "4. Возьмите #ACCEPTThe Everlook Report# #ACCEPTDuke Nicholas Zverenhoff# и #ACCEPTSister Pamela#" },
			[5] = { str = "5. На другой стороне города возьмите #ACCEPTAre We There, Yeti? pt.1#" },
			[6] = { str = "6. Следите за синими перьями мункинов, чтобы завершить #DOQUESTMoontouched Wildkin#" },
			[7] = { str = "7. Бегите всю дорогу на юг к 60,73, чтобы завершить #ACCEPTStrange Sources#", x = 60, y = 73, zone = "Winterspring" },
			[8] = { str = "8. Жмите Hearth обратно в Everlook, если он не готов — умрите специально" },
			[9] = { str = "9. Идите к 65,45 и убивайте йети для #DOQUESTAre We There, Yeti? pt.1#", x = 65, y = 45, zone = "Winterspring" },
			[10] = { str = "10. Бегите обратно в Everlook и сдайте #TURNINAre We There, Yeti? pt.1# возьмите #ACCEPTAre We There, Yeti? pt.2#" },
			[11] = { str = "11. Идите обратно к 65,45 и убивайте матриархов и патриархов для #DOQUESTAre We There, Yeti? pt.2# их много в пещере в 67,42", x = 67, y = 42, zone = "Winterspring" },
			[12] = { str = "12. Бегите обратно в Everlook и сдайте #TURNINAre We There, Yeti? pt.2# возьмите #ACCEPTAre We There, Yeti? pt.3#" },
			[13] = { str = "13. Идите чуть восточнее таверны и напугайте Legacki для #DOQUESTAre We There, Yeti? pt.3#" },
			[14] = { str = "14. Идите на восток от Winterspring к 66,34 и убивайте фурболгов там для #DOQUESTWinterfall Activity# и части #DOQUESTThreat of the Winterfall#", x = 66, y = 34, zone = "Winterspring" },
			[15] = { str = "15. Надеюсь, вы найдёте #NPCEmpty Firewater Flask# на одном из них, что начнёт #ACCEPTWinterfall Firewater#" },
			[16] = { str = "16. Бегите наверх к Starfall Village в 51,30 и сдайте #TURNINTo Winterspring!# возьмите #ACCEPTThe Ruins of Kel'Theril#", x = 51, y = 30, zone = "Winterspring" },
			[17] = { str = "17. Сдайте #TURNINEnraged Wildkin pt.1# ПРОПУСТИТЕ часть 2 пока, также сдайте #TURNINThe Ruins of Kel'Theril# возьмите #ACCEPTTroubled Spirits of Kel'Theril#" },
			[18] = { str = "18. Возьмите реликвию в 55,42 для #DOQUESTTroubled Spirits of Kel'Theril# отпустите пета перед тем, как открывать их, затем бегите и используйте FD. 2-я реликвия в 53,43. 3-я в 52,41 4-я в 50,41" },
			[19] = { str = "19. Идите на запад к 39,43 и убивайте фурболгов здесь для #DOQUESTThreat of the Winterfall# также убедитесь, что у вас есть 10 перьев для #DOQUESTMoontouched Wildkin#", x = 39, y = 43, zone = "Winterspring" },
			[20] = { str = "20. Идите к 31,45 и сдайте #TURNINStrange Sources# #TURNINThreat of the Winterfall# и #TURNINWinterfall Firewater# возьмите #ACCEPTFalling to Corruption#", x = 31, y = 45, zone = "Winterspring" },
			[21] = { str = "21. Бегите к 27,34 и сдайте #TURNINWinterfall Activity#", x = 27, y = 34, zone = "Winterspring" },
			[22] = { str = "22. Теперь вы должны быть на 25-30% в 55 уровне" },
			[23] = { str = "23. Бегите через туннель в Felwood" },
			[24] = { str = "24. Идите к 60,5 и коснитесь котла в лагере, что сдаст #TURNINFalling to Corruption# возьмите #ACCEPTMystery Goo#", x = 60, y = 5, zone = "Winterspring" },
			[25] = { str = "25. Жмите Hearth в Everlook, затем летите в Darnassus" },
			[26] = { str = "26. В Rut’theran Village сдайте #TURNINMoontouched Wildkin# 55,92 возьмите #ACCEPTFind Ranshalla#", x = 55, y = 92, zone = "Darnassus" },
			[27] = { str = "27. Идите в Darnassus наверх к 34,8 в большую башню и сдайте #TURNINThe New Frontier pt.1# возьмите #ACCEPTThe New Frontier pt.2# спуститесь на 1 этаж и сдайте его, возьмите #ACCEPTRabine Saturna#", x = 34, y = 8, zone = "Darnassus" },
			[28] = { str = "28. Летите в Moonglade к 51,45 и сдайте #TURNINRabine Saturna# возьмите #ACCEPTWasteland#", x = 51, y = 45, zone = "Moonglade" },
			[29] = { str = "29. Летите в Auberdine, плывите в Menethil и летите в IF, сделайте его своим домом. Убедитесь, что у вас есть ваш black dragonflight molt" },
			[30] = { str = "30. Идите к 75,23 и сдайте #TURNINA Little Slime Goes A Long Way pt.2#", x = 75, y = 23, zone = "Ironforge" },
			[31] = { str = "31. Идите к 38,55 в тронный зал и возьмите #ACCEPTThe Smoldering Ruins of Thaurissan pt.1# затем щёлкните по ней и послушайте историю и сдайте обратно, возьмите #ACCEPTThe Smoldering Ruins of Thaurissan pt.2#", x = 38, y = 55, zone = "Ironforge" },
			[32] = { str = "32. Перед полетчиком возьмите #ACCEPTTaking Back Silithus#" },
			[33] = { str = "33. Летите в Lakeshire" },
			[34] = { str = "34. Бегите на север к 46,6 и войдите в Burning Steppes", x = 46, y = 6, zone = "Redridge Mountains" },
		}
	},

-----------55-56 Burning Steppes
	--[508] = {
	[5556] = {
		title = "55-56 Burning Steppes",
		--n = "55-56 Burning Steppes",
		--pID = 507, nID = 509,
		--itemCount = 29,
		items = {
			[1] = { str = "1. 55-56 Burning Steppes" },
			[2] = { str = "2. Идите к 83,63 и следуйте по тропе наверх и возьмите полетчика", x = 83, y = 63, zone = "Burning Steps" },
			[3] = { str = "3. Возьмите #ACCEPTExtinguish the Firegut# и #ACCEPTFIFTY! YEP!#" },
			[4] = { str = "4. Перед разрушенным домом возьмите #ACCEPTDragonkin Menace# Это начало цепочки на ключ от Ониксии" },
			[5] = { str = "5. Начните убивать огров по всей горе в 81,42 для #DOQUESTExtinguish the Firegut# затем бегите обратно к 84,68 и сдайте, возьмите #ACCEPTGor'tesh the Brute Lord#", x = 81, y = 42, zone = "Burning Steps" },
			[6] = { str = "6. Идите на северо-запад к 66,40 и соберите руины, которые выглядят как надгробия, для #DOQUESTThe Smoldering Ruins of Thaurissan pt.2#", x = 66, y = 40, zone = "Burning Steps" },
			[7] = { str = "7. Бегите наверх к 65,24 и зайдите в пещеру, сдайте #TURNINYuka Screwspigot# ПРОПУСТИТЕ остальное", x = 65, y = 24, zone = "Burning Steps" },
			[8] = { str = "8. Снаружи возьмите #ACCEPTTablet of the Seven# и #ACCEPTBroodling Essence#" },
			[9] = { str = "9. Идите к 54,40 и коснитесь статуи дворфа для #DOQUESTTablet of the Seven#", x = 54, y = 40, zone = "Burning Steps" },
			[10] = { str = "10. Идите на запад к 43,46 к blackrock stronghold или на юг к 49,55 к pillar of ash и убивайте орков для #DOQUESTFIFTY! YEP!# они дропаются в больших количествах", x = 43, y = 46, zone = "Burning Steps" },
			[11] = { str = "11. Пока в pillar of ash в 40,56 вы должны убить Gor’tesh для #DOQUESTGor'tesh the Brute Lord#", x = 40, y = 56, zone = "Burning Steps" },
			[12] = { str = "12. Найдите группу, если можете, для #DOQUESTDragonkin Menace# и затем убивайте мобов для него прямо к северо-востоку от лагеря вдоль восточной стены. Его можно солоить, но на грани. Также соберите 8 broodlings для #DOQUESTBroodling Essence#, используя устройство на них перед атакой." },
			[13] = { str = "13. Идите в пещеру в 94,31 и возьмите #ACCEPTA Taste of Flame# затем отдайте ему molt и сдайте задание обратно. ПРОПУСТИТЕ следующую часть", x = 94, y = 31, zone = "Burning Steps" },
			[14] = { str = "14. Бегите обратно наверх к 65,23 и сдайте #TURNINTablet of the Seven# и #TURNINBroodling Essence# возьмите #ACCEPTFelnok Steelspring#", x = 65, y = 23, zone = "Burning Steps" },
			[15] = { str = "15. Езжайте обратно к 84,68 и рядом с грифоном сдайте #TURNINFIFTY! YEP!# и #TURNINGor'tesh the Brute Lord# возьмите #ACCEPTOgre Head On A Stick = Party#", x = 84, y = 68, zone = "Burning Steps" },
			[16] = { str = "16. Перед разрушенным домом сдайте #TURNINDragonkin Menace# возьмите #ACCEPTThe True Masters pt.1#" },
			[17] = { str = "17. Бегите наверх к вершине горы в 80,45 и щёлкните по мягкой куче земли для #DOQUESTOgre Head On A Stick = Party# затем бегите обратно к 84,68 и сдайте", x = 80, y = 45, zone = "Burning Steps" },
			[18] = { str = "18. Летите в Lakeshire и бегите в ратушу в 29,44 и сдайте #TURNINThe True Masters pt.1# возьмите #ACCEPTThe True Masters pt.2#", x = 29, y = 44, zone = "Redridge Mountains" },
			[19] = { str = "19. Летите в SW" },
			[20] = { str = "20. Идите к 78,18 в SW keep и сдайте #TURNINThe True Masters pt.2# возьмите #ACCEPTThe True Masters pt.3# затем поговорите с леди и сдайте обратно и возьмите #ACCEPTThe True Masters pt.4#", x = 78, y = 18, zone = "Stormwind City" },
			[21] = { str = "21. Летите обратно в Lakeshire и идите в ратушу в 29,44 и сдайте #TURNINThe True Masters pt.4# возьмите #ACCEPTThe True Masters pt.5#", x = 29, y = 44, zone = "Redridge Mountains" },
			[22] = { str = "22. Летите в Burning Steppes и сдайте #TURNINThe True Masters pt.5# когда приземлитесь и возьмите #ACCEPTThe True Masters pt.6#" },
			[23] = { str = "23. Бегите наверх к 64,23 и послушайте ragged john затем бегите обратно к 84,68 и сдайте #TURNINThe True Masters pt.6# Я ПРОПУСКАЮ следующую часть, сделайте позже, если беспокоитесь о скорости прокачки. Это были лёгкие 30к опыта ни за что, и ваша цепочка на ключ от Ониксии начата.", x = 64, y = 23, zone = "Burning Steps" },
			[24] = { str = "24. Теперь вы должны быть в 10к от 56 уровня, гриндите до 5к на орках в 49,55", x = 49, y = 55, zone = "Burning Steps" },
			[25] = { str = "25. Жмите Hearth в IF" },
			[26] = { str = "26. Идите в тронный зал в 38,55 и сдайте  #TURNINThe Smoldering Ruins of Thaurissan pt.2#", x = 38, y = 55, zone = "Ironforge" },
			[27] = { str = "27. Теперь вы должны быть 56 уровня, получите новые навыки" },
			[28] = { str = "28. Летите в Menethil и плывите в Theramore" },
			[29] = { str = "29. Летите в Gadgetzan" },
		}
	},

-----------56-56 Tanaris
	--[509] = {
	[5655] = {
		title = "56-56 Tanaris",
		--n = "56-56 Tanaris",
		--pID = 508, nID = 510,
		--itemCount = 9,
		items = {
			[1] = { str = "1. 56-56 Tanaris" },
			[2] = { str = "2. Идите к северо-западной стороне города и напугайте sprinkle для #DOQUESTAre We There, Yeti? pt.3#" },
			[3] = { str = "3. Сделайте Gadgetzan своим домом" },
			[4] = { str = "4. К югу от lost rigger cove в 70,49 есть куча камней в кругу, залутайте вещи из синего рюкзака и используйте книгу, чтобы призвать Aquementas. Он водный элементаль 54 уровня", x = 70, y = 49, zone = "Tanaris" },
			[5] = { str = "5. Жмите Hearth в Gadgetzan или умрите, если он ещё не готов." },
			[6] = { str = "6. Летите в Un’goro" },
			[7] = { str = "7. Найдите Quixxil и напугайте его для #DOQUESTAre We There, Yeti? pt.3#" },
			[8] = { str = "8. Идите в глубь пещеры и сдайте #TURNINAquementas# возьмите #ACCEPTLinken's Adventure# и сдайте его прямо снаружи пещеры у большого дерева ПРОПУСТИТЕ следующую часть" },
			[9] = { str = "9. Летите в Silithus" },
		}
	},

-----------56-56 Silithus
	--[510] = {
	[5656] = {
		title = "56-56 Silithus",
		--n = "56-56 Silithus",
		--pID = 509, nID = 511,
		--itemCount = 42,
		items = {
			[1] = { str = "1. 56-56 Silithus" },
			[2] = { str = "2. Рядом с лунным колодцем возьмите #ACCEPTThe Twilight Mystery#" },
			[3] = { str = "3. Перед таверной сдайте #TURNINTaking Back Silithus# возьмите #ACCEPTSecuring the Supply Lines#" },
			[4] = { str = "4. ПРОПУСТИТЕ задание на табличке, если не найдёте группу" },
			[5] = { str = "5. Сделайте Cenarion Hold своим домом" },
			[6] = { str = "6. Наверху возьмите #ACCEPTDeadly Desert Venom#" },
			[7] = { str = "7. Кажется, много белых заданий, потому что есть много заданий AQ, о которых пока не нужно беспокоиться." },
			[8] = { str = "8. Выполните #DOQUESTSecuring the Supply Lines# и #DOQUESTDeadly Desert Venom# к северу и северо-востоку от города повсюду около 55,24 dredges, scorpids и skitterers для этих 2 заданий по всей этой области.", x = 55, y = 24, zone = "Silithus" },
			[9] = { str = "9. Бегите наверх к 81,18 и сдайте #TURNINWasteland# возьмите #ACCEPTThe Spirits of Southwind#", x = 81, y = 18, zone = "Silithus" },
			[10] = { str = "10. Бегите на северо-запад к 22,9 и подберите фрагменты twilight tablet для #DOQUESTThe Twilight Mystery# Они усеивают это место", x = 22, y = 9, zone = "Silithus" },
			[11] = { str = "11. Жмите Hearth в Cenarion Hold" },
			[12] = { str = "12. Наверху сдайте #TURNINDeadly Desert Venom# возьмите #ACCEPTNoggle's Last Hope#" },
			[13] = { str = "13. Перед таверной сдайте #TURNINSecuring the Supply Lines# возьмите #ACCEPTStepping Up Security#" },
			[14] = { str = "14. Идите рядом с лунным колодцем и сдайте #TURNINThe Twilight Mystery# возьмите #ACCEPTThe Deserter#" },
			[15] = { str = "15. Теперь вы должны быть примерно на 30-35% в 56 уровне" },
			[16] = { str = "16. Идите на юго-восток к 62,53 и убивайте мобов-нежить здесь для #DOQUESTThe Spirits of Southwind# осторожно, когда они умирают, появляется 1-2 жука", x = 62, y = 53, zone = "Silithus" },
			[17] = { str = "17. Убивайте pincers для #DOQUESTNoggle's Last Hope# и drudges для #DOQUESTThe Deserter# к югу отсюда около 56,58", x = 56, y = 58, zone = "Silithus" },
			[18] = { str = "18. Идите в пещеру в 67,69 и сдайте #TURNINThe Deserter# возьмите #ACCEPTThe Twilight Lexicon#", x = 67, y = 69, zone = "Silithus" },
			[19] = { str = "19. Вы можете найти flayers и stalkers снаружи пещеры для #DOQUESTNoggle's Last Hope# они также оба около 43,72 на другой стороне улья", x = 43, y = 72, zone = "Silithus" },
			[20] = { str = "20. Жмите Hearth обратно в Cenarion Hold или умрите, чтобы оказаться там" },
			[21] = { str = "21. Идите наверх и сдайте для #TURNINNoggle's Last Hope# возьмите #ACCEPTNoggle's Lost Satchel#" },
			[22] = { str = "22. Снаружи таверны сдайте #TURNINStepping Up Security#" },
			[23] = { str = "23. Идите к 29,35 и убейте Twilight Keeper Manya для #DOQUESTThe Twilight Lexicon# она немного боится. Она в юго-восточном углу лагеря", x = 29, y = 35, zone = "Silithus" },
			[24] = { str = "24. Идите к 41,41 и убейте Twilight Keeper Havanuth для #DOQUESTThe Twilight Lexicon# он на восточной стороне лагеря, у него неприятное аое", x = 41, y = 41, zone = "Silithus" },
			[25] = { str = "25. Идите всю дорогу на юг к маленькому лагерю в 42,90 и поднимитесь на холм за ним, вы найдёте Deathclasp, посередине тропы на стене есть мешочек, заберите его, когда Deathclasp в глубине, для #DOQUESTNoggle's Lost Satchel#", x = 42, y = 90, zone = "Silithus" },
			[26] = { str = "26. Направляйтесь на юго-запад к 16,87 и убейте Twilight Keeper Exeter для #DOQUESTThe Twilight Lexicon# он в юго-западном углу лагеря", x = 16, y = 87, zone = "Silithus" },
			[27] = { str = "27. Идите обратно в пещеру в 67,69 и сдайте #TURNINThe Twilight Lexicon# возьмите #ACCEPTA Terrible Purpose# Он также предлагает другое задание за 10 twilight texts, это больше для репутации cen circle позже", x = 67, y = 69, zone = "Silithus" },
			[28] = { str = "28. Бегите наверх к 81,18 и сдайте #TURNINThe Spirits of Southwind# возьмите #ACCEPTHive in the Tower#", x = 81, y = 18, zone = "Silithus" },
			[29] = { str = "29. Идите на верх башни в 61,52 Будьте осторожны, при входе появляются 3 жука. Shift + правая кнопка по кокону, потому что как только вы его откроете, появятся amushers. Убейте как минимум 1 и залутайте его для #DOQUESTHive in the Tower#", x = 61, y = 52, zone = "Silithus" },
			[30] = { str = "30. Идите наверх к 81,18 и сдайте #TURNINHive in the Tower# возьмите #ACCEPTUmber, Archivist#", x = 81, y = 18, zone = "Silithus" },
			[31] = { str = "31. Жмите Hearth в Cenarion Hold" },
			[32] = { str = "32. ......." },
			[33] = { str = "33. Идите наверх и сдайте #TURNINNoggle's Lost Satchel#" },
			[34] = { str = "34. Идите в длинное здание и сдайте #TURNINA Terrible Purpose#" },
			[35] = { str = "35. Летите в Moonglade" },
			[36] = { str = "36. Идите к 44,35 и сдайте #TURNINUmber, Archivist# возьмите #ACCEPTUncovering Past Secrets#", x = 44, y = 35, zone = "Moonglade" },
			[37] = { str = "37. Бегите к 51,44 и сдайте #TURNINUncovering Past Secrets#", x = 44, y = 35, zone = "Moonglade" },
			[38] = { str = "38. Теперь вы должны быть на 80-85% в левелинге" },
			[39] = { str = "39. Летите в Auberdine и плывите в Menethil, затем летите в IF" },
			[40] = { str = "40. Сделайте IF своим домом, затем найдите бродячего командира-дворфа и возьмите  #ACCEPTA Call To Arms: The Plaguelands!#" },
			[41] = { str = "41. Летите в Southshore" },
			[42] = { str = "42. Бегите на север в Alterac Mountains и на северо-восток к 80,34 и бегите в Western Plaguelands (WPL)", x = 80, y = 34, zone = "Alterac Mountains" },
		}
	},

------------56-57 Western Plaguelands
	--[511] = {
	[5657] = {
		title = "56-57 Western Plaguelands",
		--n = "56-57 Western Plaguelands",
		--pID = 510, nID = 512,
		--itemCount = 44,
		items = {
			[1] = { str = "1. 56-57 Western Plaguelands" },
			[2] = { str = "2. Рядом с хижиной возьмите #ACCEPTA Plague Upon Thee pt.1#" },
			[3] = { str = "3. Возьмите полетчика" },
			[4] = { str = "4. Всякий раз, когда возвращаетесь в лагерь здесь, всегда проверяйте торговца на рецепт stormshroud pants. Он стоит около 1.3г, и вы легко продадите его за 10 или 20г+ Это ограниченный рецепт, который пополняется 1 раз в час." },
			[5] = { str = "5. Идите к палатке и сдайте #TURNINA Call To Arms: The Plaguelands!#, возьмите #ACCEPTClear The Way#" },
			[6] = { str = "6. Идите к 3 людям Argent Dawn рядом с другой палаткой и сдайте #TURNINThe Everlook Report# а также завершите #ACCEPTArgent Dawn Commission# это не задание, которое у вас было, она просто использует его, чтобы дать вам аксессуар, который вы всегда должны носить в WPL и EPL, потому что он даёт репутацию AD и позволяет выпадать scourge tokens, на которые у неё также есть 3 новых задания на сдачу. Скорее всего вы не получите ничего дальше первого задания, так как остальные в основном в инстансах." },
			[7] = { str = "7. Сохраняйте tokens, пока я не скажу их сдать" },
			[8] = { str = "8. Идите на северо-восток к 51,78 и гриндите гулей здесь, пока не наберёте достаточно для #DOQUESTClear The Way#", x = 51, y = 78, zone = "Western Plaguelands" },
			[9] = { str = "9. Идите обратно в Chillwind Camp в 42,84 и сдайте #TURNINClear The Way# возьмите #ACCEPTAll Along the Watchtowers# и #ACCEPTThe Scourge Cauldrons#", x = 42, y = 84, zone = "Western Plaguelands" },
			[10] = { str = "10. Развернитесь и сдайте #TURNINThe Scourge Cauldrons# возьмите #ACCEPTTarget: Felstone Field#" },
			[11] = { str = "11. Теперь вы должны быть примерно в 5-10к от 57 уровня" },
			[12] = { str = "12. Идите обратно на северо-восток к 48,72 и перейдите мост", x = 48, y = 72, zone = "Western Plaguelands" },
			[13] = { str = "13. Прямо в городе слева в 47,71 находится 4-я башня для #DOQUESTAll Along the Watchtowers#, внутри элитные мобы, но вы можете стоять вне LOS на краю и легко пометить двери. 1-я башня к западу отсюда в 40,71. 2-я башня к северо-востоку отсюда в 42,66. 3-я башня к северо-востоку отсюда в 44,63. Прямо за этой башней.", x = 47, y = 71, zone = "Western Plaguelands" },
			[14] = { str = "14. Идите на северо-запад к 37,56 к Felstone field, убейте #NPCCauldron Lord Bilemaw# ради его ключа от котла. Затем щёлкните правой кнопкой по котлу и сдайте #TURNINTarget: Felstone Field# возьмите #ACCEPTReturn to Chillwind Camp#", x = 37, y = 56, zone = "Western Plaguelands" },
			[15] = { str = "15. На северо-восточной стороне поля в 38,54 есть 2 дома, зайдите в северный дом и поднимитесь наверх. Возьмите #ACCEPTBetter Late Than Never pt.1#", x = 38, y = 54, zone = "Western Plaguelands" },
			[16] = { str = "16. Зайдите в амбар по соседству и возьмите коробку на полу и сдайте #TURNINBetter Late Than Never pt.1# возьмите #ACCEPTBetter Late Than Never pt.2#" },
			[17] = { str = "17. Бегите обратно в Chillwind Camp в 42,84 и сдайте #TURNINAll Along the Watchtowers#, возьмите #ACCEPTScholomance# ПРОПУСТИТЕ другое, если не найдёте 10-20 человек.", x = 42, y = 84, zone = "Western Plaguelands" },
			[18] = { str = "18. Сдайте #TURNINScholomance# прямо за ним, возьмите #ACCEPTSkeletal Fragments Bones# для этого потребуется время и дропается со всех скелетов." },
			[19] = { str = "19. Рядом с полетчиком сдайте #TURNINReturn to Chillwind Camp# возьмите #ACCEPTTarget: Dalson's Tears#" },
			[20] = { str = "20. Идите наверх к 46,52 к Dalson’Tears, убейте #NPCCauldron Lord Malvinious# ради его ключа от котла. Затем щёлкните правой кнопкой по котлу и сдайте #TURNINTarget: Dalson's Tears# возьмите #ACCEPTReturn to Chillwind Camp#", x = 46, y = 52, zone = "Western Plaguelands" },
			[21] = { str = "21. Зайдите в амбар здесь в 47,50 и коснитесь дневника на полу и завершите его, ещё одно задание, которое не задание.", x = 47, y = 50, zone = "Western Plaguelands" },
			[22] = { str = "22. Идите за амбар и поищите Wandering Skeleton и получите с него Dalson Outhouse Key. Используйте его, чтобы открыть уборную здесь сзади и убить Farmer Dalson и получить его Dalson Cabinet Key. Используйте ключ на запертом шкафу наверху в доме теперь в 47,49 рядом с амбаром и завершите задание #TURNINLocked Away#", x = 47, y = 49, zone = "Western Plaguelands" },
			[23] = { str = "23. Идите обратно в Chillwind Camp в 42,84 и сдайте #TURNINReturn to Chillwind Camp# возьмите #ACCEPTTarget: Writhing Haunt#", x = 42, y = 84, zone = "Western Plaguelands" },
			[24] = { str = "24. Жмите Hearth в IF, затем летите в SW" },
			[25] = { str = "25. Идите в здание в 48,30 на 2-м этаже области собора и сдайте #TURNINBetter Late Than Never pt.2# возьмите #ACCEPTGood Natured Emma#", x = 48, y = 30, zone = "Stormwind" },
			[26] = { str = "26. Emma перемещается между собором и торговым районом, найдите её и сдайте #TURNINGood Natured Emma# возьмите #ACCEPTGood Luck Charm#" },
			[27] = { str = "27. Идите в крепость в 78,17 и возьмите #ACCEPTThe First and the Last#", x = 78, y = 17, zone = "Stormwind" },
			[28] = { str = "28. Идите к 75,79 и сдайте #TURNINThe First and the Last# возьмите #ACCEPTHonor the Dead# затем сдайте сразу обратно, возьмите #ACCEPTFlint Shadowmore#", x = 75, y = 79, zone = "Stormwind" },
			[29] = { str = "29. Летите обратно в WPL" },
			[30] = { str = "30. Перед домом сдайте #TURNINFlint Shadowmore# возьмите #ACCEPTThe Eastern Plagues#" },
			[31] = { str = "31. Идите обратно к Felstone field в дом наверху в 38,54 и сдайте #TURNINGood Luck Charm# возьмите #ACCEPTTwo Halves Become One# Выйдите и поищите jabbering ghoul. Вы его не пропустите, он носит вилы. Продолжайте зачищать перед домом, пока не найдёте его. Это даст вам хорошее время, чтобы получить те skeletal fragments", x = 38, y = 54, zone = "Western Plaguelands" },
			[32] = { str = "32. Объедините половинки и идите обратно наверх и сдайте #TURNINTwo Halves Become One#" },
			[33] = { str = "33. Идите на юго-восток к 53,65 к Writhing Haunt, убейте #NPCCauldron Lord Razarch# ради его ключа от котла. Затем щёлкните правой кнопкой по котлу и сдайте #TURNINTarget: Writhing Haunt# возьмите #ACCEPTReturn to Chillwind Camp#", x = 53, y = 65, zone = "Western Plaguelands" },
			[34] = { str = "34. В доме в 54,65 возьмите #ACCEPTThe Wildlife Suffers Too pt.1# теперь идите на север от haunt и убивайте больных волков. Не идите дальше на восток, чтобы найти их, просто идите на север, может немного на северо-запад.", x = 54, y = 65, zone = "Western Plaguelands" },
			[35] = { str = "35. Идите обратно к 54,65 и сдайте #TURNINThe Wildlife Suffers Too pt.1# возьмите #ACCEPTThe Wildlife Suffers Too pt.2#", x = 54, y = 65, zone = "Western Plaguelands" },
			[36] = { str = "36. Идите обратно в Chillwind Camp в 42,84 и сдайте #TURNINReturn to Chillwind Camp# возьмите #ACCEPTTarget: Gahrron's Withering#", x = 42, y = 84, zone = "Western Plaguelands" },
			[37] = { str = "37. Идите чуть севернее Writhing Haunt между горами на карте в 52,56 и убивайте больных гризли по пути вниз к 62,58 для #DOQUESTThe Wildlife Suffers Too pt.2#", x = 52, y = 56, zone = "Western Plaguelands" },
			[38] = { str = "38. Идите на северо-восток к 62,58 к Gahrron’s Withering, убейте #NPCCauldron Lord Soulwrath# ради его ключа от котла. Затем щёлкните правой кнопкой по котлу и сдайте #TURNINTarget: Gahrron's Withering# возьмите #ACCEPTReturn to Chillwind Camp#", x = 62, y = 58, zone = "Western Plaguelands" },
			[39] = { str = "39. Идите обратно к 54,65 и сдайте #TURNINThe Wildlife Suffers Too pt.2# возьмите #ACCEPTGlyphed Oaken Branch#", x = 54, y = 65, zone = "Western Plaguelands" },
			[40] = { str = "40. Если вы ещё не закончили Skeletal Fragments, идите в склеп в 54,79 и убивайте скелетов, пока не получите 15 фрагментов", x = 54, y = 79, zone = "Western Plaguelands" },
			[41] = { str = "41. Идите обратно в Chillwind Camp в 42,84 и сдайте #TURNINReturn to Chillwind Camp#", x = 42, y = 84, zone = "Western Plaguelands" },
			[42] = { str = "42. Развернитесь к парню перед палаткой и завершите задание #TURNINMission Accomplished!# нет ссылки, потому что это снова не задание лол. Теперь видите, что беготня туда-сюда казалась лишней, но в конце был огромный буст опыта и хороший опыт по ходу." },
			[43] = { str = "43. Справа сдайте #TURNINSkeletal Fragments# ПРОПУСТИТЕ следующую часть, если не хотите начинать свой ключ от scholo." },
			[44] = { str = "44. Бегите на восток к 70,50 и войдите в Eastern Plaguelands (EPL)", x = 70, y = 50, zone = "Western Plaguelands" },
		}
	},

-----------57-58 Eastern Plaguelands
	--[512] = {
	[5758] = {
		title = "57-58 Eastern Plaguelands",
		--n = "57-58 Eastern Plaguelands",
		--pID = 511, nID = 513,
		--itemCount = 21,
		items = {
			[1] = { str = "1. 57-58 Eastern Plaguelands" },
			[2] = { str = "2. Бегите вверх по западному побережью к 67,4 и возьмите 3 задания #ACCEPTDemon Dogs# #ACCEPTBlood Tinged Skies# и #ACCEPTCarrion Grubbage#", x = 67, y = 4, zone = "Eastern Plaguelands" },
			[3] = { str = "3. Это раздражающие задания, которые могут занять время. С этого момента и до их завершения убивайте любых plaguehound runts, carrion worms или plaguebats." },
			[4] = { str = "4. Отсюда и вниз к большей области убивайте любых собак, червей и летучих мышей. Сосредоточьтесь на них, пока направляетесь к следующему шагу" },
			[5] = { str = "5. Продолжайте убивать собак и летучих мышей и направляйтесь к скелету в 28,74 откройте его и заберите значок для #DOQUESTThe Eastern Plagues# затем бегите немного дальше к следующему скелету в 27,74 и заберите значок, он практически прямо перед ним, и вы также получите сообщение о завершении blightcaller found. Теперь идите вниз к дороге в 28,79 и залутайте последний значок со скелета", x = 28, y = 74, zone = "Eastern Plaguelands" },
			[6] = { str = "6. Сосредоточьтесь на собаках и летучих мышах, пока направляетесь к Darrowshire в 36,90 в разрушенный дом. Сдайте #TURNINSister Pamela# возьмите #ACCEPTPamela's Doll# затем направляйтесь к домам здесь, в любом из домов может быть любая из 3 частей куклы. Они случайны. Призраки появляются, когда вы приближаетесь к частям, так что будьте осторожны. Как только у вас есть все 3 части, объедините их и идите обратно к 36,90 и сдайте #TURNINPamela's Doll# возьмите #ACCEPTAuntie Marlene# и #ACCEPTUncle Carlin#", x = 36, y = 90, zone = "Eastern Plaguelands" },
			[7] = { str = "7. Посмотрите на карту в 48,76 Это совпадает с тем средним хребтом гор. Не идите дальше на восток от этого места, пока не получите убийства plaguehound runt для #DOQUESTDemon Dogs# и plaguebats для #DOQUESTBlood Tinged Skies#, потому что дальше их нет.", x = 48, y = 76, zone = "Eastern Plaguelands" },
			[8] = { str = "8. Не забудьте убивать личинок по пути для #DOQUESTCarrion Grubbage#, они не так важны, потому что их везде полно." },
			[9] = { str = "9. Убивайте Plaguehounds для Demon Dogs повсюду вокруг 56,57 это к северу от шрама и к югу от blackwood lake. Не забудьте личинок", x = 56, y = 57, zone = "Eastern Plaguelands" },
			[10] = { str = "10. Убивайте Frenzied Plaguehounds для #DOQUESTDemon Dogs# повсюду вокруг 61,41 это к северу от blackwood lake, но теперь к западу от него.", x = 61, y = 41, zone = "Eastern Plaguelands" },
			[11] = { str = "11. Направляйтесь к lights hope chapel в 81,58, если вам всё ещё нужно мясо личинок для #DOQUESTCarrion Grubbage#, затем убивайте их по пути", x = 81, y = 58, zone = "Eastern Plaguelands" },
			[12] = { str = "12. Возьмите полетчика" },
			[13] = { str = "13. Сдайте #TURNINUncle Carlin# возьмите #ACCEPTDefenders of Darrowshire#" },
			[14] = { str = "14. Развернитесь и сдайте #TURNINDuke Nicholas Zverenhoff#" },
			[15] = { str = "15. Бегите на юго-запад к 79,63 и возьмите #ACCEPTZaeldarr the Outcast#", x = 79, y = 63, zone = "Eastern Plaguelands" },
			[16] = { str = "16. Летите обратно в EPL" },
			[17] = { str = "17. Перед домом сдайте #TURNINThe Eastern Plagues# возьмите #ACCEPTThe Blightcaller Cometh#" },
			[18] = { str = "18. Если вы в пределах 6,600 до уровня, то жмите Hearth в IF и летите в SW, если нет, то гриндите, пока не будете в диапазоне." },
			[19] = { str = "19. Идите к 78,18 в крепость и сдайте #TURNINThe Blightcaller Cometh# теперь я ПРОПУСКАЮ следующую часть, но это хорошее задание для 60", x = 78, y = 18, zone = "Eastern Plaguelands" },
			[20] = { str = "20. Идите получать новые навыки" },
			[21] = { str = "21. Летите обратно в WPL" },
		}
	},

-----------58-58 Western Plaguelands
	--[513] = {
	[5857] = {
		title = "58-58 Western Plaguelands",
		--n = "58-58 Western Plaguelands",
		--pID = 512, nID = 514,
		--itemCount = 9,
		items = {
			[1] = { str = "1. 58-58 Western Plaguelands" },
			[2] = { str = "2. Идите на северо-восток к дому в 49,78 и поднимитесь наверх. Сдайте #TURNINPamela's Doll# возьмите #ACCEPTA Strange Historian#", x = 49, y = 78, zone = "Western Plaguelands" },
			[3] = { str = "3. Прямо к северу от дома в 49,76 вы увидите надгробие другого цвета. Залутайте его и получите обручальное кольцо для #DOQUESTA Strange Historian#", x = 49, y = 76, zone = "Western Plaguelands" },
			[4] = { str = "4. Зайдите в западный вход в Andorhal в 39,71 и вы должны увидеть единственное целое здание, похоже на таверну в 39,68. Поднимитесь наверх и сдайте #TURNINA Strange Historian# возьмите #ACCEPTThe Annals of Darrowshire# также возьмите #ACCEPTA Matter of Time#", x = 39, y = 68, zone = "Western Plaguelands" },
			[5] = { str = "5. Теперь ищите по всему городу сломанные силосы с синим светом из них. Используйте silo horn, чтобы призвать червей, появляется 1-3 моба для #DOQUESTA Matter of Time#. Когда убьёте последнего, у них есть тенденция призвать ещё одного. Они больше на восточной стороне города" },
			[6] = { str = "6. Идите в ратушу рядом со всеми мобами в центре города, вы можете пробраться с юго-западной стороны. Берите книги на полу, пока не получите #ACCEPTThe Annals of Darrowshire# Некоторые призывают мобов" },
			[7] = { str = "7. Идите обратно в таверну в 39,68 на верхний этаж, сдайте #TURNINA Matter of Time# возьмите #ACCEPTCounting Out Time# также сдайте #TURNINThe Annals of Darrowshire# возьмите #ACCEPTBrother Carlin#", x = 39, y = 68, zone = "Western Plaguelands" },
			[8] = { str = "8. Выйдите и поищите вокруг разрушенных домов маленькие металлические ланчбоксы для #DOQUESTCounting Out Time#" },
			[9] = { str = "9. Идите обратно в таверну в 39,68 и сдайте #TURNINCounting Out Time# теперь вы можете повторять это задание для dampener. Это используется против 61 элитного", x = 39, y = 68, zone = "Western Plaguelands" },
		}
	},

-----------58-58 Eastern Plaguelands
	--[514] = {
	[5858] = {
		title = "58-58 Eastern Plaguelands",
		--n = "58-58 Eastern Plaguelands",
		--pID = 513, nID = 515,
		--itemCount = 18,
		items = {
			[1] = { str = "1. 58-58 Eastern Plaguelands" },
			[2] = { str = "2. Выбегите отсюда и в EPL наверх к северо-западу в 7,43 и сдайте 3 задания #TURNINDemon Dogs# #TURNINBlood Tinged Skies# и #TURNINCarrion Grubbage# возьмите #ACCEPTRedemption# затем выслушайте его и сдайте обратно. Затем возьмите #ACCEPTOf Forgotten Memories#", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[3] = { str = "3. Идите к Undercroft в 28,86 и бегите за него. Коснитесь кучи земли, чтобы призвать Mercutio и 3 охранников. Самый простой способ сделать это — кайтить его от его друзей или найти группу. Залутайте его тело ради молота для #DOQUESTOf Forgotten Memories#", x = 28, y = 86, zone = "Eastern Plaguelands" },
			[4] = { str = "4. Теперь идите в низ склепа и убейте очень большого тролля для #DOQUESTZaeldarr the Outcast# Берите свиток на полу, только если хотите" },
			[5] = { str = "5. Идите обратно к 7,43 и сдайте #TURNINOf Forgotten Memories# возьмите #ACCEPTOf Lost Honor#", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[6] = { str = "6. Либо бегите к Light’s Hope Chapel, либо обратно в Chillwind и летите туда" },
			[7] = { str = "7. Сдайте #TURNINBrother Carlin# возьмите #ACCEPTVillains of Darrowshire#" },
			[8] = { str = "8. Идите вниз к 79,63 и сдайте #TURNINZaeldarr the Outcast#", x = 79, y = 63, zone = "Eastern Plaguelands" },
			[9] = { str = "9. Идите вниз чуть севернее Corin’s Crossing к 53,65 и заберите меч для #DOQUESTVillains of Darrowshire# Он внизу в шраме. Не забудьте сделать часть #DOQUESTDefenders of Darrowshire# у Corin’s Просто соберите, что сможете", x = 53, y = 65, zone = "Eastern Plaguelands" },
			[10] = { str = "10. Идите на север к Blackwood Lake в 51,49 и заберите череп под водой для #DOQUESTVillains of Darrowshire#", x = 51, y = 49, zone = "Eastern Plaguelands" },
			[11] = { str = "11. Идите на северо-восток к 65,41 и убивайте зомби для части #DOQUESTDefenders of Darrowshire# здесь их довольно много, вы, вероятно, сможете закончить", x = 65, y = 41, zone = "Eastern Plaguelands" },
			[12] = { str = "12. Идите к озеру в 71,33 и заберите флаг рядом с клеткой, его трудно увидеть, и он лежит плоско для #DOQUESTOf Lost Honor#", x = 71, y = 33, zone = "Eastern Plaguelands" },
			[13] = { str = "13. Идите на северо-запад к башне в 56,24 и сдайте #TURNINTroubled Spirits of Kel'Theril# ПРОПУСТИТЕ следующую часть", x = 56, y = 24, zone = "Eastern Plaguelands" },
			[14] = { str = "14. Бегите на запад к 45,34 и залутайте термитники здесь для #DOQUESTA Plague Upon Thee pt.1#, пока не получите 100 термитов, также убивайте гулей, чтобы закончить #DOQUESTDefenders of Darrowshire#", x = 45, y = 34, zone = "Eastern Plaguelands" },
			[15] = { str = "15. Бегите к Lights Hope Chapel теперь" },
			[16] = { str = "16. Идите к палатке и сдайте #TURNIN“Defenders of Darrowshire”# и #TURNIN“Villains of Darrowshire”#" },
			[17] = { str = "17. Летите в WPL" },
			[18] = { str = "18. Рядом с домом сдайте #TURNIN“A Plague Upon Thee pt.1”# возьмите #ACCEPT“A Plague Upon Thee pt.2”#" },
		}
	},

------------58-59 Western Plaguelands
	--[515] = {
	[5859] = {
		title = "58-59 Western Plaguelands",
		--n = "58-59 Western Plaguelands",
		--pID = 514, nID = 516,
		--itemCount = 19,
		items = {
			[1] = { str = "1. 58-59 Western Plaguelands" },
			[2] = { str = "2. Бегите наверх к 51,28 и возьмите #ACCEPT“Unfinished Business pt.1”#", x = 52, y = 30, zone = "Western Plaguelands" },
			[3] = { str = "3. Начните направляться обратно на юго-запад к 47,32 и пробивайтесь к мельнице. Щёлкните правой кнопкой по коробке и разместите термитов, затем щёлкните по бочке и сдайте #TURNIN“A Plague Upon Thee pt.2”# возьмите #ACCEPT“A Plague Upon Thee pt.3”#", x = 47, y = 32, zone = "Western Plaguelands" },
			[4] = { str = "4. Идите чуть южнее 49,42 и убейте 2 рыцарей и магов для #DOQUEST“Unfinished Business pt.1”# затем 51,43 для охотников и медиков", x = 49, y = 42, zone = "Western Plaguelands" },
			[5] = { str = "5. Идите к 51,28 и сдайте #TURNIN“Unfinished Business pt.1”# возьмите #ACCEPT“Unfinished Business pt.2”#", x = 51, y = 28, zone = "Western Plaguelands" },
			[6] = { str = "6. Идите к 57,36 и убейте Huntsman Radly для #DOQUEST“Unfinished Business pt.2”# затем на север к башне в 55,23 и убейте Cavalier Durgen наверху", x = 57, y = 36, zone = "Western Plaguelands" },
			[7] = { str = "7. Идите прямо из башни через горы к 51,28 и сдайте #TURNIN“Unfinished Business pt.2”# делать 3-ю часть #DOQUEST“Unfinished Business pt.3”# опционально. Некоторые классы могут сделать это легче, чем другие. Вам нужно бежать на север к hearthglen и подняться в большую башню в центре города в 45,18 и смотреть через край, пока не напишет complete.", x = 45, y = 18, zone = "Western Plaguelands" },
			[8] = { str = "8. Бегите обратно прямо на юг через горы к 51,28 и сдайте #TURNIN“Unfinished Business pt.3”#", x = 51, y = 28, zone = "Western Plaguelands" },
			[9] = { str = "9. Бегите в EPL и наверх к 7,43 и сдайте #TURNIN“Of Lost Honor”# возьмите #ACCEPT“Of Love and Family pt.1”#", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[10] = { str = "10. Идите обратно в WPL и бегите/плывите к острову, где находится Scholo, в 65,75 и сдайте #TURNIN“Of Love and Family pt.1”# ПРОПУСТИТЕ остальное, пока не сделаете strat", x = 65, y = 75, zone = "Western Plaguelands" },
			[11] = { str = "11. Идите обратно в Chillwind Camp в 43,84 и сдайте #TURNIN“A Plague Upon Thee pt.3”#", x = 43, y = 84, zone = "Western Plaguelands" },
			[12] = { str = "12. Теперь вы хотите сделать 2 вещи здесь. Стать friendly с Argent Dawn и получить 8-8.5к до левелапа. Вы можете сделать #DOQUEST“Alas, Andorhal”# если найдёте группу, это не так сложно, но может занять 5-10 человек. Это даст вам лёгкие 8300 опыта вместо гринда." },
			[13] = { str = "13. Теперь вы хотите пойти в andorhal и просто гриндить, пока не станете friendly, как только станете friendly, идите обратно в Chillwind Camp и сдайте все свои scourge tokens. Это позволяет покупать mana biscuits, которые восстанавливают ману и здоровье и больше, чем еда. Если вам всё ещё нужно левелиться, то идите гриндить мобов в andorhal снова, пока не будете в 8-8.5к от 59 уровня" },
			[14] = { str = "14. Как только вы в 8к-8.5к от левелапа, летите в Hinterlands и бегите всю дорогу на северо-восток к водопаду в 80,46 и прыгайте. Под водой залутайте сундук и завершите #DOQUEST“Cortello’s Riddle pt.3”#", x = 80, y = 46, zone = "The Hinterlands" },
			[15] = { str = "15. Жмите Hearth в IF" },
			[16] = { str = "16. Идите в тронный зал в 43,52 и возьмите #ACCEPT“An Earnest Proposition”# (выберите свой класс из списка) У вас должны быть напульсники tier 0 вашего класса, чтобы сделать это задание. Вы можете купить их на AH", x = 43, y = 52, zone = "Ironforge" },
			[17] = { str = "17. Летите в Menethil и плывите в Auberdine, летите в Darnassus" },
			[18] = { str = "18. Идите к 35,8 на 2-м этаже и сдайте #TURNIN“Glyphed Oaken Branch”#", x = 35, y = 8, zone = "Darnassus" },
			[19] = { str = "19. Теперь вы должны быть 59 уровня, летите в Winterspring" },
		}
	},

------------59-60 Winterspring
	--[516] = {
	[5960] = {
		title = "59-60 Winterspring",
		--n = "59-60 Winterspring",
		--pID = 515, nID = 516,
		--itemCount = 35,
		items = {
			[1] = { str = "1. 59-60 Winterspring" },
			[2] = { str = "2. Слева после входа сдайте #TURNIN“Are We There, Yeti? pt.3”#" },
			[3] = { str = "3. Ближе к задней части находятся 2 ордынца, возьмите #ACCEPT“Luck Be With You”#" },
			[4] = { str = "4. Развернитесь и сдайте #TURNIN“Felnok Steelspring”# возьмите #ACCEPT“Chillwind Horns”#" },
			[5] = { str = "5. #HUNTER4) Stable your pet#" },
			[6] = { str = "6. #HUNTER5) Бегите на север к frostsaber rock в 51,15 и приручите Frostsaber Stalker для prowl и dash rank 3.#", x = 51, y = 15, zone = "Winterspring" },
			[7] = { str = "7. Сделайте #DOQUEST“An Earnest Proposition”# просто убивайте сабель, пока не получите 15 крови" },
			[8] = { str = "8. Идите чуть юго-восточнее отсюда около 55,18 и убивайте химер для #DOQUEST“Chillwind Horns”#", x = 55, y = 18, zone = "Winterspring" },
			[9] = { str = "9. #HUNTER8) Как только это сделаете, приручите Winterspring Screecher для Claw rank 8#" },
			[10] = { str = "10. Бегите к Starfall Village в 52,30 и возьмите #ACCEPT“Enraged Wildkin pt.1”#", x = 52, y = 30, zone = "Winterspring" },
			[11] = { str = "11. Бегите обратно в everlook $HUNTERи достаньте кота обратно#" },
			[12] = { str = "12. Сдайте #TURNIN“Chillwind Horns”# ПРОПУСТИТЕ другое, если не хотите туда идти" },
			[13] = { str = "13. Идите на юг к 59,59 и коснитесь ящика и сдайте #TURNIN“Enraged Wildkin pt.1”# возьмите #ACCEPT“Enraged Wildkin pt.2”#", x = 59, y = 59, zone = "Winterspring" },
			[14] = { str = "14. Идите обратно к дороге в 61,60 и коснитесь фургона, сдайте #TURNIN“Enraged Wildkin pt.2”# возьмите #ACCEPT“Enraged Wildkin pt.3”# заберите коробку в снегу", x = 61, y = 60, zone = "Winterspring" },
			[15] = { str = "15. Бегите на восток снова к 63,59 и сдайте #TURNIN“Find Ranshalla”# возьмите #ACCEPT“Guardians of the Altar”#", x = 63, y = 59, zone = "Winterspring" },
			[16] = { str = "16. Теперь защищайте её, пока она делает своё дело. Убедитесь, что получили перо с совы для #DOQUEST“Enraged Wildkin pt.3”# Когда она останавливается в пещере, зажгите для неё факел. Если не получили перо до того, как закончите, продолжайте убивать, пока не получите." },
			[17] = { str = "17. Идите на юг к 62,69 и залутайте самоцветы для #DOQUEST“Luck Be With You”# охотники и локи могут использовать пета, чтобы отвлекать мобов, пока лутают, другим классам придётся группироваться.", x = 62, y = 69, zone = "Winterspring" },
			[18] = { str = "18. Жмите Hearth в Everlook" },
			[19] = { str = "19. Сдайте #TURNIN“Luck Be With You”# у 2 ордынцев ближе к задней части everlook" },
			[20] = { str = "20. Теперь вы должны быть примерно на 25% в 59 уровне." },
			[21] = { str = "21. Возьмите #ACCEPT“Cache of Mau'Ari”# если хотите. Это просто даёт вам предмет, который позволяет мобам здесь дропать вещи, которые вы можете сдать на баффы" },
			[22] = { str = "22. Идите наверх к Starfall Village в 52,30 и сдайте #TURNIN“Enraged Wildkin pt.3”#", x = 52, y = 30, zone = "Winterspring" },
			[23] = { str = "23. Бегите к 31,45 и сдайте #TURNIN“Mystery Goo”# возьмите #ACCEPT“Toxic Horrors”#", x = 31, y = 45, zone = "Winterspring" },
			[24] = { str = "24. Бегите в Felwood и идите к 48,24 и убивайте токсичных ужасов для #DOQUEST“Toxic Horrors”# они также дропают essence of waters", x = 48, y = 24, zone = "Felwood" },
			[25] = { str = "25. Летите в Rut’theran Village и идите в дом в 55,92 и сдайте #TURNIN“Guardians of the Altar”# возьмите #ACCEPT“Wildkin of Elune”#", x = 55, y = 92, zone = "Teldrassil" },
			[26] = { str = "26. Идите в Darnassus и наверх к вершине башни в 34,8 и сдайте #TURNIN“Wildkin of Elune”#", x = 34, y = 8, zone = "Darnassus" },
			[27] = { str = "27. Летите обратно в Felwood" },
			[28] = { str = "28. Бегите обратно наверх в Winterspring и к 31,45 сдайте #TURNIN“Toxic Horrors”# возьмите #ACCEPT“Winterfall Runners”#", x = 31, y = 45, zone = "Winterspring" },
			[29] = { str = "29. Теперь найти бегунов. Они путешествуют от пещеры Timbermaw на восток к 53,34 затем вверх вокруг гор к северу от everlook к Winterfall Village. Если вы не видели их от пещеры до сюда, направляйтесь на восток. Вам не нужно убивать всех 3", x = 53, y = 34, zone = "Winterspring" },
			[30] = { str = "30. Как только получите ящик, бегите обратно к 31,45 Сдайте Winterfall Runners, из озера придёт засада, если вы не отойдёте от палатки, они не сагрятся. ПРОПУСТИТЕ следующую часть, если не найдёте группу", x = 31, y = 45, zone = "Winterspring" },
			[31] = { str = "31. Жмите Hearth в Everlook" },
			[32] = { str = "32. Теперь вы должны быть на 45-50% в 59 уровне. Теперь я убеждаюсь, что у меня есть mana bisquits, и начинаю гриндить, пока не останется 6600 до 60 уровня.  Любое место подойдёт, где много мобов. Это всё дело предпочтения. Я выбираю owl wing thicket в 64,62 или что угодно к северу от everlook. Мне нравится убивать фурболгов для репутации timbermaw тоже.", x = 64, y = 62, zone = "Winterspring" },
			[33] = { str = "33. Если не хотите гриндить это большое количество, то делайте BRD, scholo или strat. У вас есть много заданий в этих местах" },
			[34] = { str = "34. Как только вы в 6600 до 60, идите в IF и сдайте #TURNINAn Earnest Proposition#" },
			[35] = { str = "35. Поздравляю с 60!" },
		}
	},
}
